### PR TITLE
doc: renaming of the master branch

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

As discussed on the mailing list, the `master` branch in the repo is about to be renamed to `main`.
This PR should cover all the required changes to the internal doc and pre-commit hooks.

Opening as a draft ahead of the actual operation.

edit: note that GitHub's hardwork on making this change seamless means that this PR is not even breaking tests workflows
that rely on checking the "main" branch 🤯 

see https://github.com/github/renaming

## PR Checklist

- [x] New features are documented, with docstrings and narrative docs
- [ ] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
(changed the automated name which reflected my very narrowly scoped original intention with the PR)

**Comment by matthewturk** [comment]
this looks good

**Review by cphyc — APPROVED** [review]
This looks good to me, thanks for fixing this.

**Comment by neutrinoceros** [comment]
resolved a conflict in pre-commit-config.yaml
This should be ready when test pass again :)

**Pull request merged**
