### PR TITLE
TST: add --fix-missing flag to apt-get calls in ci_install.sh

### LINKED ISSUE #4299: TST: ci_install.sh is currently flaky
### Bug report

**Bug summary**

Many CI jobs are failing randomly these days with
Screenshot 2023-01-13 at 10 44 19

Let's try the solutions contain in the error message

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary
Supposedly fix #4299

### CODE REVIEW

**Comment by neutrinoceros** [comment]
Note on apt-get's doc
Screenshot 2023-01-13 at 11 19 07

**Comment by neutrinoceros** [comment]
All I can say for sure now is that the issue didn't show while running CI on this PR, but I can't tell if it was just a lucky run.
@Xarthisius I'd like your opinion on this one, but if I don't hear from you today I may just try to merge and backport it as is.

**Comment by Xarthisius** [comment]
It's a connectivity issue. It's unlikely that --fix-missing will solve that, it will just postpone the error. Imagine the situation that apt cannot install `openmpi`, cause it cannot fetch the package. With `--fix-missing` apt will "succeed", but later when we call `mpiexec` it's not gonna be there...

**Comment by neutrinoceros** [comment]
Good call. Let's not keep this PR then.

**Pull request closed without merging**
