### PR TITLE
Remove LinearLocator, LogLocator from Visualization

### PR DESCRIPTION
**Pull request by git-abhishek**
## PR Summary
Cleanup by removing `LinearLocator`, `LogLocator` ~and `FieldTransform`~.

## PR Checklist

- [X] Code passes flake8 checker

## Adding Reviewers
@ngoldbaum @Xarthisius @colinmarc

### CODE REVIEW

**Comment by git-abhishek** [comment]
@ngoldbaum Does the [`LogLocator`](https://github.com/yt-project/yt/blob/master/yt/visualization/tick_locators.py#L17) implementation complete and correct?

**Comment by MatthewTurk** [comment]
I think this is a good change, but I'd go even further to get rid of the `FieldTransform` objects altogether and just use strings.

**Comment by ngoldbaum** [comment]
And in places where you need to use the funciton (where is that happening btw?) you could either use a lambda or just define a function outside of the `FieldTransform` class and use the functions where they're needed.

**Comment by git-abhishek** [comment]
Its happening [here](https://github.com/yt-project/yt/blob/08606e8a2c8684b1ce7e16f095084b2833b1b9bb/yt/visualization/plot_container.py#L243). 
```
self._field_transform[field] = symlog_transform
self._field_transform[field].func = linthresh
```
How should this be handled, if we want `self._field_transfrom[field]` to be just string?
My earlier commit failed due to this error:

>ERROR: yt.visualization.tests.test_plotwindow.test_symlog_colorbar
>----------------------------------------------------------------------
>Traceback (most recent call last):
>  File "/home/travis/build/yt-project/yt/venv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
>    self.test(*self.arg)
>  File "/home/travis/build/yt-project/yt/yt/visualization/tests/test_plotwindow.py", line 551, in test_symlog_colorbar
>    plot.set_log(field, True, linthresh=0.1)
>  File "/home/travis/build/yt-project/yt/yt/visualization/plot_container.py", line 76, in newfunc
>    rv = f(*args, **kwargs)
>  File "/home/travis/build/yt-project/yt/yt/visualization/plot_container.py", line 219, in set_log
>    self._field_transform[field].func = linthresh
>AttributeError: 'str' object has no attribute 'func'

**Comment by ngoldbaum** [comment]
Ah I see, we do actually need the function, it gets passed to matplotlib here:

https://github.com/yt-project/yt/blob/master/yt/visualization/plot_window.py#L842-L847

So I guess we really do need both a name and a function, so it makes sense to keep the `FieldTransform` object. I guess we could use a tuple or something like that, but I think that would end up less clear.

I think this is fine as-is.

**Pull request merged**
