### PR TITLE
[bugfix] Fix field calculation for octrees

### PR DESCRIPTION
**Pull request by cphyc**
At the moment, the current fields cannot be computed for octree datasets (RAMSES & ART).
- [x] `("gas", "average_density")`
- [ ] `("gas", "shear_mach")`

# Steps to reproduce
```python
import yt

ds = yt.load_sample("output_00080")
ds.r["gas", "shear_mach"]       # raises RuntimeError
ds.r["gas", "average_density"]  # raises YTFieldNotFound
```

## Expected behaviour
The script should be able to run till the end. Note that it may catch some `yt.fields.field_exceptions.NeedsParameter` exceptions.

```python
import yt
from tqdm import tqdm
import numpy as np

# ds = yt.load_sample("enzo_tiny_cosmology")
ds = yt.load_sample("output_00080")
ad = ds.all_data()

for ftype, fname in tqdm(np.random.permutation(ds.derived_field_list)):
    if "cutting_plane" in fname:  # need to skip cutting planes as they require a cutting plane!
        continue
    if fname in ("shear_mach", "average_density"):  # these trigger catastrophic failures, skip them
        continue
    yt.mylog.debug("Computing field %s", (ftype, fname))
    try:
        ad[ftype, fname]
    except:
        yt.mylog.error("Got exception for field (%s, %s)", ftype, fname, exc_info=True)
```

### CODE REVIEW

**Comment by cphyc** [comment]
The second item turns out to be quite involved. After some digging, it is related to the way the grid level is computed for octrees. I cannot find a good way of fixing it at the moment, so I'd be happy to have this PR merged to fix item 1 and I'll open an issue for solving item 2.

**Comment by munkm** [comment]
That sounds good! Since i'll be writing the changelog soon -- this specifically fixes field calculation for `average_density` on octrees, right?

**Review by munkm — APPROVED** [review]
If possible, I think we should add a test for a field that was fixed in this PR.

**Comment by cphyc** [comment]
> That sounds good! Since i'll be writing the changelog soon -- this specifically fixes field calculation for `average_density` on octrees, right? Are there any other fields that this could apply to?

In principle the same approach could be reused for other fields, but I couldn't find any for which it was required. I'll add a test.

**Comment by munkm** [comment]
Do you want me to merge and open an issue for the test, or wait until one is added here to merge?

**Comment by cphyc** [comment]
Opening an issue is probably best!

8 Apr 2021 8:06:10 pm Madicken Munk ***@***.***>:

**Pull request merged**
