### PR TITLE
update API docs for missing/moved classes

### PR DESCRIPTION
**Pull request by brittonsmith**
A number of data container classes were moved in recent reorgs, breaking the api docs links. I also encountered some that were missing.

## PR Checklist

- [ ] New features are documented, with docstrings and narrative docs
- [ ] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Review by neutrinoceros — APPROVED** [review]

**Review by cphyc — APPROVED** [review]

**Comment by brittonsmith** [comment]
Does anyone know how to interpret the docs build failure?

**Comment by neutrinoceros** [comment]
Looks like timeout... usually running again fixes it.
@yt-fido test this please

**Review by munkm — APPROVED** [review]
Thank you for finding and fixing these @brittonsmith !

**Comment by brittonsmith** [comment]
Still failing. Is it actually related to this PR or is the docs build just failing?

**Comment by neutrinoceros** [comment]
🤷🏻‍♂️
@Xarthisius ?

**Comment by Xarthisius** [comment]
@yt-fido test this please

**Pull request merged**
