### PR TITLE
Append required FITS keywords in header

### PR DESCRIPTION
**Pull request by migueldvb**
Creating a ds9 region with `yt.frontends.fits.misc.ds9_region` produces the error below
as in the FITS radio cubes notebook in the documentation:

http://yt-project.org/docs/dev/cookbook/fits_radio_cubes.html

```
~/.local/lib64/python3.6/site-packages/astropy/io/fits/header.py in _cardindex(self, key)
   1652
   1653         if not indices:
-> 1654             raise KeyError("Keyword {!r} not found.".format(keyword))
   1655
   1656         try:
KeyError: "Keyword 'NAXIS1' not found."
```

## PR Summary

This fixes the error below when creating a ds9 region. The FITS header created by
the `astropy.wcs.WCS.to_header` only contains WCS related keywords, and the required `NAXIS` keywords have to be supplied after calling `to_header`.

In SpectralCubeFITSDataset, the coordinate description in wcs_2d can be equivalently obtained using `astropy.wcs.WCS.sub` so a few lines a are gone in `data_structures.py`.

## PR Checklist

- [ ] Code passes flake8 checker
- [ ] New features are documented, with docstrings and narrative docs
- [ ] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by jzuhone** [comment]
I'll give this a look tomorrow, but so far makes sense.

**Comment by jzuhone** [comment]
@yt-fido test this please

**Comment by jzuhone** [comment]
@migueldvb can you either merge from `master` or rebase this on the current master? I think that should fix the test failures, which are unrelated.

**Comment by migueldvb** [comment]
Sure, I will rebase and update this PR.

**Comment by matthewturk** [comment]
@yt-fido please test this

**Comment by Xarthisius** [comment]
@yt-fido test this please

**Comment by matthewturk** [comment]
@jzuhone Is this ready to merge?

**Pull request merged**
