### PR TITLE
second isort pass with isort 5.1.4

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

Companion PR to #2756 and follow up to #2749 : second pass with the latest version of isort, which fixes some bugs on their side and now seamlessly runs on Cython files

### CODE REVIEW

**Comment by neutrinoceros** [comment]
right, I should update it here too to prove it works !

**Comment by matthewturk** [comment]
I think the cimport sorting might have broken the build.  I'm going to try taking a crack at this and let you know.

**Comment by neutrinoceros** [comment]
> I think the cimport sorting might have broken the build. I'm going to try taking a crack at this and let you know.

wow, may be worth reporting to isort's author if this is indeed the case.

**Comment by matthewturk** [comment]
@neutrinoceros I suspect it's because of a sneaky transitive cimport issue -- probably not worth reporting.

**Pull request merged**
