### PR TITLE
ci: restrain build-test workflow to pull request trigger

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

This avoids having failures reported from both personal forks and the main repo.

### CODE REVIEW

**Comment by matthewturk** [comment]
Hmm, doesn't this mean that if we do a direct push it won't test it?

**Comment by neutrinoceros** [comment]
If you push against an existing PR tests will still run (just checked with the h5py workflow that relies only on the pull_request trigger)

**Comment by munkm** [comment]
I just checked the workflows documentation and it seems if the PR is "synchronized" the PR workflow will be triggered. 

However, it also seems that the gh workflows won't be triggered by forked repositories by default, and must be enabled manually by users in the actions tab of their personal fork? Were we having issues with lots of personal forks?

**Comment by neutrinoceros** [comment]
>  Were we having issues with lots of personal forks?

@munkm this may be just me but I'm used to opening PRs as soon as I publish a branch so I very frequently get double-notified when the same workflow fails on my fork _and_ here.

**Comment by munkm** [comment]
Ok so the use case that this would effect is if somebody wants to test their local branches with actions (assuming they are enabled on their fork) by pushing to their branch but they haven't opened up a PR yet.

**Comment by munkm** [comment]
I've been thinking about this more and I will say that my workflow is a bit different than yours -- I don't open a PR right away usually. In some cases we do have side projects that are large that exist on a fork until they're in a later stage (I think the dask stuff could be a good example here). I think it could be worth leaving on the push trigger for those cases?

**Comment by neutrinoceros** [comment]
Possibly, but I'd argue that this leaves no possibility for a workflow with low notification noise when a specific task is hard or complex enough that it goes through a large number of iterations where some tests are temporarily broken.

**Comment by neutrinoceros** [comment]
I take that back, I'm just now realising, as you actually hinted earlier, that I can manually turn actions off on my fork. I don't feel like this PR is necessary anymore, closing.

**Pull request closed without merging**
