### PR TITLE
TST: add CPython 3.13 to regular test matrix

### LINKED ISSUE #4931: CPython 3.13 support (tracker issue)
This issue is to plan and keep track on the effort to add support for CPython 3.13 .
See [PEP 719](https://peps.python.org/pep-0719/) for the release schedule.
At the time of opening, version `3.13.0b2` is available, and NumPy is already publishing nightly wheels for it.

Here's the chronological task list to complete before we can declare support for it.
- [x] wait for our core dependencies to publish nightly builds, or be tested
	- [x] numpy
	- [x] matplotlib https://github.com/matplotlib/matplotlib/pull/28293
      - [x] Pillow
      - [x] contourpy
	- [x] unyt https://github.com/yt-project/unyt/pull/507 (not a real requirement: unyt 3.0.3 appear to be compatible already)
	- [x] cmyt https://github.com/yt-project/cmyt/pull/178
	- [x] ewah-bool-utils https://github.com/yt-project/ewah_bool_utils/pull/108
- [x] ~~https://github.com/yt-project/yt/pull/4958~~ replaced by #5021 
- [x] pass all tests on ubuntu
- [x] test `cp313` wheels builds for all platform in CI (but don't publish them yet)
	- [x] this is helped by #4949 
	- [x] ... and #4971
	- [x] #4973
- [x] enable publication to PyPI 
	- [x] requires ABI stability, i.e., CPython 3.13.0rc1
	- [x] #4973
- [ ] #5021

Supporting the experimental free-threading (a.k.a "nogil") build is a non-goal for this issue.
Relevant PRs are to be linked in this message.

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

close #4931, and replace #4958

### CODE REVIEW

**Comment by neutrinoceros** [comment]
trying out disabling netcdf4 temporarily as an experiment to see if anything *else* is currently blocking. Will revert that commit before I undraft.

**Comment by neutrinoceros** [comment]
also disabling mpi4py since it also fails to build on Windows for some reason (it's complaining that MPI itself isn't installed, but I don't think we previously did anything special to have it available on Windows images and it compiled just fine with Python 3.12 🤷🏻‍♂️)

**Comment by neutrinoceros** [comment]
ok looks like that's everything. I want to report the build failure for mpi4py upstream because it seems unknown at the moment and I have no idea what's the actual issue. I'll try to do this tomorrow.

**Comment by neutrinoceros** [comment]
I was pleasantly surprised to discover, while trying to put a minimal reproducer to illustrate my report, that mpi4py 4.0.1 was released yesterday and appeared to fix the build issue on Windows + Python 3.13, so it should really be just down to netcdf4 now.

**Comment by neutrinoceros** [comment]
netCDF4 1.7.2 just dropped, let's try this again

**Review by chrishavlin — APPROVED** [review]

**Pull request merged**
