### PR TITLE
Mapserver improvements

### PR DESCRIPTION
**Pull request by cphyc**
## PR Summary

* Possibility to plot *any* field using different layers
* Support cmap
* Add new routes (e.g. localhost:.../temperature will plot the temperature)
* Search through the different fields

## PR Checklist

- [x] Code passes flake8 checker

## TODO
Fix `GenerationInProgress` errors. This happen e.g. with the `output_00080` dataset, when selecting the `gas density_gradient_z` field.

### CODE REVIEW

**Comment by cphyc** [comment]
Actually before merging, I'd be glad to have some feedback from some users. I know there are still some issues, e.g. I get `GenerationInProgress` errors sometimes, …

**Comment by cphyc** [comment]
@MatthewTurk any chance you give some feedback on the matter of the `GenerationInProgress` issue?

**Comment by ngoldbaum** [comment]
How are you triggering those errors? Generally that errors gets raised when the field system gets into an inconsistent state, e.g. if field detection is breaking somehow. Looking at the code changes you've made I don't see anything that would break the field system, so it's possible you're hitting an existing issue that would not normally be triggered by interactive use.

**Comment by cphyc** [comment]
Steps to reproduce the bug:
* load in some dataset, e.g. 
   `yt mapserver DICEGalaxyDisk/output_00001/info_00001.txt --host localhost:1234`
* go to `localhost:1234/density`
* now load `gas averaged_density` field

**Comment by ngoldbaum** [comment]
Ah, so this is a case where the field system is getting into an inconsistent state. As you've discovered the `averaged_density` field requires yt to generate ghost zones to evaluate the field. Ideally, for Ramses datasets where we haven't implemented the ability to generate ghost zones yet, the field detection system would be able to see that fields like `averaged_density` don't work and not include them in `ds.derived_field_list`. However, the field detection system currently assumes all frontends are able to generate ghost zones.

You're seeing `GenerationInProgress` errors because the field system is trying access a field that isn't actually available, so the field system thinks it's still in field detection, and gets into an inconsistent state.

I'm not sure offhand why accessing the field manually leads to the AttributeError you're seeing instead of `GenerationInProgress` but I don't think that's related to the mapserver in any way, it's an issue with the field system that is separate from the mapserver.

**Comment by cphyc** [comment]
@ngoldbaum Are you ok to merge this?

**Pull request merged**
