### PR TITLE
Use the underlying octree field parameters in block slices

### LINKED ISSUE #1699: Off-Axis Projections do not work on Cut Regions (in at least Ramses)
### Bug report

**Bug summary**

Off-Axis Projections work for Ramses datasets for geometric containers. However, using a cut region does not work, giving the error: 
   AttributeError: 'OctreeSubsetBlockSlicePosition' object has no attribute '_field_parameter_state'

Cut regions need to inherit from YTSelectionContainer, or field_parameter_state needs to be set up for them. 

**Code for reproduction**

This uses the output_00080 ramses cosmological data available online. 

```python
import yt
import numpy as np

num = 80
Look = [1.,1.,0]
Up = [0.,1.,1.]

c = np.array([0.5,0.5,0.5])
rad = 0.2
left  = c - rad*1.05
right = c + rad*1.05
bb = [left,right]

fn = "./output_{0:05d}/info_{0:05d}.txt"
ds = yt.load(fn.format(num),bbox=bb)

region = ds.region(c,left,right)
d30 = region.cut_region(['obj["density"] > 1e-30'])

# This works
p1 = yt.OffAxisProjectionPlot(ds,Look,"density",weight_field='density',center=c,width=2*rad,data_source=region,north_vector=Up)
p1.save("OAProjDens_Region_{0:03d}.png".format(num))

# This doesn't
p1 = yt.OffAxisProjectionPlot(ds,Look,"density",weight_field='density',center=c,width=2*rad,data_source=d30,north_vector=Up)
p1.save("OAProjDens_D30_{0:03d}.png".format(num))
```

**Actual outcome**

```
yt : [INFO     ] 2018-02-20 16:41:20,597 Parameters: current_time              = 1.11921656406
yt : [INFO     ] 2018-02-20 16:41:20,597 Parameters: domain_dimensions         = [64 64 64]
yt : [INFO     ] 2018-02-20 16:41:20,597 Parameters: domain_left_edge          = [ 0.  0.  0.]
yt : [INFO     ] 2018-02-20 16:41:20,598 Parameters: domain_right_edge         = [ 1.  1.  1.]
yt : [INFO     ] 2018-02-20 16:41:20,598 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2018-02-20 16:41:20,598 Parameters: current_redshift          = 0.142557286322
yt : [INFO     ] 2018-02-20 16:41:20,598 Parameters: omega_lambda              = 0.723999977112
yt : [INFO     ] 2018-02-20 16:41:20,598 Parameters: omega_matter              = 0.276000022888
yt : [INFO     ] 2018-02-20 16:41:20,598 Parameters: hubble_constant           = 0.703000030518
yt : [WARNING  ] 2018-02-20 16:41:20,612 Detected 2 extra particle fields assuming kind `double`. Consider using the `extra_particle_fields` keyword argument if you have unexpected behavior.
yt : [INFO     ] 2018-02-20 16:41:22,661 xlim = -0.200000 0.200000
yt : [INFO     ] 2018-02-20 16:41:22,661 ylim = -0.200000 0.200000
yt : [INFO     ] 2018-02-20 16:41:22,661 zlim = -0.500000 0.500000
yt : [INFO     ] 2018-02-20 16:41:22,670 Making a fixed resolution buffer of (('gas', 'density')) 800 by 800
/mnt/blackwhale/home/mrichard/soft/yt/yt_cphyc/yt/units/yt_array.py:1130: RuntimeWarning: invalid value encountered in divide
  np.divide(self, oth, out=self)
yt : [INFO     ] 2018-02-20 16:41:31,633 Saving plot OAProjDens_Region_080.png
yt : [INFO     ] 2018-02-20 16:41:32,467 xlim = -0.200000 0.200000
yt : [INFO     ] 2018-02-20 16:41:32,467 ylim = -0.200000 0.200000
yt : [INFO     ] 2018-02-20 16:41:32,467 zlim = -0.500000 0.500000
yt : [INFO     ] 2018-02-20 16:41:32,468 Making a fixed resolution buffer of (('gas', 'density')) 800 by 800
Traceback (most recent call last):
  File "Bug_OAProj_Container.py", line 25, in <module>
    p1 = yt.OffAxisProjectionPlot(ds,Look,"density",weight_field='density',center=c,width=2*rad,data_source=d30,north_vector=Up)
  File "/mnt/blackwhale/home/mrichard/soft/yt/yt_cphyc/yt/visualization/plot_window.py", line 1727, in __init__
    fontsize=fontsize)
  File "/mnt/blackwhale/home/mrichard/soft/yt/yt_cphyc/yt/visualization/plot_window.py", line 660, in __init__
    PlotWindow.__init__(self, *args, **kwargs)
  File "/mnt/blackwhale/home/mrichard/soft/yt/yt_cphyc/yt/visualization/plot_window.py", line 219, in __init__
    self._setup_plots()
  File "/mnt/blackwhale/home/mrichard/soft/yt/yt_cphyc/yt/visualization/plot_window.py", line 748, in _setup_plots
    self._recreate_frb()
  File "/mnt/blackwhale/home/mrichard/soft/yt/yt_cphyc/yt/visualization/plot_window.py", line 1733, in _recreate_frb
    super(OffAxisProjectionPlot, self)._recreate_frb()
  File "/mnt/blackwhale/home/mrichard/soft/yt/yt_cphyc/yt/visualization/plot_window.py", line 272, in _recreate_frb
    self._frb._get_data_source_fields()
  File "/mnt/blackwhale/home/mrichard/soft/yt/yt_cphyc/yt/visualization/fixed_resolution.py", line 155, in _get_data_source_fields
    self[f]
  File "/mnt/blackwhale/home/mrichard/soft/yt/yt_cphyc/yt/visualization/fixed_resolution.py", line 543, in __getitem__
    method=dd.method)
  File "/mnt/blackwhale/home/mrichard/soft/yt/yt_cphyc/yt/visualization/volume_rendering/off_axis_projection.py", line 189, in off_axis_projection
    for i, (grid, mask) in enumerate(data_source.blocks):
  File "/mnt/blackwhale/home/mrichard/soft/yt/yt_cphyc/yt/data_objects/selection_data_containers.py", line 836, in blocks
    with obj._field_parameter_state(self.field_parameters):
AttributeError: 'OctreeSubsetBlockSlicePosition' object has no attribute '_field_parameter_state'
```

**Expected outcome**

There should be two output png files generated. Currently only one is generated. The second would cut out all material more diffuse than 1e-30 g/cm^3

**Version Information**

  * Operating System: CentOS
  * Python Version: 2.7.13
  * yt version: 3.5.dev0
  * Other Libraries (if applicable): 

yt was installed with conda from source.

### PR DESCRIPTION
**Pull request by MatthewTurk**
This fixes #1699.  The way it does so is by dispatching the field
parameter state to the underlying object (octree subset) in the octree
block slice position object.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
@git-abhishek recently added `fake_octree_ds` which might be helpful here.

**Comment by cphyc** [comment]
```
ds = yt.testing.fake_octree_ds() 
cut = ds.all_data().cut_region('obj["density"]>0.5') 
p = yt.OffAxisProjectionPlot(ds, [1, 0, 0], 'density', data_source=cut)
p = yt.OffAxisSlicePlot(ds, [1, 0, 0], 'density', data_source=cut)
```
works with your version!

**Comment by MatthewTurk** [comment]
Ok, added some tests!

**Comment by ngoldbaum** [comment]
Looks like this causes one unit test to fail:

```
ERROR: yt.visualization.tests.test_offaxisprojection.test_field_cut_off_axis_octree
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/yt-project/yt/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/yt-project/yt/yt/visualization/tests/test_offaxisprojection.py", line 89, in test_field_cut_off_axis_octree
    p1 = OffAxisProjectionPlot(ds, [1, 0, 0], 'density')
  File "/home/travis/build/yt-project/yt/yt/visualization/plot_window.py", line 1723, in __init__
    data_source=data_source)
  File "/home/travis/build/yt-project/yt/yt/visualization/plot_window.py", line 1596, in __init__
    fields = self.dd._determine_fields(fields)
  File "/home/travis/build/yt-project/yt/yt/data_objects/data_containers.py", line 1153, in _determine_fields
    finfo = self.ds._get_field_info("unknown", fname)
  File "/home/travis/build/yt-project/yt/yt/data_objects/static_output.py", line 731, in _get_field_info
    self.index
  File "/home/travis/build/yt-project/yt/yt/data_objects/static_output.py", line 506, in index
    self, dataset_type=self.dataset_type)
  File "/home/travis/build/yt-project/yt/yt/frontends/stream/data_structures.py", line 1487, in __init__
    super(StreamOctreeHandler, self).__init__(ds, dataset_type)
  File "/home/travis/build/yt-project/yt/yt/geometry/geometry_handler.py", line 50, in __init__
    self._setup_geometry()
  File "/home/travis/build/yt-project/yt/yt/geometry/oct_geometry_handler.py", line 25, in _setup_geometry
    self._initialize_oct_handler()
  File "/home/travis/build/yt-project/yt/yt/frontends/stream/data_structures.py", line 1502, in _initialize_oct_handler
    self.oct_handler = OctreeContainer.load_octree(header)
  File "yt/geometry/oct_container.pyx", line 135, in yt.geometry.oct_container.OctreeContainer.load_octree (yt/geometry/oct_container.c:4768)
    raise KeyError(ref_mask.size, obj.nocts, obj.oref,
KeyError: (329, 73, 1, 1)
```

**Comment by MatthewTurk** [comment]
Whoa, that is really weird.  It's not like I just added it and didn't run it before testing!  :cold_sweat: Let's take another pass...

**Comment by MatthewTurk** [comment]
Yup, so I must be doing something differently than I should.  I'm on 7f9e9047c19328733a164055f56c7d4a6231f02b and I can run the test just fine:

```
nosetests yt/visualization/tests/test_offaxisprojection.py
```

Do the tests get run on a merged version?

**Comment by ngoldbaum** [comment]
Yes they do. Can you try rebasing on or merging with master?

**Comment by MatthewTurk** [comment]
OK, I have run on the current changeset, and it works on my machine.

**Comment by cphyc** [comment]
@yt-fido test this please

**Pull request merged**
