### PR TITLE
[WIP] [RAMSES] Feature/rt support

### PR DESCRIPTION
**Pull request by cphyc**
This PR adds support for radiative transfer in RAMSES.

## PR Summary

RT in RAMSES is writting into files like `rt_XXXX.outYYYY`. This PR reads them all, autodiscovering the number of groups and tracers there. It also parses the `info_rt.outYYYY` file to get the conversion factors from code unit to physical units.

## PR Checklist

- [x] Code passes flake8 checker
- [x] New features are documented, with docstrings and narrative docs
- [x] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Fully parse and load the `info_rt_YYYYY.txt` file.
- [ ] Write an answer test?
- [x] Add a new dataset for testing purposes
- [ ] Rebase from master

### CODE REVIEW

**Comment by ngoldbaum** [comment]
It looks like this is done on top of #1548, so let's hold off on merging this until #1548 is merged.

**Comment by cphyc** [comment]
I can also rebase onto master the current by cherry-picking?

**Comment by ngoldbaum** [comment]
Sure, if you don't mind dealing with the merge conflicts.

**Comment by cphyc** [comment]
it's actually quite a pain to rebase onto master (mostly because then I'll have to rebase it once again once #1548 is accepted) so I'm leaving it for now.

**Comment by ngoldbaum** [comment]
@cphyc now that #1548 is merged feel free to come back and rebase this.

**Comment by cphyc** [comment]
Hi! I haven't updated this PR in a long time. Anyway, I was working on a refactoring of the particle + field files in RAMSES that would make this PR much simpler and more generic. I'll update it once it's done.

**Pull request closed without merging**
