### PR TITLE
[bugfix] Alternate fix for PR #1912

### PR DESCRIPTION
**Pull request by brittonsmith**
This is an alternative implementation of the bugfix PR #1912.

After @MatthewTurk's comment, I've implemented a fix that does not remove grids where the `filename` is None and instead allows them to be sorted and potentially operated on. This may be safer than what I did in PR #1912. Only one of these two should be accepted.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
I have no idea why this impacts `test_axial_pixelization`, although I could see why it happens since that test use `fake_amr_ds` under the hood.

The travis failures are unrelated, I suspect we have a memory leak somewhere.

**Comment by brittonsmith** [comment]
Ok thanks for clarifying that. I'll look into `test_axial_pixelization` and see if there's something to it.

**Comment by brittonsmith** [comment]
The failures in `test_axial_pixelization` were due to the change from sorting by `grid.id` to `str(grid.id)`, which changed the grid order set in `_identify_base_chunk`. Not sure why the order should matter for those tests, but it definitely did.

**Comment by ngoldbaum** [comment]
The python3 test failures can be ignored.

Nice job Britton! Thanks for pushing on this.

**Pull request merged**
