### PR TITLE
TST: migrate image comparison tests from nose to pytest-mpl (⏰ wait on #4122)

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary
Partially addresses #4102
 
This is far from done, but I need early iterations with CI to see what problems I encounter.
Right now I'm only aiming at image tests being skipped on nose

approach:
the main difficulty is that our `yield` base image tests are built via loops, while `pytest-mpl` relies on return values of test functions. When `pytest.mark.parametrize` is appropriate, this can be a one-to-one translation, but otherwise I rely on generated code to reproduce existing test (by which I mean that I write many alike plain test functions, just not purely by hand).

TODO:
- [ ] stop using image answer tests (replace them with pytest-mpl)
  - [x] `GenericImageTest`
  - [x] `VRImageComparisonTest`
  - [x] `PhasePlotAttributeTest`
  - [x] `PixelizedParticleProjectionValuesTest`
  - [ ] `PixelizedProjectionValuesTest`
  - [ ] `PlotWindowAttributeTest`
- [ ] create image baseline folder (should probably be a submodule, not sure if a new one is warranted, or if we should just reuse answer-store)
- [ ] add image image comparison-only test job
- [ ] cleanup `tests/report_failed_answers.py`
- [ ] cleanup uses of `filename=...` in mpl_image_compar markers
- [ ] consider refactoring again with `pytest.mark.parametrize`

opened questions:
- How can we handle "big data" image tests, and more generally image tests that use real (large) data ? Currently these tests are run on Jenkins + nose

### CODE REVIEW

**Comment by neutrinoceros** [comment]
I was not originally planning to fully replace the "answer tests" job on GHA but I see that after removing all image tests from it, it now runs only a very small set of tests and takes about 20s to run (and 10min to build), so I think I should just clear that out completely and replace the job with a new one 1000% focused on image-comparison tests.

**Comment by neutrinoceros** [comment]
I think I should split this in two parts and separate tests that require real data (running on Jenkins) from the rest (running on GH)

**Comment by neutrinoceros** [comment]
This is probably beyond saving at this point. In any case, #4122 has most of this work in a mergeable state, so I think I should just close this one.

**Comment by matthewturk** [comment]
Can you describe the difference with #4122?

**Pull request closed without merging**
