### PR TITLE
MNT: revert a patch that was written in support to a now unsupported use case

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary
revert 2ffd0a246c83dd846f988eefbeb38e37d18c0f24
for context, this patch was intended to answer https://github.com/yt-project/yt/issues/1053
but the example given in the issue is currently invalid and fails with
```python-traceback
TypeError: Expected a 2-tuple of strings formatted as
(field or particle type, field name)
Received invalid field key: dust_density, with type <class 'str'>
```
This failure is intentional and aligns with the overarching goal of dropping support for single-string field ids in yt 4.1

I hope reverting the patch doesn't break anything else, but the intended use case has clearly not been tested continuously for a while.
edit: looks like not !

### CODE REVIEW

**Comment by neutrinoceros** [comment]
While I'm at it let's also simplify all 4 occurrences of `list(sorted())` found in the code base.
`sorted` in fact already returns a list regardless of the input type.
```python
>>> sorted((1, 2, 0))
[0, 1, 2]
```

**Comment by neutrinoceros** [comment]
this is actually low priority, no need to have it in the milestone

**Comment by neutrinoceros** [comment]
closing/reopening t refresh CI and test if #3923 has any unforseen side effect on a new PR.

**Comment by neutrinoceros** [comment]
That's a fair question. Let me give a little more insight on this

Only user provided field keys can be ambiguous. yt used to accept single-str field keys (potentially ambiguous) in a field definition, but yt 4.0 doesn't: user-defined field keys _have_ to be `tuple[str, str]`s.

`FieldInfoContainer.find_dependencies` is called internally at definition/setup time, but only after type validation happens, so it's now safe to assume that it only sees tuple field keys.

Seeing that this patch hasn't caused any failure in tests, I'm rather confident that nothing in yt was actually relying on the patch I'm reverting.

**Review by brittonsmith — APPROVED** [review]

**Comment by neutrinoceros** [comment]
@matthewturk can this be merged ?

**Pull request merged**
