### PR TITLE
Reverse angular momentum orientation

### LINKED ISSUE #2042: Angular momentum orientation
I'm confused by the current definition of specific angular momentum as [`-ucross(r_vec, v_vec)`](https://github.com/yt-project/yt/blob/4ca693aed0ce6c3ef791be44ec8a6fe6743c82c4/yt/fields/particle_fields.py#L306). Why isn't it `ucross(r_vec, v_vec)` instead, which should be the standard definition?

I digged into the history and found the definition introduced in this [PR](https://bitbucket.org/yt_analysis/yt/pull-requests/1585). The situation was a little bit complicated, and there was actually a [conversation](https://bitbucket.org/yt_analysis/yt/pull-requests/1585/bugfix-improvement-specific-angular/activity#LC7248981T310) specifically about the angular momentum orientation.

The situation was that the definition of the angular momentum vector and those of the components were opposite. The vector was defined as [`np.cross(r_vec, v_vec)`](https://bitbucket.org/yt_analysis/yt/pull-requests/1585/bugfix-improvement-specific-angular/diff#Lyt/fields/particle_fields.pyF285), while the x component was defined as [`yv*z - zv*y`](https://bitbucket.org/yt_analysis/yt/pull-requests/1585/bugfix-improvement-specific-angular/diff#Lyt/fields/particle_fields.pyF302) (similarly for other components), corresponding to `-np.cross(r_vec, v_vec)`. Eventually the decision was made to use the latter convention.

But I'm not convinced this is a proper convention. Could we reconsider this? @cosmosquark @MatthewTurk @ngoldbaum was in the previous conversation and might have more to say.

### PR DESCRIPTION
**Pull request by qobilidop**
## PR Summary

Resolves #2042.

## PR Checklist

- [x] Code passes flake8 checker

### CODE REVIEW

**Comment by ngoldbaum** [comment]
I think this would be too much of a disruptive change for 3.5, so let's hold off on merging this until after 3.5 gets released.

**Comment by cphyc** [comment]
@yt-fido test this please

**Comment by cphyc** [comment]
To be fully consistent, one would need to also flip the axes for the gas angular momentum (as defined in `yt/fields/angular_momentum.py`).

**Comment by qobilidop** [comment]
@cphyc Thanks for spotting this! I've made a patch.

**Comment by ngoldbaum** [comment]
@qobilidop looks like a conflict has creeped in. Can you merge or rebase to clear it?

Also it's awesome that the tests pass!

**Comment by qobilidop** [comment]
@ngoldbaum It's now resolved! Sorry for not noticing this earlier.

**Comment by ngoldbaum** [comment]
Heh, this broke the test that @cphyc just added that tests the angular momentum value of a real dataset. Needs a minus sign ;)

**Comment by qobilidop** [comment]
That's expected, right? It's great now this change is caught in tests. Thanks, @cphyc! I guess there needs to be further discussion back in #2042 then.

**Comment by ngoldbaum** [comment]
That's expected given the change in this PR. I'd just add the minus sign to the broken test. That test was added in between the time when this PR was originally opened and now.

**Comment by qobilidop** [comment]
I see. Thanks for the clarification.

**Comment by ngoldbaum** [comment]
OK, I think this is ready to merge. I'm going to send an e-mail to yt-dev about it first though because I feel like this one might be more disruptive than usual.

**Comment by qobilidop** [comment]
I totally agree. A wider awareness and discussion is necessary.

**Comment by ngoldbaum** [comment]
Just because the tests haven't run on this in a while I'm going to close and reopen it to retrigger them. Assuming the tests pass I agree that we should merge this.

**Comment by ngoldbaum** [comment]
The test failures on python3 are due to #1702 and can be ignored. Merging.

**Pull request merged**
