### PR TITLE
Drop CodeTour GHA

### PR DESCRIPTION
**Pull request by matthewturk**
Let's see if we can iterate this to working.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
@matthewturk you'll need to re-enable the workflow here https://github.com/yt-project/yt/actions/workflows/codetour-check.yaml

**Comment by neutrinoceros** [comment]
now that it's enabled, I'll close/reopen to trigger it

**Review by neutrinoceros — APPROVED** [review]
Seems that it did the trick, thank you !

**Comment by Xarthisius** [comment]
> Seems that it did the trick, thank you !

That's tbd. What you need is a PR that changes something that would trigger this test to fail. Only then it tries to comment on an issue and AFAIU insufficient perms on the token were the cause...

**Comment by matthewturk** [comment]
OK, I guess we need a custom purpose token?

**Comment by Xarthisius** [comment]
> OK, I guess we need a custom purpose token?

We have that. I just regenerated it (although that was pointless). It has proper scopes (repo), it belongs to yt-fido and you can verify the fact that this token can be used to modify issues/code by the fact that jenkins jobs appear in here...

I don't know what kind of scopes codetour plugin needs.

**Comment by matthewturk** [comment]
https://github.com/marketplace/actions/codetour-watch this says just comment.  UGH!

**Comment by Xarthisius** [comment]
I give up...

**Comment by neutrinoceros** [comment]
Should we remove `.tours` too ?

**Comment by matthewturk** [comment]
I think we should leave them, and for now allow them to slowly become out of date or manually verified.

**Review by neutrinoceros — APPROVED** [review]

**Comment by neutrinoceros** [comment]
@yt-fido test this please

**Comment by neutrinoceros** [comment]
I don't understand what's happening at the moment but it seems I cannot merge.

Screenshot 2023-01-27 at 11 54 57


I'll try one last close/reopen.

**Comment by neutrinoceros** [comment]
I see the py38 job was correctly launched on Jenkins, but Github doesn't seem to see it. No idea what's broken or how to fix it.

**Comment by Xarthisius** [comment]
@yt-fido test this please

**Comment by Xarthisius** [comment]
@yt-fido test this please

**Comment by yt-fido** [comment]
test connection from jenkins

**Pull request merged**
