### PR TITLE
[WIP] Plot window answer tests visualization.test_plotwindow.py

### PR DESCRIPTION
**Pull request by git-abhishek**
## PR Summary

Update test cases in `test_plotwindow.py`

Convert unit tests to answer tests
Remove test from Jenkins as answer test

Note: This branch is rebased from PR  #1955 as `yt.visualization.tests.test_plotwindow.TEST_FLNMS `  is 
imported in `yt/visualization/tests/test_profile_plots.py`.

## PR Checklist

- [X] Code passes flake8 checker

## Adding Reviewers
@ngoldbaum @Xarthisius @colinmarc

### CODE REVIEW

**Comment by ngoldbaum** [comment]
@git-abhishek looks like the jenkins tests are failing now. Missed something in tests.yaml?

**Comment by git-abhishek** [comment]
@ngoldbaum This was getting messy, due to rebase from other branch. I will update this, once the dependent PR gets merge.

**Comment by ngoldbaum** [comment]
Ah missed that :)

**Comment by matthewturk** [comment]
@git-abhishek Thanks for this -- we discussed and think that right now we're going to move in a different direction, but we appreciate the work you and @ngoldbaum put into this.

**Pull request closed without merging**
