### PR TITLE
cleanup: remove a class that was only used in python 2

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary
Unless I'm misreading its docstring, this class isn't required anymore.

### CODE REVIEW

**Comment by matthewturk** [comment]
We may also no longer need `poster` either.

**Comment by neutrinoceros** [comment]
I'm fine with removing the whole module. Should I ?

**Comment by neutrinoceros** [comment]
switching to draft, I'll try removing the whole module later and see what happens.

**Comment by neutrinoceros** [comment]
This is superseded by #2783

**Pull request closed without merging**
