### PR TITLE
exp: remove unused module pmods

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

I believe this is an unused external module who survived the removal of yt/externs

### CODE REVIEW

**Comment by matthewturk** [comment]
Hmm, let's discuss this one. I think it may still be used by user-written
scripts.

**Comment by neutrinoceros** [comment]
sure !

**Comment by neutrinoceros** [comment]
note: this module depends on `imp`, which is a deprecated module from the standard lib (https://docs.python.org/3/library/imp.html), so if we want to keep it, it will be necessary to update it at least for this reason.

**Comment by neutrinoceros** [comment]
Coincidently, it appears that the corresponding documentation is not included in the docs build, see https://github.com/yt-project/yt/issues/3029
@matthewturk , how likely is it that anyone is still using it ?

**Comment by matthewturk** [comment]
I am growing skeptical that it is used.  And, more convincingly (to myself), I'm starting to think including it is the wrong approach.  I think we should remove it for 4.0.  Can you notify yt-dev?  I will chime in with my supporting reasons.

**Comment by neutrinoceros** [comment]
>  Can you notify yt-dev?

done !

**Comment by chummels** [comment]
I thought I used to use this in my parallel computation scripts, but I guess maybe I'm mistaken and I just used `piter()`?  Come to think of it, I don't remember exactly what `pmods` did and looking at the source isn't seeming to help. :)

**Comment by matthewturk** [comment]
You probably did use it -- it *used* to manage the import process to try to
alleviate the strain of many-nodes-importing-at-once.

**Pull request merged**
