### PR TITLE
Add imposter syndrome disclaimer to readme

### PR DESCRIPTION
**Pull request by ngoldbaum**
This was shamelessly stolen from the [metpy readme](https://github.com/Unidata/MetPy). I really like the gist of it and think it would be a good addition for our readme as well.

### CODE REVIEW

**Comment by MatthewTurk** [comment]
Can you note in the disclaimer itself that this comes from metpy?

**Comment by adriennefriend** [comment]
Just a heads-up, so glad metpy is using it! Much of the text was written by me and was adapted. Thanks for the credit and for sharing the support and spirit of welcome! Cheers.

**Comment by zingale** [comment]
this is a very nice addition

**Comment by MatthewTurk** [comment]
@adriennefriend Thank you for writing it, and also for stepping in to note that you wrote it so that it gets appropriate citation!  It's a really great statement.

**Comment by adriennefriend** [comment]
Thanks so much y'all! Love what you're doing and how you're being so welcoming. 🐍💚

**Pull request merged**
