### PR TITLE
BLD: require Cython 3.0.3 to fix known issues on CPython 3.12

### LINKED ISSUE #4675: BLD: (yt 4.3) cp312 wheels require Cython 3.0.3
### Context
https://github.com/cython/cython/issues/5724
https://github.com/cython/cython/pull/5725

In short: binaries built with Cython 3.0.2 + Python 3.12 cause a memory leak, so we'd better wait for Cython 3.0.3 to be released so we can bump our requirements, before publishing cp312 wheels.
I'll consider this a release blocker for yt 4.3.0

### PR DESCRIPTION
**Pull request by neutrinoceros**
close #4675

### CODE REVIEW

**Review by chrishavlin — APPROVED** [review]
Looks good to me.

Since this PR also introduces a minimal unit test with 3.12, it might be useful to add a new issue just to track the progress of moving to full testing with 3.12 (if there's not already one that I've missed). What do you think?

**Comment by neutrinoceros** [comment]
I think this could be useful, though we're almost there already, and it looks like our optional dependencies are moving much faster than in recent years, so I'm actually hopeful that we can just finish it in a couple days.

**Comment by neutrinoceros** [comment]
@chrishavlin I've opened #4689 and linked to it here

**Review by cphyc — APPROVED** [review]
Also LGTM! I'd be happy once we fix future incompatibilities with Cython 3.1 though :)

**Comment by neutrinoceros** [comment]
it might actually be a no-op, depending on how https://github.com/cython/cython/issues/4310 turns out

**Pull request merged**
