### PR TITLE
[BUGFIX] Correct typo in WarpX field definitions.

### PR DESCRIPTION
**Pull request by atmyers**
## PR Checklist

- [ ] Code passes flake8 checker
- [ ] New features are documented, with docstrings and narrative docs
- [ ] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Good catch! Unfortunately fido is down right now so I'd prefer to wait until after it comes back up to make sure merging this doesn't break any of the `WarpX` answer tests. @Xarthisius do you happen to know if there's an estimate for when Nebula will be back up?

**Comment by ngoldbaum** [comment]
It occurs to me that it wouldn't be a bad idea to check for repeated entries in `known_other_fields` and `known_particle_fields` when we instantiate `FieldInfoContainer` subclasses. Just a thought, not necessary to think about in this PR.

**Comment by Xarthisius** [comment]
>  @Xarthisius do you happen to know if there's an estimate for when Nebula will be back up?

Hopefully tomorrow.

**Comment by ngoldbaum** [comment]
@atmyers it's the plotwindow answer tests, not the boxlib ones that failed.

**Pull request merged**
