### PR TITLE
BUG: fix an edge case in enzo frontend where dark matter-only dataset would fail to load

### LINKED ISSUE #3809: Commit a8b395e prevents dark matter-only Enzo simulations from being analyzed
### Bug report

**Bug summary**

As of commit a8b395e1833381d1647d1b91c7ecda99a09ec75b, yt appears to fail with dark matter-only Enzo simulations as soon as frontends.enzo.fields.setup_energy_field() is called (e.g., via ds.all_data() or ds.add_particle_filter()). These simulations do not have an explicit energy field, so an error is triggered at [line 278 of frontends/enzo/fields.py](https://github.com/yt-project/yt/blob/main/yt/frontends/enzo/fields.py#L278), since ('enzo', None) is not a valid field name.

**Code for reproduction**

```python
import yt
ds = yt.load('DD0064/DD0064')
ads = ds.all_data()
```
Sample dataset that generates error at: http://use.yt/upload/35be3369

**Actual outcome**

```
Traceback (most recent call last):
  File "Research/Outputs/TestSphere.py", line 15, in <module>
    ads = ds.all_data()
  File "/Users/anna/yt/yt/data_objects/static_output.py", line 1052, in all_data
    self.index
  File "/Users/anna/yt/yt/data_objects/static_output.py", line 546, in index
    self.create_field_info()
  File "/Users/anna/yt/yt/data_objects/static_output.py", line 592, in create_field_info
    self.field_info.setup_fluid_fields()
  File "/Users/anna/yt/yt/frontends/enzo/fields.py", line 189, in setup_fluid_fields
    self.setup_energy_field()
  File "/Users/anna/yt/yt/frontends/enzo/fields.py", line 280, in setup_energy_field
    ("enzo", te_name), sampling_type="cell", units="code_velocity**2"
  File "/Users/anna/yt/yt/fields/field_info_container.py", line 425, in add_output_field
    self[name] = DerivedField(name, sampling_type, NullFunc, **kwargs)
  File "/Users/anna/yt/yt/fields/derived_field.py", line 134, in __init__
    validate_field_key(name)
  File "/Users/anna/yt/yt/funcs.py", line 1206, in validate_field_key
    "Expected a 2-tuple of strings formatted as\n"
TypeError: Expected a 2-tuple of strings formatted as
(field or particle type, field name)
Received invalid field key: ('enzo', None), with type <class 'tuple'>
```

**Expected outcome**

This shouldn't usually produce any output. As far as I can tell, it works on commits prior to a8b395e1833381d1647d1b91c7ecda99a09ec75b

**Version Information**

  * Operating System: macOS 10.15.7
  * Python Version: 3.7.7
  * yt version: 4.1.dev0
  * Other Libraries (if applicable): N/A

yt installed from source

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary
fix #3809

### CODE REVIEW

**Review by matthewturk — COMMENTED** [review]
I think this looks good to me, but getting @anchwr to verify would be great.

**Comment by neutrinoceros** [comment]
Sure. For the record I've used the embedded dataset locally for validation. The report was really useful !

**Comment by anchwr** [comment]
That works perfectly for me. Thank you so much!

**Review by jzuhone — APPROVED** [review]

**Comment by neutrinoceros** [comment]
Any reason not to merge yet ?

**Pull request merged**
