### PR TITLE
[BUGFIX] Art: fix dm_only frontend

### PR DESCRIPTION
**Pull request by cphyc**
## PR Summary

Removes tests that are intended for particle datasets. They were incorrectly run on ART, an octree dataset.

### CODE REVIEW

**Comment by matthewturk** [comment]
Looks good to me.  I think @munkm pointed out somewhere that there's a *different* DM-only ART sim we could test.

**Comment by munkm** [comment]
Yes I did in the slack. i'll update the test. It's the `DMonly` dataset.

**Comment by Xarthisius** [comment]
Looks like `DMonly` dataset is not recognized as a valid ART file

**Comment by cphyc** [comment]
Note: cbd1a68 and b5cfe9f are merely an attempt at making things work ; I am not entirely sure about them, so please feel free to overwrite them.

**Comment by Xarthisius** [comment]
I had to kill the test run. It was stuck in some sort of an infinite loop and consuming 108GB of RAM...
Strace showed only this:

```
openat(AT_FDCWD, "/mnt/yt/DMonly/PMcrs0.0100.DAT", O_RDONLY|O_CLOEXEC) = 15
fstat(15, {st_mode=S_IFREG|0664, st_size=402653184, ...}) = 0
ioctl(15, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, 0x7ffd320aaf50) = -1 ENOTTY (Inappropriate ioctl for device)
lseek(15, 0, SEEK_CUR)                  = 0
lseek(15, 0, SEEK_END)                  = 402653184
lseek(15, 0, SEEK_CUR)                  = 402653184
close(15)
```

**Comment by cphyc** [comment]
Oh well, I think I accidentally made it work.

> I had to kill the test run. It was stuck in some sort of an infinite loop and consuming 108GB of RAM...
> Strace showed only this:
> 
> ```
> openat(AT_FDCWD, "/mnt/yt/DMonly/PMcrs0.0100.DAT", O_RDONLY|O_CLOEXEC) = 15
> fstat(15, {st_mode=S_IFREG|0664, st_size=402653184, ...}) = 0
> ioctl(15, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, 0x7ffd320aaf50) = -1 ENOTTY (Inappropriate ioctl for device)
> lseek(15, 0, SEEK_CUR)                  = 0
> lseek(15, 0, SEEK_END)                  = 402653184
> lseek(15, 0, SEEK_CUR)                  = 402653184
> close(15)
> ```

The tests should now pass, but if anyone has some experience with ART datasets, that would be valuable as I am unsure about the correctness of my fixes.

**Comment by cphyc** [comment]
@yt-fido test this please

**Comment by matthewturk** [comment]
So I think this is part of a bigger problem, which is that not all of the frontends have had their `range` arguments implemented.  But as long as this works, it's fine.  In #2658 I tried to make this more formal, by making it obvious, but that one's not yet in.

**Comment by cphyc** [comment]
Agreed. But even with #2658 in, we'd still have the problem that particle frontends with no implementation of chunking will fail, even with CHUNKSIZE=∞

**Comment by matthewturk** [comment]
Good point.

All this kind of makes me hope we can figure out a better chunking solution
soon.

**Pull request merged**
