### PR TITLE
[WIP] Pytest2

### PR DESCRIPTION
**Pull request by jcoughlin11**
## PR Checklist

- [ ] Code passes flake8 checker
- [ ] New features are documented, with docstrings and narrative docs
- [ ] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by matthewturk** [comment]
Not to be merged -- just a reference point.

**Comment by munkm** [comment]
I'm not sure if we want to keep this open as a testing reference?

**Comment by matthewturk** [comment]
@jcoughlin11 should we close this in favor of #2817 ?

**Comment by matthewturk** [comment]
@jcoughlin11 let me know that this can be closed.

**Pull request closed without merging**
