### PR TITLE
Documentation for walk_volume

### PR DESCRIPTION
**Pull request by cgyurgyik**
Documentation for yt's grid traversal function walk_volume.

## PR Summary

This ensures future maintainers and users are provided a basic understanding of walk_volume. Since it is such a large function, future steps may incorporate breaking the function up into two pieces, initialization and traversal.

## PR Checklist

- [x] Code passes flake8 checker
- [x] New features are documented, with docstrings and narrative docs
- [x] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
I don't have a string opinion about this but I think it would be slightly more idiomatic to include add this documentation as a docstring on `walk_volume` rather than as a comment as you have it now.

ping @matthewturk who originally wrote this code and would hopefully be able to check the content of the new docstring.

**Comment by matthewturk** [comment]
Content looks good, and I'm not sure a docstring makes much of a difference since it's on a `cdef` function without a python frontend.  LGTM!

**Comment by cgyurgyik** [comment]
Getting the following error from AppVeyor, though my code only has documentation:
```
GenericImage_UniformGridData_all_profile_dict_keys([('gas', 'cell_mass')])_18_None_None ... ok
GenericImage_UniformGridData_all_profile_odict_keys([('gas', 'density'), ('gas', 'dark_matter_density')])_None_None ... ok
yt.visualization.tests.test_profile_plots.test_set_units ... ok
yt.visualization.tests.test_profile_plots.test_set_labels ... ok
yt.visualization.tests.test_profile_plots.test_create_from_dataset ... ok
yt.visualization.tests.test_profile_plots.test_phaseplot_set_log ... ok
yt.visualization.tests.test_profile_plots.test_phaseplot_showhide_colorbar_axes ... ok
Tests functionality of off_axis_projection and write_projection. ... ok
create a toy dataset that puts a sphere at (0,0,0), a single cube ... ok
yt.tests.test_funcs.test_validate_axis ... ok
yt.tests.test_funcs.test_validate_center ... ok
yt.tests.test_testing.test_requires_backend ... ok
======================================================================
ERROR: yt.units.tests.test_ytarray.test_ufuncs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda36-x64\envs\test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\projects\yt\yt\units\tests\test_ytarray.py", line 878, in test_ufuncs
    unary_ufunc_comparison(ufunc, YTArray([.3, .4, .5], 'cm'))
  File "C:\projects\yt\yt\units\tests\test_ytarray.py", line 809, in unary_ufunc_comparison
    ret1, ret2 = ufunc(a)
  File "C:\projects\yt\yt\units\yt_array.py", line 1378, in __array_ufunc__
    out_arr = func(np.asarray(inp), out=out, **kwargs)
TypeError: 'out' must be a tuple of arrays
======================================================================
ERROR: test_make_colormap (yt.visualization.tests.test_color_maps.TestColorMaps)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda36-x64\envs\test\lib\site-packages\numpy\core\function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\projects\yt\yt\visualization\tests\test_color_maps.py", line 50, in test_make_colormap
    name='french_flag', interpolate=False)
  File "C:\projects\yt\yt\visualization\color_maps.py", line 554, in make_colormap
    np.linspace(color[j], next_color[j], interval)
  File "<__array_function__ internals>", line 6, in linspace
  File "C:\Miniconda36-x64\envs\test\lib\site-packages\numpy\core\function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
----------------------------------------------------------------------
Ran 1430 tests in 1462.656s
FAILED (errors=2)
Command exited with code 1
```

**Comment by munkm** [comment]
Those are unrelated to your PR! They should be fixed in yt-project/yt#2448.

**Comment by munkm** [comment]
Ok, that PR has been merged now. Would you mind merging master into your development branch just so we can check that everything passes? 

Thanks so much for your work in this PR!

**Comment by ngoldbaum** [comment]
I think we can just merge this? I don't really think we need to rerun the tests since we know that the failure is unrelated to this PR. Is that OK @munkm?

**Comment by munkm** [comment]
yep! Sounds good to me.

**Pull request merged**
