### PR TITLE
BUG: avoid using deprecated matplotlib.cm API in volume rendering (round 2)

### LINKED ISSUE #4088: BUG: pending deprecation warnings from MPL 3.6
### Bug report

**Bug summary**

Matplotlib's colormap API is still evolving and new pending deprecation warnings are now emitted, which breaks yt's bleeding edge CI

example failed job: https://github.com/yt-project/yt/runs/7929987453?check_suite_focus=true
origin of the change: https://github.com/matplotlib/matplotlib/pull/23668

I note that `cmyt` is unaffected by these new warnings.

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary
Fix #4088 again

### CODE REVIEW

**Review by brittonsmith — APPROVED** [review]
Looks ok to me. Does the import need to happen inside the property?

**Comment by neutrinoceros** [comment]
It doesn't. The reason I put it there is to make extra sure no one ever relies on being able to import it as
```python
from yt.visualization._handlers import _get_cmap
```
but there are already 2 `_*` prefixes objects along the way so it should be pretty obvious already that it's not a good idea.

I can put the import at the top level if you have a preference.

**Comment by brittonsmith** [comment]
I suppose I'm in favor of moving the import up top, but only mildly. The underscores should be enough to deter importing, and it cuts down on a duplicate line of code.

**Comment by neutrinoceros** [comment]
Done !

**Review by brittonsmith — APPROVED** [review]

**Pull request merged**
