### PR TITLE
[bugfix] Check for units before converting quantities in HaloCatalog

### PR DESCRIPTION
**Pull request by brittonsmith**
This fixes a bug where halo quantities returned without units will fail because of a forced unit conversion when compiling results.  I also added a test for this.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
LGTM

**Comment by Xarthisius** [comment]
@yt-fido test this please

**Comment by brittonsmith** [comment]
Interesting that this broke in py2 and not 3.  I will take a closer look.

**Comment by ngoldbaum** [comment]
Oops, looks like this got messed up. Can you rebase? Let me know if you need a hand rewriting history.

**Comment by brittonsmith** [comment]
@yt-fido test this please

**Pull request merged**
