### PR TITLE
[yt-4.0] bugfix to ensure sph normalization, gather and neighbors are applied

### PR DESCRIPTION
**Pull request by AshKelly**
## PR Summary

bugfix to ensure sph normalization, gather and neighbors are applied

## PR Checklist

- [x] Code passes flake8 checker
- *NA* New features are documented, with docstrings and narrative docs
- [ ] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by matthewturk** [comment]
@AshKelly It looks to me like the results to

 * `yt.data_objects.tests.test_sph_data_objects.test_arbitrary_grid`
 * `yt.data_objects.tests.test_sph_data_objects.test_compare_arbitrary_grid_slice`

changed.  Are you able to run `nose -c nose_answer.cfg` locally and verify that your new answers are improvements?

**Comment by AshKelly** [comment]
Yes - we discovered this bug goes deeper.

In frontends that inherit from the SPH frontend the correct answer is with '_' but for datasets that don't inherit from there, the answer should no have '_'.

I think the solution is to remove '_' in the SPH frontend and then things should work properly

**Comment by matthewturk** [comment]
@AshKelly It strikes me that this is one very good reason to move forward with things like #2556 !  :)

**Comment by AshKelly** [comment]
It was the introduction of the getters/setters which into the `SPHFrontend` and subsequent change of name for the attributes to include an `_` at the front.

For now - I think the easiest solution is what I pushed. Remove the setters/getters and then every dataset/container can just use `<>.use_use_sph_normalization` etc. But, I guess #2556 could solve this better later on!

**Comment by AshKelly** [comment]
I should add that Robin Kooistra found this bug!

**Comment by AshKelly** [comment]
I need to check `yt.data_objects.tests.test_sph_data_objects.test_arbitrary_grid` tests. I *think* this is because the change in `_sph_types` means they are no longer being smoothed.

**Comment by matthewturk** [comment]
@AshKelly Can we help get this over the finish line?  Do you want a hand with fixing the conflicts?

**Comment by munkm** [comment]
@AshKelly would you mind updating this with the current version of `main`, please? I think this would be good to get in for 4.0 too!

**Pull request closed without merging**
