### PR TITLE
[2/2] No ambiguous fields automatic — bump answer tests

### PR DESCRIPTION
**Pull request by cphyc**
## PR Summary

Follows #3101 by bumping answer tests. This PR should be merged after #3101 is itself merged as it shares all but 2 commits.

Updates to the answer are in https://github.com/yt-project/answer-store/pull/18.

### CODE REVIEW

**Comment by cphyc** [comment]
I have to update the answer tests in the answer store as well!

**Comment by cphyc** [comment]
`py38_answertests` fail are due to https://github.com/yt-project/answer-store/pull/18 not being merged yet.

**Comment by cphyc** [comment]
@yt-fido test this please

**Comment by cphyc** [comment]
[just rebased on the last version of #3101]

**Comment by cphyc** [comment]
@yt-fido test this please

**Review by munkm — APPROVED** [review]

**Pull request merged**
