### PR TITLE
Sink csv

### PR DESCRIPTION
**Pull request by Lenoble-lab**
Hello, 
Sorry for this really small pull request. 
I realized just now that there is a small mistake of capital letters in the merge request I did one year ago. It leads to some bad named variables for RAMSES sink output. 

Best regards
Romain

### CODE REVIEW

**Comment by neutrinoceros** [comment]
I wasn't going to say anything but yes I would really like it better if this was done more cleanly. I also have concerns with backward compatibility here since the original patch was already released but we have tools to deal with it and we can discuss that in the second PR.

**Comment by Lenoble-lab** [comment]
Hello, 
Yes sorry, I did not start a new branch from the previous PR. I did not see that all the previous commits were added. 
I will start a new branch if it is better.

**Comment by chrishavlin** [comment]
ok, thanks @Lenoble-lab ! apologies for causing a bit of extra work for you.

**Comment by neutrinoceros** [comment]
Thank you for your understanding!

**Pull request closed without merging**
