### PR TITLE
MNT: prevent dependabot from upgrading minimal requirements

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

A more aggressive (and guaranteed correct) approach than my previous attempt in #4989, after the fiasco that ensued (#5002, #5003, #5005, #5006).
Revert #4989

### CODE REVIEW

**Comment by neutrinoceros** [comment]
@yt-fido test this please

**Comment by neutrinoceros** [comment]
@Xarthisius looks like Jenkins is having issues rendering the docs here (though I don't get why it's even trying)
Screenshot 2024-09-27 at 11 09 38

**Comment by neutrinoceros** [comment]
milestoning this so as to avoid conflicts in backporting

**Review by chrishavlin — APPROVED** [review]

**Comment by neutrinoceros** [comment]
Thanks for approving ! I'll merge this tomorrow when I have time to deal with another (however unlikely) storm of unwanted PRs.

**Pull request merged**
