### PR TITLE
REL: bump version to 4.1.3

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

Finalize yt 4.1.3

### CODE REVIEW

**Review by jzuhone — APPROVED** [review]

**Comment by neutrinoceros** [comment]
The failure is unrelated, but there's also nothing really urgent about this release so it can wait for a resolution.

**Comment by neutrinoceros** [comment]
for reference this is the "blocking" issue: https://github.com/yt-project/yt/issues/4257

**Comment by jzuhone** [comment]
I actually think this is rather urgent since we've already seen this break user code in a few places. Happy to help out.

**Comment by neutrinoceros** [comment]
@jzuhone no worries we can get it out today; everything needed should be listed in #4258

**Comment by jzuhone** [comment]
Ok--if you need my help let me know, I am mostly responsible for this issue.

**Comment by neutrinoceros** [comment]
I don't have all day to babysit this and it's fairly safe to assume it doesn't break tests so I'll merge and push the tag now

**Pull request merged**
