### PR TITLE
BLD: drop support for CPython 3.7

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

As announced on the mailing list
https://mail.python.org/archives/list/yt-dev@python.org/thread/V465SPCOWING6MUDUH2CQF5KCRL6CQ52/

Hopefully this is a full drop + cleanup.

This is targetted to yt 4.2, so I'll open a milestone for that. It's also still conditional on a (lazy ?) consensus, so I'll keep this as a draft for a couple weeks at least.

todo: 
- [x] cleanup after #4140 goes in

### CODE REVIEW

**Comment by neutrinoceros** [comment]
For details, I've also upgraded minimal requirements:
- numpy and matplotlib bumped to their respective oldest versions with binaries for CPython 3.8
- cmyt and unyt are bumped to their current latest versions to include our latest bug fixes there. These upgrades were not possible before because cmyt and unyt both require Python 3.8 already

**Comment by neutrinoceros** [comment]
many apparent flaky test failures, let's try that again

**Comment by matthewturk** [comment]
LGTM after waiting for 4.1

**Comment by neutrinoceros** [comment]
@yt-fido test this please

**Review by matthewturk — APPROVED** [review]

**Comment by jzuhone** [comment]
I've been trying to merge this but cannot. Anyone know why?

**Comment by neutrinoceros** [comment]
No idea what happened, but looks like you managed after all :)

**Pull request merged**
