### PR TITLE
Add current density fields

### PR DESCRIPTION
**Pull request by yihaochen**
## PR Summary

Add current density vectors and magnitude as a field plugin. This might be useful for people with MHD simulations who want to inspect the properties of the electric current. It is basically calculating the curl of magnetic fields and convert to appropriate units. Most of the code is copied from the vorticity calculations in `fields/fluid_vector_fields.py`.

I spent some time making sure the units of the electric current are correct in both cgs and SI systems. But it would be great if someone familiar with the EM units can check again!

## PR Checklist

- [x] Code passes flake8 checker
- [ ] New features are documented, with docstrings and narrative docs
- [x] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Take a look at #1693. Perhaps this should be merged after that one? This is going to need to be updated to use the `relative_magnetic_field_[xyz]` fields that PR defines.

**Comment by yihaochen** [comment]
I see and will update it later. But I cannot find where you define the `relative_magnetic_field_[xyz]` fields in #1693.

**Comment by ngoldbaum** [comment]
It happens indirectly via the `create_relative_field` function defined in `vector_operations.py`.

**Comment by yihaochen** [comment]
OK. So the `relative_magnetic_field_[xyz]` is only the difference between `magnetic_field_[xyz]` and the vector `bulk_magnetic_field`, right? I was thinking about transformation between two rest frames, which might introduce non-zero electric fields.

**Comment by ngoldbaum** [comment]
Ah yes, nothing that fancy although I guess in principle `bulk_velocity` might matter? Better not to worry about that until someone actually needs it for something.

Just a note for potential reviewers, the tests on this one won't pass until #1693 is merged.

**Comment by matthewturk** [comment]
@yihaochen Hi!  Can I help with getting this across the finish line?

**Comment by yihaochen** [comment]
@matthewturk But thanks for checking in. I almost forgot about this. I am not sure what went wrong in the tests or what is still needed for this PR.

**Comment by matthewturk** [comment]
@yihaochen Great -- I will take a look and push the resolution to the conflicts to your fork, and we can take it from there.

**Comment by matthewturk** [comment]
OK, I've merged!  Let's see how it goes.

**Comment by yihaochen** [comment]
It looks like there is something wrong with the units in MKS. I looked into it but have not figured out where the problem is. It seems that all the "relative_magnetic_field_[xyz]" are converted to CGS even if the unit system is MKS. 

I probably will need some more time to work on this.

**Comment by matthewturk** [comment]
@yihaochen ah, great. If I can help, let me know. @jzuhone may have an idea about the unit issues.

**Comment by ngoldbaum** [comment]
It's possible these are bugs that have been fixed in unyt but are still issues in yt.units. Maybe try rebasing this on the yt-4.0 branch and see if the tests pass?

**Comment by jzuhone** [comment]
@neutrinoceros I may try taking the commits, rebasing on current `main`, and fixing it, because it fits into something else I'm going to do eventually. But no need to re-open this one.

**Pull request closed without merging**
