### PR TITLE
[WIP] Adding Cholla Frontend

### PR DESCRIPTION
**Pull request by chummels**
## PR Summary

This adds a frontend to yt for working with datasets from the CHOLLA code (https://github.com/cholla-hydro/cholla).  It's currently a work-in-progress, so do not merge it yet until I've removed that header and this text.

Currently, it can read in the dataset and give the field list ok, but it fails with an "endian" error when you actually try to look at some of the data.  This is a strange error, since all of the datasets are HDF5 files, which shouldn't yield issues with endianness.

For simplicity, I've also made it so nprocs=1, so it reads a single grid for the whole dataset, since it's unigrid.  After I get this working, I'll make yt chunk it into smaller-sized chunks for for efficiency.

### CODE REVIEW

**Comment by chummels** [comment]
For reference, the current issue is that Cholla datasets are written in big-endian format into the HDF5 files, and yt is complaining that it needs things in little-endian format.  I've looked into conversion utilities to byteswap between big-endian and little-endian, but I think this is going to be a whole lot of work.  

@brittonsmith suggested being able to use some high-level functions in the h5py API, but I haven't found any that actually work.  There is the `astype` method for use on individual h5py arrays, but I cannot get it to address the issue.  

I actually don't entirely understand why yt has problems with this, since h5py can read big-endian datasets to numpy arrays with no problems.  I guess maybe it's because it's cython code that's actually reading in the data arrays?

For reference to demonstrate this error, I've placed a sample cholla hdf5 dataset here:

http://chummels.org/cholla/30.h5

Here is a sample script that I'm trying to run on it:

```
import yt
ds = yt.load('30.h5')
ad = ds.all_data()
print(ad['density'])
```

And here is the traceback:

```
yt : [INFO     ] 2018-08-06 11:28:32,984 Parameters: current_time              = [ 30000.]
yt : [INFO     ] 2018-08-06 11:28:32,984 Parameters: domain_dimensions         = [128 128 128]
yt : [INFO     ] 2018-08-06 11:28:32,985 Parameters: domain_left_edge          = [0 0 0]
yt : [INFO     ] 2018-08-06 11:28:32,985 Parameters: domain_right_edge         = [ 10.  10.  10.]
yt : [INFO     ] 2018-08-06 11:28:32,985 Parameters: cosmological_simulation   = False
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    print(ad['density'])
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/data_objects/data_containers.py", line 255, in __getitem__
    self.get_data(f)
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/data_objects/data_containers.py", line 1294, in get_data
    self.index._identify_base_chunk(self)
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/geometry/grid_geometry_handler.py", line 293, in _identify_base_chunk
    gi = dobj.selector.select_grids(self.grid_left_edge,
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/data_objects/data_containers.py", line 1246, in selector
    self._selector = sclass(self)
  File "yt/geometry/selection_routines.pyx", line 136, in yt.geometry.selection_routines.SelectorObject.__cinit__
ValueError: Big-endian buffer not supported on little-endian compiler
```

If anyone has any ideas, I'm all ears.

**Comment by jzuhone** [comment]
@chummels did you ever get any resolution on this? I'm asking because I just came into some Cholla data myself.

**Comment by chummels** [comment]
@jzuhone I *just* saw this message.   No, I didn't find resolution, but I'm hopeful that @ngoldbaum 's new PR #2120 may help address it.  I'll try to work on this soon.

**Comment by ngoldbaum** [comment]
Ah, I completely missed this and did not make the connection, apologies!

**Comment by neutrinoceros** [comment]
@chummels what is the status of this PR ?

**Comment by chummels** [comment]
I started it over again from scratch about 6 months ago, and it's nearly working, but I'm still hung up on `_read_fluid_selection()`, and I'd deeply appreciate any help getting it out the door.  I'll close this PR and issue a new one with the additional changes.

**Comment by chummels** [comment]
Closed and resubmitted #3663 which attempts this again from scratch.

**Comment by matthewturk** [comment]
@chummels next time, instead of opening a new one, could we do a "force push" on the branch?  It will help to consolidate the comments, and help us not lose track of where you were having issues before, etc.

**Comment by chummels** [comment]
I didn't realize this was an option.  In the past, I've seen others close PRs and re-issue new ones, which is why I followed this path.  I can force-push this one to retain discussion.

**Comment by matthewturk** [comment]
No, let's just move to the new one!  NBD

**Pull request closed without merging**
