### PR TITLE
Bump deps

### LINKED ISSUE #2925: Out of date dependencies
### Bug report

Some of our dependencies have released major versions that we don't test against. We should probably ensure that they are working before the yt 4.0 release.

To name a few
| package | pinned version   | current latest version |
| :-------- | :-------------- | :--------------------- |
| astropy | 3.2.3 | 4.0.1 |
| pytest | 5.2 | 6.1.0 |
| scipy | 1.3.2 | 1.5.2 |
| xarray | 0.12.3 | 0.16.1 |
| cartopy | 0.17.0 | 0.18.0 |
| pint | 0.8.1 | 0.16.1 |
| pandas | 0.25.3 | 1.1.2 |

Note: I suspect pint is only used to benchmark against unyt, in which case it's not necessary to install it to test yt anymore.

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

fix #2925
(this is branched out of #2924)

to bump
- [x] astropy
- [x] scipy (can't be updated on windows for now)
- [x] cartopy
- [x] Xarray
- [x] pandas

to remove:
- [x] pint

update :
since unyt 2.8.0 was just released, I bumped it too so we don't rely on a specific commit that was somewhere between 2.7.2 and 2.8.0

### CODE REVIEW

**Comment by matthewturk** [comment]
What's carroty?

**Comment by neutrinoceros** [comment]
An artifact from autocorrect for Cartopy :)

**Comment by Xarthisius** [comment]
@yt-fido test this please

**Comment by neutrinoceros** [comment]
@yt-fido test this please

**Comment by Xarthisius** [comment]
@yt-fido test this please

**Review by Xarthisius — APPROVED** [review]

**Pull request merged**
