### PR TITLE
BUG: use tight layout by default when saving matplotlib figures

### LINKED ISSUE #3601: BUG: saving images crops out colorbar labels
### Bug report

**Bug summary**
This is a bug that affects some of our image references, it happens when the dynamic range of data is small (less than an order of magnitude) and a log norm is used  for the colorbar (which happens by default).

**Code for reproduction**

```python
import yt

def background(fields, data):
    return data["gas", "density"] + data["gas", "density"].max()*10000

ds = yt.testing.fake_amr_ds([("gas", "density")], units=["g/cm**3"])
ds.add_field(("gas", "my_density"), background, sampling_type="cell", units="g/cm**3")
p = yt.SlicePlot(ds, "z", "my_density")
p.save(f"/tmp/box.png")
```

**Actual outcome**

box

**Expected outcome**
In fact the desirable output can be obtained as
```python
p.save(f"/tmp/box.png", mpl_kwargs={"bbox_inches": "tight"})
```
box

But I'd argue that this should be the default behaviour. This seems extremely easy to fix but I expect it will take some time to merge a patch here because changing the default behaviour may affect a lot of image references.

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

This is a second a second attempt to fix #3601, reusing the patch from #3602
combined with the test framework modifications from #3633 to enable comparisons
for images of different sizes.
Opening as a draft to indicate #3633 takes priority over this.

### CODE REVIEW

**Comment by cphyc** [comment]
Thinking on top of my head on my phone, but have you tried using `constrained_layout=True` when creating the matplotlib figure?

31 Oct 2021 17:58:52 Clément Robert ***@***.***>:

> 
> *PR Summary*
> 
> This is a second a second attempt to fix #3601[https://github.com/yt-project/yt/issues/3601], reusing the patch from #3602[https://github.com/yt-project/yt/pull/3602]
> combined with the test framework modifications from #3633[https://github.com/yt-project/yt/pull/3633] to enable comparisons
> for images of different sizes.
> Opening as a draft to indicate #3633[https://github.com/yt-project/yt/pull/3633] takes priority over this.
> 
> ----------------------------------------
> 
> *You can view, comment on, or merge this pull request online at:*
> 
>   https://github.com/yt-project/yt/pull/3635
> 
> 
> *Commit Summary*
> 
* > ENH: Improve 2D figure layout in case the long axis is vertical[https://github.com/yt-project/yt/pull/3635/commits/4ffc8896354d1756fe250c6ea6626633859cf8b1]
* > TST: modify image comparison method to enable reports when actual and expected don't have the same shape[https://github.com/yt-project/yt/pull/3635/commits/af7093c1799cdf59fbc93808ffcba73becb72a94]
* > BUG: use tight layout by default when saving figures (PlotMPL) to avoid cropping labels out[https://github.com/yt-project/yt/pull/3635/commits/af2bf3e9efb883a36947804b3b790f5e2a4941d3]
> 
> *File Changes*
> 
> (2 files[https://github.com/yt-project/yt/pull/3635/files])
> 
* > *M* yt/utilities/answer_testing/framework.py[https://github.com/yt-project/yt/pull/3635/files#diff-0588597c99a8f042699cce2585f6e885e3dcbc0e2cc13c4618ca58eadf875a6f] (35)
* > *M* yt/visualization/base_plot_types.py[https://github.com/yt-project/yt/pull/3635/files#diff-813fdd3d212be372fea21282904849bdc1a899e20e90523a82a271a2d2074963] (13)
> 
> *Patch Links:*
> 
* > https://github.com/yt-project/yt/pull/3635.patch
* > https://github.com/yt-project/yt/pull/3635.diff

**Comment by neutrinoceros** [comment]
I have no experience with this paradigm, so no. What benefits do you expect from this approach ?

**Comment by cphyc** [comment]
> I have no experience with this paradigm, so no. What benefits do you expect from this approach ?

According to few sources on matplotlib's issue tracker (see e.g. https://github.com/matplotlib/cheatsheets/issues/30#issuecomment-655594205), `constrained_layout` is supposed to be a better version of `tight_layout` that doesn't screw your layout. To use it, create the figure using
```python
fig = plt.figure(constrained_layout=True)
```
rather than call `fig.tight_layout()` _a posteriori`.

**Comment by neutrinoceros** [comment]
Excellent. I was afraid this would be marginally better and a lot more expensive to implement/maintain, but the cost seems actually equivalent and MPL core devs seem to be unanimous on their preference, so let's try this

**Comment by neutrinoceros** [comment]
@cphyc turns out this is more than a single line patch, lets see what CI has to say.

**Comment by neutrinoceros** [comment]
oh and one thing that should be elucidated is how well this two options play together when combined. Users may already be passing `box_inches="tight"`, so if it turns out it's not compatible with `constrained_layout=True`, it'll be more work to catch that option and warn consumers not to use it.

**Comment by neutrinoceros** [comment]
So it seems to me that `constrained_layout` produces smaller diffs... but also doesn't fix the problem I was going at as `bbox_inches="tight"` does, e.g. here
Screenshot 2021-11-01 at 15 42 24
(the ylabel is fixed by `box_inches="tight"`, while this figure is unchanged using `constrained_layout=True`)

@cphyc, let me know if you want to have a looks, but otherwise I'll just remove the most recent commit (constrained_layout)

**Comment by neutrinoceros** [comment]
I realized that my modified testing framework produce nice reports but will upload polluted artifacts that are not suited to update the answer store. This needs more work, but I don't know when I'll be able to manage this, so I'm closing this PR for now.

**Pull request closed without merging**
