### PR TITLE
docs: apply black format

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

... and stabilise it with a pre-commit hook
This would have been included in [YTEP 0037](https://ytep.readthedocs.io/en/master/YTEPs/YTEP-0037.html) had I known about it.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
Oops, looks like this particular hook is very unstable and fails on its own outputs. Closing.

**Comment by neutrinoceros** [comment]
So actually... the tool isn't broken, but our _doc_ is, because it contains several syntax errors, I'll reopen after I push a fix for those !

**Comment by neutrinoceros** [comment]
I think the mere fact that I was able to discover problems within the docs demonstrates how useful this tool is :)

**Review by matthewturk — APPROVED** [review]

**Review by munkm — APPROVED** [review]
I think this is great (and thank you for fixing the errors). 

One thing that might enhance our dev docs (which you can do on this PR or separately) is that we should consider listing what tools are being run by the bot and would be installed with the pre-commit install. Our section in the docs https://yt-project.org/docs/dev/developing/developing.html#automatically-checking-and-fixing-code-style that talks about these tools is helpful, but at this point we have a few that are run and it might be helpful for future contributors to know what types of checks are going to be run.

**Comment by neutrinoceros** [comment]
I've been thinking about documenting them but it seems to me that it would generate unnecessary maintenance burden.

>  would be installed with the pre-commit install 

I'm not sure this clarification is needed but I'll still run with it: `pre-commit install` in fact installs the hooks in isolation (I think they are not even installed together but each one gets a virtual env of its own) so they are never in conflict with the user's env, but it also means they are not available outside of the framework.

The cool thing is that `.pre-commit-config.yaml` is naturally self-documenting because it necessarily refers to repositories by url, so I think the easiest way to address your concern would be to document that the exact tool bet is described in this file. WDYT ?

**Comment by munkm** [comment]
So the reason I suggested the change was because I went looking in our docs and I was surprised that even though we are using black for our code (and if this PR is merged, our docs) we have no documentation of that in our development guide. We don't have to describe in detail what is installed or what we're using -- I just think a bulleted list that describes our tooling and what they're used for would help enhance that part of the documentation. Something like this:

* **black** is used for code style and formatting consistency 
* **isort** is used to ensure imports are consistently ordered
etc. etc. 


Also, this way a potential dev doesn't need to get in the weeds in the dev process to know what to expect. Does that make sense? 
I hear you on the maintenance burden, but I (personally) think it's better to have out of date docs than no docs for things and documentation is a really good item for a first time contributor to contribute to yt with!

**Comment by munkm** [comment]
Anyways, I don't see any reason for that to hold up this PR! I just wanted to raise the issue with our docs. 🙂

**Pull request merged**
