### PR TITLE
[BUGFIX] [Boxlib frontend] Handle the case where the raw_fields were written out with ghost zones

### PR DESCRIPTION
**Pull request by atmyers**
This simply ignores the ghost zones if they are present in the file.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Hmm, jenkins seems to be having unrelated issues @Xarthisius

**Comment by Xarthisius** [comment]
@yt-fido test this please

**Comment by Xarthisius** [comment]
> Hmm, jenkins seems to be having unrelated issues @Xarthisius

Yeah, we run out of space. I freed ~0.7Tb should be enough...

**Comment by Xarthisius** [comment]
Now the failures are relevant (`yt.frontends.boxlib.tests.test_outputs.test_raw_fields`). I guess we need to bump answers @atmyers

**Comment by atmyers** [comment]
Thanks for ping, @Xarthisius. Just updated the tests.

**Comment by atmyers** [comment]
@yt-fido test this please

**Comment by atmyers** [comment]
@yt-fido test this please

**Comment by Xarthisius** [comment]
@yt-fido test this please

**Pull request merged**
