### PR TITLE
Execute setup only on a parent thread to prevent a failure with spawn

### PR DESCRIPTION
**Pull request by Xarthisius**
## PR Summary

In python3.8 on OSX multiprocessing switched from *fork*ing to *spawn*ing. In order to prevent parallel cythonize messing up the concurrency `setup()` has to be executed only on the main process.

### CODE REVIEW

**Comment by Xarthisius** [comment]
> What happens with `pip install .` ?

`pip install` invokes `python setup.py`

**Comment by jzuhone** [comment]
@matthewturk I had the same problem either way

**Comment by munkm** [comment]
@neutrinoceros this PR might fix the issue you had installing 4.0 on Python 3.8.

**Comment by neutrinoceros** [comment]
@munkm It does ! 🎉 
Thanks a lot @Xarthisius !

**Pull request merged**
