### PR TITLE
ci: add flake8-bugbear to travis linting (YTEP0037 6/6 part 0)

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

This PR adds flake8-bugbear to the linting stage for Travis. CI _should_ fail until PRs attached to #2666 are merged.

### CODE REVIEW

**Comment by matthewturk** [comment]
Just so I understand, we *expect* this to fail until the other bits in the series go in, right?

**Comment by neutrinoceros** [comment]
> Just so I understand, we expect this to fail until the other bits in the series go in, right?

exactly ! that's test-driven dev for you 😄

**Comment by neutrinoceros** [comment]
Alright to only #2667 is still not merged (tests are running), so I've made this branch a continuation of it, and bugbear checks should now pass here.

**Comment by neutrinoceros** [comment]
@yt-fido test this please

**Pull request merged**
