### PR TITLE
deprecate simulation answer testing framework

### PR DESCRIPTION
**Pull request by munkm**
## PR Summary

Deprecates `can_run_sim` and `requires_sim` in our answer testing framework.

These functions aren't used anywhere by our answer tests, so they should probably be deprecated. 

If anybody feels strongly about it, we could delete them too. I don't see why these would be used downstream. But maybe I'm missing something. But deprecation feels like the safer option if we don't know for sure. 

@brittonsmith you added these in 2014. Do we need them anymore? 

## PR Checklist

- [x] Code passes flake8 checker
- [ ] New features are documented, with docstrings and narrative docs
- [ ] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by brittonsmith** [comment]
`requires_sim` is used in the `yt_astro_analysis` tests. If we're going to remove it, could it be moved there?

**Comment by matthewturk** [comment]
@brittonsmith moving that one to astro analysis seems like a good idea to me

**Comment by matthewturk** [comment]
Once tests pass I'll merge this

**Comment by neutrinoceros** [comment]
@munkm could you update the branch (rebasing is probably the cleanest option) ?

**Comment by neutrinoceros** [comment]
@yt-fido test this please

**Pull request merged**
