### PR TITLE
[WIP] Pytest

### PR DESCRIPTION
**Pull request by jcoughlin11**
## PR Summary

This Work in Progress PR is meant to address answer testing in yt. Currently, yt uses nose for its testing. Additionally, the answer tests are quite time and memory intensive, at the moment. This PR is meant to do two things: switch from nose to pytest to simplify the answer testing environment, and to implement hashes in the answer tests to hopefully streamline them.

Also, I know this PR is being issued off of master, and I'm not supposed to do that, but I couldn't get the answer tests to work on yt-4.0 (hopefully this PR addresses this, as well), so my fork's branch was made off of master. I apologize if this is an issue.

## PR Checklist

- [ ] Code passes flake8 checker
- [ ] New features are documented, with docstrings and narrative docs
- [ ] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by matthewturk** [comment]
Hi @jcoughlin11 , I know this isn't done, but I have a few broad comments and I'll leave some specific ones.

 * Make sure all your docstrings are in the format we use, or they might cause issues for the build of the docs.  You also should either fill them out or yank them -- not all functions *need* docstrings, but those that have them should have ones that match the functionality.
 * Check the PEP-8 compliance.
 * Before this can go in, the documentation will need to be updated, and we should let folks on yt-users / yt-dev know.  This change in principle will make the tests much easier to use (especially answer tests) but it will also change behavior a bit.

I'll leave comments, as well.

**Comment by matthewturk** [comment]
It looks like you've added a few files that might have been leftover and caught up in a `git add .` call.  Can you remove:

 * `yt/utilities/answer_testing/blah.py`
 * `yt/utilities/lib/bounded_priority_queue.c`
 * `yt/utilities/lib/cykdtree/kdtree.cpp`
 * `yt/utilities/lib/cykdtree/utils.cpp`
 * `yt/utilities/lib/cyoctree.cpp`
 * `yt/utilities/lib/ewah_bool_wrap.cpp`
 * `yt/utilities/lib/particle_kdtree_tools.cpp`
 * `yt/utilities/lib/pixelization_routines.cpp`

Looks like there are some symlinks that got added, too.  I think these are all under `Data/` so just making sure they are not included would be sufficient.

**Comment by jcoughlin11** [comment]
As far as I can tell, all of the answer tests (not just the front-end answer tests) have now been ported over to pytest except for the TestFieldAccess test. I just need to update the docs regarding the new functionality.

**Comment by munkm** [comment]
Since this PR is so huge, I think we need to bypass some of our standard review practices and split it up into manageable portions. In the triage meeting today we proposed to split things thematically and have at least one reviewer for smaller thematic chunks of this PR to make sure there's good review coverage on everything. 

If I do `git diff a546d17c8..HEAD --name-only` I can see a list of all of the names of the files changed. Major folders changed are:
* top-level files like .gitignore, conftest.py, setup.py, __init__.py and yt/testing.py
* `doc/`, including documentation and the `test cookbook` functionality
* `yt/analysis_modules` - 11 files
* `yt/data_objects` - 6 files
* `yt/fields` - 2 files
* `yt/frontends` - 65 files
* `yt/geometry` - 2 files 
* `yt/utilities` - 8 files
* `yt/visualization` - 9 files

Most of these I think naturally chunk themselves out. I might also consider grouping the `fields`, `geometry`, and `doc` folders together, since they're all only two-ish files. Some of the files changed also have fairly small differences, but I think right now this is a reasonable starting point to split up our labor. That said I'm not sure how best to split up the `frontends` folder review. 

Anyways, how does this sound: choose one of the four groupings below and click the checkbox and say what of the options you're reviewing. If you feel like being a second reviewer on one of the categories, please feel free to do that too! I think these checkboxes can help us track that we have appropriate coverage with at least one reviewer on each. 

- [ ] top-level files + fields/geometry/doc
- [ ] utilities + data objects
- [ ] visualization 
- [ ] frontends
- [ ] analysis modules

@Xarthisius @jzuhone @matthewturk what do you think?

**Comment by munkm** [comment]
also @ngoldbaum and @brittonsmith I'd be interested in your thoughts on how to split up this review.

**Comment by matthewturk** [comment]
@jcoughlin11 can you fix the conflicting files?  And, what's the current status of this PR?

**Comment by jcoughlin11** [comment]
I can fix them, yeah. The status is that, hopefully, it should be good to go. I've implemented pytest parametrize for the applicable tests, which means most of the loops inside the tests could be removed. I've also overhauled how the answer files are written. Each answer test class gets its own file. Within that file every combination of test parameters for a given test function gets its own entry that includes the values of the test parameters as well as any applicable array hashes. Everything is a dictionary now instead of an OrderedDict, so there are no more duplicate anchor issues and the whole thing should be entirely human readable. I need to update the documentation to reflect the newest changes.

**Comment by jcoughlin11** [comment]
The code now passes flake8 with the exception of: ./yt/utilities/on_demand_imports.py:441:17: F401 'pytest.main' imported but unused

I'm not sure what to do about that one.

**Comment by matthewturk** [comment]
You can use `# noqa` on it for now.

**Comment by munkm** [comment]
Hey out of curiosity why is https://github.com/yt-project/yt/pull/2286/commits/952d2bbd70acf1f23369fabe39d99d156b139df1 in this pull request? It seems unrelated.

**Comment by jcoughlin11** [comment]
I had to fix it in order to go ahead with validating the tests, but yeah, it should be its own thing. I just thought I'd mention what I had done.

**Comment by jcoughlin11** [comment]
Should I cherry pick that commit into a new PR that addresses that issue?

**Comment by ngoldbaum** [comment]
> Should I cherry pick that commit into a new PR that addresses that issue?

yup. Also note in the PR you make that it closes the issue Matt opened about this, #2359

**Comment by munkm** [comment]
Since @jcoughlin11 is reissuing the pytest PRs for yt-4 i'm going to close this out knowing we'll replace it with other PRs. We're really excited about your pytest work Jared! 🚀 🤖

**Pull request closed without merging**
