### PR TITLE
Migration script: migrate with user input

### PR DESCRIPTION
**Pull request by cphyc**
## PR Summary

At the moment, if a user has `~/.config/yt/ytrc` but no `~/.config/yt/yt.toml`, a hard-exit happens which prevent yt from being used. Though we display an explicit message advising the user on how to fix the issue, we may give the user a chance to interactively perform the migration immediately to lower the friction of this transition.

### CODE REVIEW

**Review by neutrinoceros — APPROVED** [review]

**Comment by Xarthisius** [comment]
If I updated yt on a cluster and run a batch job, I'd be very unhappy that my CPUh were spent on waiting on `input()`. I'd be infinitely less unhappy if it died right away.

**Comment by matthewturk** [comment]
Ok, this is an extremely good point. Let's brainstorm solutions.

**Comment by Xarthisius** [comment]
Can we just do it like we do with everything else? Start with deprecation warning over the course of one release, then die if not fixed after next + 1 release?

**Comment by neutrinoceros** [comment]
The point was to protect users from ignoring the warning + wondering what went wrong later. In all honesty, I'm reconsidering if it's even worth it. Thanks @Xarthisius for bringing this up. It actually happened to me once and I confirm it didn't make me a fan of the code in question...

Can we automatically perform the migration BUT keep the original file without appending ".bak" to it ?
Then both confit files would be present and we'd raise a non blocking warning at load time until the old one is (re)moved.

**Comment by cphyc** [comment]
I have made a recap of all the solutions that emerged out of the discussion. Please feel free to edit the pros/cons so that we converge relatively quickly.

| Solution | Pros | Cons
|-----|----|----|
| Stop early with a `raise SystemExit` (current behaviour) | Ensures users perform the migration | We may receive many complaints about yt "not working" |
| Raise warning then error in yt 4.0.1 | Transition is smooth for the users | Some users may ignore the warning and not perform the migration, yet still think `~/.config/yt/ytrc` is their config file |
| Raise warning, migrate automatically | Transition is even smoother for the users | We're modifying on-disk files without user's consent |
| Raise warning, migrate automatically after confirmation | Transition is smooth | Will result in annoying behaviour if launched on a non-interactive environment (ex. on a cluster) as we're using for user input |

**Comment by neutrinoceros** [comment]
I voted 🎉 because the "cons" is actually aligned with yt's old behaviour: we used to create a ytrc file when none was found, BUT I actually don't like this "feature" very much (for the exact reason you're mentioning).
I think it is reasonable to migrate automatically provided two restrictions are followed
1) do not write to yt.toml if the file already exists
2) do not _create_ a config file ex-nihilo, only do it if the old one is present.

Again, if this turns into a monstrosity of maintainability, my second preferred option is "👍🏻"

**Comment by cphyc** [comment]
Regarding

> I voted tada because the "cons" is actually aligned with yt's old behaviour: we used to create a ytrc file when none was found, BUT I actually don't like this "feature" very much (for the exact reason you're mentioning).
> I think it is reasonable to migrate automatically provided two restrictions are followed
> 
>     1. do not write to yt.toml if the file already exists
> 
>     2. do not _create_ a config file ex-nihilo, only do it if the old one is present.
> 
> 
> Again, if this turns into a monstrosity of maintainability, my second preferred option is "rocket"

Regarding your points:

1. currently, the error is only triggered iff `ytcfg` exists but `yt.toml` does not. If both are present, there's only a warning.
2. this would imply a larger change (but why not) as currently yt creates an empty config file if none is found. Note that this behaviour is only here because I left it in #2981, but is not necessary _per se_. Another point: the current issue is only affecting users who aren't new to yt. They should all have a `ytrc` file since it is created automatically. For new users, there's no problem as they don't have a `ytrc` file.

**Comment by neutrinoceros** [comment]
>1. currently, the error is only triggered if ytcfg exists but yt.toml does not. If both are present, there's only a warning.

excellent

>2. the current issue is only affecting users who aren't new to yt. They should all have a ytrc file since it is created automatically. For new users, there's no problem as they don't have a ytrc file.

Fair enough, I didn't connect the dots.

**Comment by matthewturk** [comment]
Are we also putting folks into a weird spot if they have both a 3.x and 4.x installation present?

**Comment by cphyc** [comment]
> Are we also putting folks into a weird spot if they have both a 3.x and 4.x installation present?

Currently, the only problematic case is when `~/.config/yt/ytrc` exists, `~/.config/yt/yt.toml` does not *and* users are on the `main` branch of yt.

If both config files exists, there is a warning and nothing else.

**Comment by matthewturk** [comment]
OK, that actually sounds like an OK solution to having both, to me...

**Comment by cphyc** [comment]
@matthewturk @Xarthisius @neutrinoceros I have created two other PRs (#3047 and #3046) that implement the automatic migration and the simple warning solution respectively. Could you have a look and tell me which one should be kept?

**Comment by neutrinoceros** [comment]
#3047 is my preferred option, given some further changes.

**Comment by munkm** [comment]
It seems like 🚀 is winning the poll?

**Comment by neutrinoceros** [comment]
Yup. As the only advocate for a different option I gracefully resign. I think the poll was open long enough that everyone who wanted to vote already did. Moving forward ? :)

**Comment by munkm** [comment]
I think 🚀 was still your second choice option though! 

> Moving forward ? 

I support it!

**Comment by neutrinoceros** [comment]
It was. That's why I'm _gracefully_ resigning, instead of being this guy.
image

**Comment by cphyc** [comment]
Closing this now in favour of https://github.com/yt-project/yt/pull/3046.

**Comment by cphyc** [comment]
Closing this now in favour of https://github.com/yt-project/yt/pull/3046.

**Review by neutrinoceros — COMMENTED** [review]
Oops, forgot to push the "submit" button yesterday. Might as well publish this review even if the PR is dead

**Pull request closed without merging**
