### PR TITLE
[BUGFIX] Fix clamping bug in _prepare_grid

### PR DESCRIPTION
**Pull request by atmyers**
I hit this on a 2D WarpX dataset with mesh refinement for some reason...

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Ugh.... this is my fault. Sorry!

**Comment by ngoldbaum** [comment]
It looks like there are a couple answer test failures. It looks like I updated these answers (along with a number of other ones) when I added this bug, so I think we can probably safely just increment the answer number again.

If you feel like it, it would be awesome if you could dig in and veryify that the answers for the failing tests are currently wrong, although I 100% understand if that's too painful to dive into.

**Comment by atmyers** [comment]
I can take a look, but probably not until tomorrow.

**Comment by ngoldbaum** [comment]
Merging because I think this is clearly the correct fix.

**Pull request merged**
