### PR TITLE
Manual backport for #4839

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

there were a couple stylistic conflicts with #4844

### CODE REVIEW

**Review by chrishavlin — APPROVED** [review]

**Comment by chrishavlin** [comment]
@yt-fido test this please

**Comment by neutrinoceros** [comment]
@chrishavlin tests on Jenkins are fundamentally broken from the backport branch because of some update in stored gadget datasets. If all failures are about gadget there's nothing we can do about those

**Comment by chrishavlin** [comment]
ah! ok! i'll stop re-testing then :)

**Comment by neutrinoceros** [comment]
update: I meant GAMER, not Gadget

**Pull request merged**
