### PR TITLE
[bugfix] A Dataset's UnitSystem should have its UnitRegistry

### PR DESCRIPTION
**Pull request by jzuhone**
During the creation of a `Dataset` instance it is assigned a `UnitSystem`, which the end-user can specify. Upon importing `yt` a number of `UnitSystem` instances are automatically created, such as "cgs", "mks", "galactic", etc. One of these is specified to `yt.load` (or the default) and it is assigned as the `Dataset`'s unit system. 

If done in this way, the `UnitSystem` does not have the correct `UnitRegistry` object. This PR fixes that problem by enforcing that a new `UnitSystem` instance is created which is associated with the `Dataset`'s `UnitRegistry`.  

I'm not thrilled about this solution, but the other solutions I came up with were messier than this, and I thought doing a `deepcopy` or something similar of the original `UnitSystem` instance and simply fixing the registry was a bad idea.

Closes Issue #2032.

### CODE REVIEW

**Comment by jzuhone** [comment]
@yt-fido test this please

**Comment by ngoldbaum** [comment]
@yt-fido test this please

**Comment by jzuhone** [comment]
@yt-fido test this please

**Comment by ngoldbaum** [comment]
The test failures are unrelated. This looks good to me!

**Comment by ngoldbaum** [comment]
@yt-fido test this please

**Pull request merged**
