### PR TITLE
Relax a GIZMO frontend validation criteria

### PR DESCRIPTION
**Pull request by qobilidop**
There could be other numbers of metal species.

### CODE REVIEW

**Comment by qobilidop** [comment]
Hi @chummels, thanks for the clarification. Currently, I have datasets with 12 and 15. The number of actual metal species is still 11, but there could be additional "dummy" elements. Looking at the gizmo code, the number `NUM_METAL_SPECIES` is set as below:

```
#ifdef GALSF_FB_RPROCESS_ENRICHMENT
#define NUM_RPROCESS_SPECIES (GALSF_FB_RPROCESS_ENRICHMENT)
#else
#define NUM_RPROCESS_SPECIES 0
#endif

#ifdef COOL_METAL_LINES_BY_SPECIES
#define NUM_METAL_SPECIES (11+NUM_RPROCESS_SPECIES)
#else
#define NUM_METAL_SPECIES (1+NUM_RPROCESS_SPECIES)
#endif
```

Eventually, it comes down to [GALSF_FB_RPROCESS_ENRICHMENT](http://www.tapir.caltech.edu/~phopkins/Site/GIZMO_files/gizmo_documentation.html#config-galsf-fire), which defaults to 4 in FIRE physics. I'm less familiar with GADGET, and the possible collision. If that is a serious concern, I'm fine with using `GizmoDataset` explicitly and leave the criteria here as it is.

**Comment by ngoldbaum** [comment]
It would be *really* nice if one of you could convince Phil to add some metadata to the Gizmo HDF5 outputs that indicates that the file was produced by Gizmo. Someting as simple as a string attribute somewhere would be sufficient.

**Comment by chummels** [comment]
@ngoldbaum you're absolutely right.  He's away this week at Ringberg, but I'll talk to him when he's back and try to get this change included.  I don't think any of the Gadget datasets to my knowledge use 11+ color fields like this, so we're probably ok accepting this PR.  Unless people have other opinions on it?

**Comment by ngoldbaum** [comment]
@qobilidop I'm going to close this PR, hopefully we can come back to this after Gizmo gains better metadata in its output format.

**Pull request closed without merging**
