### PR TITLE
RFC: change DerivedField.units attr type (str -> unyt.Unit)

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

Rationale: it's easier to convert a Unit objet to string than vice versa.

Expected gain: overall simplifications.

If I find a reason why this change isn't feasible along the way, at least I'll have learned why, and I may even find some simplifications that can still be done.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
So an important difference is that by *not* delaying conversion from str to Unit, we loose the ability to register field globally with units that don't exist in the common registry, e.g.

```python
import yt

@yt.derived_field(name="xxx", sampling_type="cell", units="code_length")
def xxx(field, data):
    return data["index", "x"]
```
However we should probably require that global fields use only units that are globally registered.
This would imply that in my example above, users should register `"code_length"` at a global level first.
We know however that units registration at the global level doesn't work at all (#3876), so probably we should fix that first.

**Comment by neutrinoceros** [comment]
Many tests are still broken because a couple builtin fields are defined using `"code_*"` units, so it falls in the same problem I pointed to above. Most notably particle fields. I don't know why it was implemented that way, but it doesn't look trivial to factor that out, so I expect It could be hard to even experiment on a refactor.
Overall #3876 and #3967 appear to be related, and much higher priorities. I'll keep this as a draft for now (makes it easier to explore failing tests if I want to come back to it) but I may close it soon if I can't think of a way forward.

**Comment by matthewturk** [comment]
I think we shouldn't pursue this at this time.

**Comment by neutrinoceros** [comment]
agreed. I'll focus on related issues first. I may resurrect this in the future.

**Pull request closed without merging**
