### PR TITLE
support active particle fields that map to arrays

### PR DESCRIPTION
**Pull request by ngoldbaum**
This makes it possible to read in active particle fields that represent arrays. With this change I'm able to run the script from @john-regan's e-mail to the mailing list.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
This assumes that the array fields are all the same shape, which I think is a sane thing to assume but maybe not.

**Comment by ngoldbaum** [comment]
@yt-fido test this please

**Comment by ngoldbaum** [comment]
@yt-fido test this please

**Comment by brittonsmith** [comment]
Is it possible to get some sample data so this can be tested?  @john-regan, do you have anything relatively small that could be used?

**Pull request merged**
