### PR TITLE
[bugfix] Update annotate_timestamp to work with "code" unit system 

### PR DESCRIPTION
**Pull request by munkm**
## PR Summary

This resolves the bug reported in yt-project/yt#2432 . Now when a dataset loaded using `unit_system=code` and `annotate_timestamp()` is called, the time returned is in `code_time`. 

With the fix applied, the plot looks like so:
timestamp_annotated

Let me know if you'd like a test added for this fix. 

## PR Checklist

- [x] Code passes flake8 checker
- [ ] New features are documented, with docstrings and narrative docs
- [ ] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by jzuhone** [comment]
Hi @munkm,

This looks fine to me, but is it necessary to set the `time_unit` attribute to the code unit and then do formatting, or could one not just set `self.time_unit = '(code_time)'` or something similar?

**Comment by munkm** [comment]
Great question @jzuhone. I think that's another option we could take. In doing this I followed sort of what we did in [this part](https://github.com/yt-project/yt/blob/master/yt/visualization/plot_container.py#L638-L640) of `_get_axes_unit_labels` and then looked at how we had formatted our field names in the plotters. I noticed most of those were Unit objects and used the latex function to format them. 

I could instead set up a dictionary like the `formatted_length_unit_names` so it will automatically format code_time properly when it's printed as a label. 

I maybe have an overcomplicated solution here.

**Comment by matthewturk** [comment]
@munkm @jzuhone Do you think this should wait for the rewritten version?  I don't think it's that big of a deal to bring it in now.

**Comment by munkm** [comment]
I'm ok with it now, but happy to change it if we feel that would be better.

**Comment by matthewturk** [comment]
I'm going to go ahead and merge this, and additional things can be added later.

**Pull request merged**
