### PR TITLE
[bugfix] Use python3-safe hdf5 attribute reader in HaloCatalog frontend.

### PR DESCRIPTION
**Pull request by brittonsmith**

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Does this fix the issue Nick Gnedin reported?

**Comment by ngoldbaum** [comment]
It looks like there are a number of places in the library where we do stuff like this: https://gist.github.com/ngoldbaum/5fc40ed9dbae0c9f439326f65e7ead4c

I'm not sure offhand if all of these are working with hdf5 files, but I suspect most of them are. Are all of these accesses of `.attrs` unsafe?

**Comment by brittonsmith** [comment]
Unclear if this is the root cause of Nick's issue.  He was getting errors at load, and this only shows up once you create the field info container.

Many of the things that show up in a grep are instance of writing, which are safe.  I'm happy to fix all of the instances that are definitely hdf5 reading, though.

**Comment by brittonsmith** [comment]
I've gone through the instances of potentially unsafe attribute reading and fixed the few that I deemed critical and that I was confident in changing.  This issue will only show up in the cases where the attribute value is a string, and most of these did not appear that way.

**Comment by ngoldbaum** [comment]
Thanks for double-checking Britton! This LGTM, I'll hit the merge button when the tests pass.

**Pull request merged**
