### PR TITLE
Parallel covering grid

### PR DESCRIPTION
**Pull request by yingchaolu**
## PR Checklist

- [ ] Code passes flake8 checker
- [ ] New features are documented, with docstrings and narrative docs
- [ ] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
I need to test this locally to make sure it works in parallel but this looks like a nice, simple approach :)

Can this new capability get a mention in the docs on yt's parallelism? Here's some instructions on how to edit yt's documentation:

http://yt-project.org/docs/dev/developing/building_the_docs.html

The specific page that needs editing is this one:

http://yt-project.org/docs/dev/analyzing/parallel_computation.html

It might also be good to mention this parallel capability in the docstrings for `YTCoveringGrid`.

Finally, I think it should be possible to apply the same style of parallelism to `YTArbitraryGrid`, which is a subclass of `YTCoveringGrid` with its own `_fill_fields` implementation. Do you think you could parallelize `YTArbitraryGrid` as well?

**Comment by yingchaolu** [comment]
YTArbitraryGrid and YTCoveringGrid have different loop order, i.e. the order of chunks and fields. Which one is preferable?

**Comment by ngoldbaum** [comment]
I don't think the order matters. You could probably move the loop over fields inside the loop over chunks.

I also forgot to mention earlier that `YTSmoothedCoveringGrid` could also probably be parallelized in the same way.

**Comment by ngoldbaum** [comment]
By the way, not trying to move goalposts on you. This is mergeable now as-is, it would just be nice to have this parallelization applied for the other data objects that are analogous to covering grid.

**Comment by yingchaolu** [comment]
Would it be useful to change the mpi_allreduce function to a method on buffer, instead of object.
Like in 
https://mpi4py.scipy.org/docs/apiref/mpi4py.MPI.Comm-class.html
Allreduce(self, sendbuf, recvbuf, Op op=SUM) 
is much faster than
allreduce(self, sendobj, op=SUM)
The function mpi_allreduce in yt is the operation on object.

**Comment by ngoldbaum** [comment]
You should try. If that's faster a pull request would be very welcome.

**Comment by yingchaolu** [comment]
I would like to try.

I think a clean way is to add a function called mpi_Allreduce in the communication interface, otherwise I have to import MPI4py in the affected files. 

And then replace the mpi_allreduce with mpi_Allreduce in covering grid and so on.

**Comment by yingchaolu** [comment]
I do not know how I can modify the communication interface.

**Comment by yingchaolu** [comment]
I think this should be similar to the allreduce
https://github.com/yt-project/yt/blob/b38bdb8728a56df78ae0db286a87ce16b243e3a4/yt/utilities/parallel_tools/parallel_analysis_interface.py#L831-L846

Basically use @parallel_passthrough decorator and call self.comm.Allreduce

**Comment by ngoldbaum** [comment]
Sure, it would also be interesting to see if we could just patch `mpi_allreduce` to use `comm.allreduce` instead of `comm.Allreduce`. I have no idea offhand if that would break anything.

**Comment by yingchaolu** [comment]
I tried to add mpi_Allreduce. It is not significantly faster.

**Pull request merged**
