### PR TITLE
doc: fix missing `sampling_type` keyword argument in `add_field` examples

### LINKED ISSUE #3108: documentation for add_field does not discuss sampling_type
### Bug report

The narrative documentation discussing `ds.add_field`, e.g. [here](https://yt-project.org/docs/dev/developing/creating_derived_fields.html), does not mention the `sampling_type` argument, which is now required.

This should probably have a `yt-4.0` label, but maybe some consensus on that is required.

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

fix #3108 
(hopefully I got all the broken examples)

### CODE REVIEW

**Comment by munkm** [comment]
I think this should fix yt-project/yt#3108. 🙂 

Thank you for fixing the broken examples! Would you mind also updating the narrative documentation around the function examples in https://yt-project.org/docs/dev/developing/creating_derived_fields.html to explain a bit about the `sampling_type` and what options are available (and what that means)?

**Comment by neutrinoceros** [comment]
> I think this should fix #3108. 🙂

oops, good catch

> Would you mind also updating the narrative documentation around the function examples in https://yt-project.org/docs/dev/developing/creating_derived_fields.html to explain a bit about the sampling_type and what options are available (and what that means)?

I'm not in a good position to do that, I don't _know_ what it does. The reason I touched this code originally was to align the developers's intentions with the behaviour (the `sampling_type` argument was noted as required in a 3 y.o. change log), and get rid of noisy warnings.

**Comment by jzuhone** [comment]
`sampling_type` tells us what kind of volume sampling is done with this field. It's either `"grid"`, `"particle"`, or `"local"`. Most derived fields which are not particle fields should be `"local"`, because this catches both grid and SPH particle types.

There may be some `sampling_type` associated with unstructured meshes but I am not sure.

**Comment by neutrinoceros** [comment]
> There may be some sampling_type associated with unstructured meshes but I am not sure.

A quick review of the code base with `git grep "sampling_type="` tells me that there are no other types than the three you listed. (btw thank Darwin we use `black`, it makes this kind of search a lot easier and more robust)

@jzuhone if you feel like it, feel free to push to this branch.

**Review by matthewturk — APPROVED** [review]

**Comment by matthewturk** [comment]
@jzuhone you want any more changes before this goes in?

**Comment by munkm** [comment]
I do. It needs the addition to the narrative docs in order to fix the issue that's tagged.

**Comment by brittonsmith** [comment]
> I do. It needs the addition to the narrative docs in order to fix the issue that's tagged.

I second this.

**Comment by neutrinoceros** [comment]
Be my guests. I agree it needs be done but I'm not the right person for this. Anyone of you can feel free to push to this branch or open a second PR either based on this one or completely independent :)

**Review by jzuhone — APPROVED** [review]

**Comment by brittonsmith** [comment]
Ok, I've done it. @munkm, @jzuhone let me know if that looks ok.

**Review by munkm — APPROVED** [review]
This looks great to me!

**Comment by neutrinoceros** [comment]
thanks @brittonsmith !

**Comment by stonnes** [comment]
Hi, I am a little confused about this parameter, apologies if this is not the right place for these questions.  As a user, I would love to know why I would ever do something other than "local", because it looks like "local" just chooses cell or particle for me in some intelligent way?

**Comment by brittonsmith** [comment]
@stonnes the main example I can think of would be creating a particle field for a dataset that has both grids and particles, like Enzo. If you used "local", it would choose "cell" instead of "particle". Would you like me to add a discussion of this?

**Comment by stonnes** [comment]
Yeah, I think that would be useful.  So the idea is that yt will choose "cell" even though it is performing the function on particles?  I am blanking on why this is bad.  I mean, if I have "particle","mass" and yt pretends it is a "cell", "mass", who cares?  Is this more for fields that should be considering a particle smoothing length?

**Comment by matthewturk** [comment]
I think it's also for differencing stencils applied to particles.

**Comment by brittonsmith** [comment]
For example, with Enzo data where you have cells and particles, if you specify "local" or "cell", you'll get back a field that has a value for every cell. Only if you specify "particle" will you get back a field that has a value for every particle.

**Comment by stonnes** [comment]
OH I get it.  Yes, I think that that sentence you just wrote @Britton is
what I needed.  You are basically assigning the first of
("cell/particle","field_name") to your derived field?




--
Dr. Stephanie Tonnesen
Associate Research Scientist
CCA, Flatiron Institute
New York, NY

***@***.***

**Comment by stonnes** [comment]
OH I get it.  Yes, I think that that sentence you just wrote @Britton is what I needed.  You are basically assigning the first of ("cell/particle","field_name") to your derived field?

**Comment by stonnes** [comment]
perfect I am sold, thanks!  I approve if I have to officially say that, @munkm :)

**Comment by brittonsmith** [comment]
@stonnes, I made a couple more edits. Does that look ok?

**Comment by stonnes** [comment]
yup looks great, I like those last additions a lot.

**Comment by munkm** [comment]
> I approve if I have to officially say that, @munkm :) 

I love the explicit approval! I'll merge this when everything passes! Thank you @brittonsmith and @neutrinoceros for this fix! (one step closer to 4.0!!!)

**Pull request merged**
