### PR TITLE
[Experiment] coverage report from jenkins

### PR DESCRIPTION
**Pull request by git-abhishek**
## PR Summary

Generating coverage report at Jenkins and uploading it to yt's [codecov](https://codecov.io/gh/yt-project/yt).

- Due to `Coverage`, the runtime at Jenkins has increased which can be seen in [`py3` Jenkins run](https://tests.yt-project.org/job/yt_py3_git/375/console) where we exit due to reaching the timeout mark (90 mins). Either we have to increase the execution limit or disable `Coverage` at Jenkins (reject this PR).  

- The `subprocess` call with `codecov` command in the PR is just to check if uploading to yt's codecov works or not. If this PR is accepted, I need to update the PR by removing this call and adding this step in the Jenkins configuration file.

## PR Checklist

- [X] Code passes flake8 checker

## Adding Reviewers
@ngoldbaum @Xarthisius @colinmarc

### CODE REVIEW

**Comment by Xarthisius** [comment]
@yt-fido test this please.

**Comment by Xarthisius** [comment]
@yt-fido test this please.

**Comment by git-abhishek** [comment]
@yt-fido test this please.

**Comment by git-abhishek** [comment]
@Xarthisius now we need to add `codecov` in the build script at Jenkins.

**Comment by Xarthisius** [comment]
yup, I did that, before I merged

**Pull request merged**
