### PR TITLE
hotfix: yt.load_sample + yt_data_dir unset

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

This is an attempt at fixing a bug reported by @matthewturk on Slack.
I think the bug is plateform dependent and I don't have time to properly test it just yet, so I'm opening early in hopes that @matthewturk can test it locally first.

### CODE REVIEW

**Review by matthewturk — APPROVED** [review]
Seems good, although I'm somewhat partial to the idea of saving it in the `XDG_CACHE` directory.

**Comment by neutrinoceros** [comment]
Where is this done ? I feel like I'm missing something

**Comment by matthewturk** [comment]
I think pooch will do it by default.

**Comment by matthewturk** [comment]
Ah, so what I mean is that pooch uses the `userdirs` package to come up with default locations.  So, if left unspecified, the download location is set by `XDG_CACHE` or the default-for-that-system value for `XDG_CACHE`.  This way it is still a user-specific, systemwide location that will be identical across runs independent of working dir.  (i.e., if I cd to a subdir and re-run `load_sample`, it won't re-download)

**Comment by neutrinoceros** [comment]
I honestly can't tell which behaviour would feel intuitive or "correct" to most people, but I agree the change should be considered. Since you approved this I take it that you're ok with this patch going in as in since it's just fixing the current intended behaviour ?

**Comment by matthewturk** [comment]
I am fine with it going in as-is to fix the current behavior.

**Comment by neutrinoceros** [comment]
A slightly different approach would be to set `yt_data_dir`'s default value as XDG_CACHE, WDYT ?

**Review by cphyc — APPROVED** [review]
This looks good to me!

**Comment by neutrinoceros** [comment]
@matthewturk I also have an PR to change the default dir names here #3093
You have a good point that `XDG_CACHE` is likely a solid candidate default for yt_data_dir, so maybe we ought to open the discussion and this how well it applies to the rest of them too ?

**Pull request merged**
