### PR TITLE
TST: fix compatibility with numpy 1.22

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary
Attempt at fixing #3742
For now I'm just disabling astropy altogether, but a better solution would be prefered, I'm just not sure there's anything we can do about it on our side (other than pinning `numpy < 1.22`)

### CODE REVIEW

**Comment by neutrinoceros** [comment]
somehow test envs still end up including astropy. I'll sign off for today, but if anyone wants to inspect this (and possibly push to this branch), feel free to.

**Comment by neutrinoceros** [comment]
got it. `glueviz` depends on `astropy`, which is why is still installing. Let's see if maybe the problem is _just_ glueviz (and possibly only on Python 3.10, since nosetests jobs are not failing)

**Comment by neutrinoceros** [comment]
So I think I gathered enough evidence to state that the incompatibility in between Astropy's latest wheels and numpy 1.22.0; the problem isn't specific to a platform (seen on Ubuntu and Windows) or to a Python version (seen on Python 3.9 and 3.10).
However it seems to only show up in pytest sessions (not in nosetest) and is reproducible locally with
```
pytest yt/data_objects/tests/test_data_containers.py::TestDataContainers::test_to_astropy_table
```

I could get it down to a minimal reproducer:
```
pytest -c "import astropy"
```

Interestingly this issue seems to be specific to pytest, as the following command succeeds on the same install.
```
python-c "import astropy"
```
this seems simple enough to report upstream.

**Comment by neutrinoceros** [comment]
figured out that the error was specifically caused by our live pytest configuration (`conftest.py`). It probably qualifies as a pytest bug but I don't understand it well enough to report that upstream. Anyway the PR now actually fixes #3742, and I've cleaned up my messy commit history. I'll remove the draft status when CI goes green again.

**Comment by neutrinoceros** [comment]
back to draft because I think I can make it marginally better

**Review by cphyc — APPROVED** [review]
This looks good to me, even if catching a warning like the one below doesn't make me particularly happy.
But meh, it was already there before ;)

**Pull request merged**
