### PR TITLE
maint: remove vendored packages

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

Apparently the only of our vendored packages that is still used is `tqdm`, so I'm proposing to stop vendoring altogether and remove all of them + make tqdm an actual dependency.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
@yt-fido test this please

**Comment by neutrinoceros** [comment]
Help me @Xarthisius, you're my only hope.

**Comment by Piernik-Majster** [comment]
> Help me @Xarthisius, you're my only hope.

Add `tqdm` to `tests/test_requirements.txt` ?

**Comment by Xarthisius** [comment]
> Help me @Xarthisius, you're my only hope.

Add `tqdm` to `tests/test_requirements.txt` ?

**Comment by neutrinoceros** [comment]
Thanks ! I don't get why this was necessary since it was already specified in `setup.py` but at least it works.

**Review by matthewturk — APPROVED** [review]
So I think other than the merge conflict from a competing PR, this is ready, right?  Most of the vendored stuff hasn't been used much recently, and tqdm is pretty great and should be used, so I think this is good to go.

**Comment by neutrinoceros** [comment]
> So I think other than the merge conflict from a competing PR, this is ready, right?

solved, and yes, it is now ready :)

**Pull request merged**
