### PR TITLE
Be smarter about parsing the WarpX header file.

### PR DESCRIPTION
**Pull request by atmyers**
This is needed to support datasets with mesh refinement.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Any chance we can get a test dataset with mesh refinement and accompanying test? Doesn't need to be an answer test, could just load the dataset and verify the metadata.

**Comment by ngoldbaum** [comment]
@atmyers fix the flake8 tests?

**Comment by atmyers** [comment]
I'll add a test and sample dataset for this, but #1473 needs to be merged first, because otherwise the answers will be wrong.

**Comment by atmyers** [comment]
@yt-fido test this please

**Pull request merged**
