### PR TITLE
TST: unpin numpy on the dev branch to allow numpy 2.0.0dev0 in future-proofing tests

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

I've realised that this upper limit, while recommended in *releases* to protect users, is actually harmful in the development branch because it prevents testing against numpy `2.0.0dev0`. I'll open an issue to remind ourselves that the pin should be re-applied after yt 4.3 is branched out.

I've also added a call to `pip list` in tests so it's easier in the future to verify exactly what went into the testing environment, and fixed another small incompatibility (`np.float_`, alias to `np.float64`, was removed).

### CODE REVIEW

**Comment by neutrinoceros** [comment]
This hit a new incompatibility between numpy dev and unyt dev, adressed at https://github.com/yt-project/unyt/pull/442

**Comment by neutrinoceros** [comment]
The issue in unyt is now resolved, and this is ready.

**Comment by Xarthisius** [comment]
@yt-fido test this please

**Comment by neutrinoceros** [comment]
@yt-fido test this please

**Comment by neutrinoceros** [comment]
@yt-fido test this please

**Review by matthewturk — APPROVED** [review]
excellent work

**Review by jzuhone — APPROVED** [review]

**Pull request merged**
