### PR TITLE
BUG: migrate away from broken optional dependency (pyregion -> regions)

### LINKED ISSUE #4234: BUG: broken optional dependency (pyregion)
### Bug report

**Bug summary**

`pyregion` is being used sporadically in a couple docs notebooks and is a docs-only dependency to yt. It's also quite fragile as no wheels are available and `pip` fails to build the current latest version (2.1.1) from source.
The project is targeted for retirement https://github.com/astropy/pyregion/issues/153, so we should move to `regions` when possible (maybe it's already the case).

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary
Should fix #4234

### CODE REVIEW

**Review by matthewturk — APPROVED** [review]

**Comment by neutrinoceros** [comment]
two notes: 
- turns out `regions` isn't a drop-in replacement for `pyregion` so we still need to adapt the code somehow
```
AttributeError: module 'regions' has no attribute 'parse'
```

At least one of the notebooks that uses it in the docs is currently broken for a different reason:
https://yt-project.org/docs/dev/cookbook/fits_radio_cubes.html?highlight=fits%20radio
```
...
ValueError: Invalid vmin or vmax
```

This other problem is not my target here so if I can't find a solution I'll report it separately.
For information ping @jzuhone, who I assume is more knowledgeable than me on this part of the code

**Comment by neutrinoceros** [comment]
I may have opened this much too soon. Migration guidelines do not even exist yet, but here's where to follow progress on it, eventually: https://github.com/astropy/regions/issues/488

**Comment by neutrinoceros** [comment]
With a little help from `regions` people (...) I was able to complete the migration;
This can be checked with this snippet (extracted from our docs):

```python
import yt
from yt.frontends.fits.misc import ds9_region

ds = yt.load("grs-50-cube.fits.gz")
region = 'galactic;box(+49:26:35.150,-0:30:04.410,1926.1927",1483.3701",0.0)'
box_reg = ds9_region(ds, region)

print(box_reg.quantities.extrema(("fits", "temperature")))

prj = yt.ProjectionPlot(
    ds,
    "z",
    ("fits", "temperature"),
    origin="native",
    data_source=box_reg,
    weight_field=("index", "ones"),
)  # "ones" weights each cell by 1
prj.set_zlim(("fits", "temperature"), 1.0e-2, 1.5)
prj.set_log(("fits", "temperature"), True)
prj.save("/tmp/")
```

which yields
grs-50-cube fits gz_Projection_z_temperature_ones


(maybe the plot shouldn't have so much empty space in it but that's a different story, I think)

I will open this PR to review when I can verify that the docs build correctly

**Comment by neutrinoceros** [comment]
Not sure if this should be backported to the 4.1.x branch since `regions` isn't API stable yet, but I'll leave that decision up for discussion.

**Comment by matthewturk** [comment]
@neutrinoceros I think unless we get a bug report, we shouldn't at this point.

**Comment by neutrinoceros** [comment]
fine by me !

**Review by jzuhone — APPROVED** [review]

**Pull request merged**
