### PR TITLE
Remove answer name collision for test_mesh_slices.py

### PR DESCRIPTION
**Pull request by Xarthisius**
## PR Summary

Adds a suffix to test description that's used for generating answer name.

### CODE REVIEW

**Review by matthewturk — APPROVED** [review]
This looks good.  We'll need to regenerate these answers, right?

**Comment by Xarthisius** [comment]
> This looks good. We'll need to regenerate these answers, right?

Hopefully! New answers should pop up at the end of travis run.

**Review by munkm — APPROVED** [review]

**Comment by matthewturk** [comment]
Do we need to do anything, or can this be merged?

**Comment by munkm** [comment]
I think we need to resolve the travis error?

**Comment by Xarthisius** [comment]
> I think we need to resolve the travis error?

You mean the CI service we no longer use? :)

**Comment by Xarthisius** [comment]
This needs answer generation bit that was added in #2978

**Comment by munkm** [comment]
Hm I thought this PR hadn't been updated to the new gh actions test workflow last time I checked! It looks like it is now.

**Comment by cphyc** [comment]
@Xarthisius are the tests failing real?

**Comment by Xarthisius** [comment]
> @Xarthisius are the tests failing real?

Yeah, they're failing cause there are no old answers since I removed name collision. I need to upload them.

**Comment by Xarthisius** [comment]
Closing in favor of pytest work.

**Pull request closed without merging**
