### PR TITLE
Convert volume rendering to memoryviews

### PR DESCRIPTION
**Pull request by matthewturk**
Migrated from https://bitbucket.org/yt_analysis/yt/pull-requests/2330/convert-volume-rendering-to-memoryviews/diff

This converts much of grid-traversal and other VR-using items to use memoryviews. Right now I have only done this for the "data" attribute; there are other attributes I hope to convert as well, but I intend to do that as part of refactoring the samplers in conjunction with the work in PR 2185.

Unit (haven't finishing running answer) tests pass for me right now, but I want to emphasize that I've left on all of the bounds checking, initialization checking, etc etc, so this will be considerably slower. I don't want it to be accepted until those have been re-enabled, but I would appreciate code review, which can occur independently.

Update: I think this should speed things back up.

### CODE REVIEW

**Comment by cphyc** [comment]
Is this PR still alive?

**Comment by MatthewTurk** [comment]
@cphyc Kind of, yes.  It's not *dead* per se, but I did not ever get around to making it speed competitive and also correct.  I do believe in it!

**Comment by matthewturk** [comment]
I am leaving this open for *now*, but *if* it gets updated, it will be rebased against master after a 3.6 release.  But the existing issues that have been noted will need to be taken into account, and it may just be better to close it.

**Comment by neutrinoceros** [comment]
Looks like this is getting harder and harder to maintain. :(
Do you still want to keep it open ? Even if you wish to go through with it I'm thinking you might be better off just reissuing since this is sitting at the bottom of the tracker.

**Comment by matthewturk** [comment]
Let's close it. I'll reissue it some day if it ever needs it.

**Pull request closed without merging**
