### PR TITLE
refactor: remove yt.funcs.ensure_tuple

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

This is a follow up to #2893.
`ensure_tuple` is only used to sanitize `Dataset.periodicity` attributes in a such a fashion that it doesn't make any difference to use builtin tuple conversion. Hence, the function serves no purpose anymore and can be removed.

### CODE REVIEW

**Comment by matthewturk** [comment]
Love that this is #3000.

**Comment by matthewturk** [comment]
I need to think about this, because of the `always_iterable` call, to make sure that I agree it can't backfire.

**Comment by neutrinoceros** [comment]
The way I rewrote `ensure_tuple` in the previous PR revealed what the function was meant to do, in a vacuum, but I'm fairly confident that the designed property (being able to loop over a possibly scalar variable) was not used anywhere.

**Comment by neutrinoceros** [comment]
@matthewturk Looks like there's indeed a class where the `always_iterable` part was helping: `EnzoDataset`

original code
```python
self.periodicity = ensure_tuple(self.parameters["LeftFaceBoundaryCondition"] ==3)
```

Now it seems the easy fix would be
```python
self.periodicity = 3 * (self.parameters["LeftFaceBoundaryCondition"] ==3,)
```
with the side benefit that periodicity would always register as a three element tuple, instead of just one.
I hope this fixes the 7 failures seen on Travis that I got with my first attempt:
```python
self.periodicity = tuple(self.parameters["LeftFaceBoundaryCondition"] ==3)
```

**Comment by neutrinoceros** [comment]
wow. Now I'm getting a very surprising error:

```
======================================================================
1906
ERROR: yt.data_objects.tests.test_io_geometry.test_preserve_geometric_properties
1907
----------------------------------------------------------------------
1908
Traceback (most recent call last):
1909
  File "C:\Miniconda\lib\site-packages\nose\case.py", line 198, in runTest
1910
    self.test(*self.arg)
1911
  File "D:\a\yt\yt\yt\testing.py", line 803, in true_wrapper
1912
    return func(*args, **kwargs)
1913
  File "D:\a\yt\yt\yt\data_objects\tests\test_io_geometry.py", line 21, in test_preserve_geometric_properties
1914
    ds2 = load(fn)
1915
  File "D:\a\yt\yt\yt\loaders.py", line 99, in load
1916
    raise YTAmbiguousDataType(fn, candidates)
1917
yt.utilities.exceptions.YTAmbiguousDataType: Multiple data type candidates for C:\Users\RUNNER~1\AppData\Local\Temp\tmpvtkaxbc5\savefile.h5
1918
The following independent classes were detected as valid :
1919
<class 'yt.frontends.ytdata.data_structures.YTDataContainerDataset'>
1920
<class 'yt.frontends.ytdata.data_structures.YTDataset'>
1921
<class 'yt.frontends.ytdata.data_structures.SavedDataset'>
1922
<class 'yt.frontends.athena.data_structures.AthenaDataset'>
1923
A possible workaround is to directly instantiate one of the above.
1924
Please report this to https://github.com/yt-project/yt/issues/new
```
The weirdest part is that it only shows up on windows... after a commit that affects NONE of the incriminated classes.

**Comment by neutrinoceros** [comment]
Got it. Looks like I was incredibly unlucky that the tmp dir was named `tmpvtkaxbc5`, which validates `AthenaDataset._is_valid()`, see https://github.com/yt-project/yt/blob/b86eaea8746f437a72f28d6c632eefd658b4f637/yt/frontends/athena/data_structures.py#L649
I'll just relaunch the CI and mark this as a different issue.

**Comment by neutrinoceros** [comment]
I'm bundling a bugfix for AMRVAC while I'm at it... `AMRVACDataset.periodicity` was improperly parsed as a `numpy.ndarray`

**Comment by matthewturk** [comment]
@neutrinoceros Looks like things are passing now -- this ready to go?

**Comment by neutrinoceros** [comment]
Yes it is !

**Pull request merged**
