### PR TITLE
[bugfix] Fix recent windows failures on github actions

### PR DESCRIPTION
**Pull request by jzuhone**
## PR Summary

This PR should fix recent Windows compilation failures on Github action `windows-latest`. It appears the compiler has been updated.

## PR Checklist

- [ ] New features are documented, with docstrings and narrative docs
- [ ] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Review by munkm — APPROVED** [review]

**Review by neutrinoceros — APPROVED** [review]
I don't know much about this but it looks like it's working.

**Comment by jzuhone** [comment]
`lrint` is defined in the new versions of the compiler but previously we were defining it as an inline function

**Comment by jzuhone** [comment]
Everything passed, so one of you can merge it and then we can re-run the tests on/rebase the failing PRs

**Comment by neutrinoceros** [comment]
I reran tests there https://github.com/yt-project/yt/pull/3129 and they still failed. I really don't get what's happening

**Comment by jzuhone** [comment]
Hmm. I was able to reproduce the failure locally.

**Comment by munkm** [comment]
It doesn't look like 3129 has the changes from main on it?

**Comment by jzuhone** [comment]
@neutrinoceros the previously failing Windows build on #3127 passed just now after I rebased it on `main`

**Comment by neutrinoceros** [comment]
Oh my bad, I don't really get what merging strategy is used in GH workflows. Thanks

**Pull request merged**
