### PR TITLE
DEPR: deprecate yt.testing.run_nose and wrap it in the yt namespace

### LINKED ISSUE #3771: pytest is now a hidden hard dependency
### Bug report

We now import `pytest` directly in `yt/testing.py`, but `pytest` is not yet listed as a hard dependency. This will cause a `ModuleNotFoundError` to be raised after installing yt until you install pytest manually.

I'm opening an issue rather than a PR because I don't know whether people would prefer to put the `pytest` import in a try block or make it a dependency.

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary
fix #3771
Opening as a draft because this will surely break CI until I refactor a couple imports

### CODE REVIEW

**Comment by matthewturk** [comment]
If we really want to have it not import at the top level, why not make `run_nose` be a thing here that just imports and runs inside the body of the function?

**Comment by neutrinoceros** [comment]
Depending how big of a patch my current approach leads to this could be a simpler alternative indeed. I may be naive in that I don't expect anyone downstream to rely on this function being at the top level. Am I ?

**Comment by matthewturk** [comment]
downstream maybe not, but people running tests, maybe yes.

**Comment by neutrinoceros** [comment]
Ok I'll just deprecate it then

**Comment by neutrinoceros** [comment]
I assume a deprecation without an alternative is fine ? Usually it isn't, but here I don't think there _is_ an alternative to redirect to.

**Comment by neutrinoceros** [comment]
The brutal approach didn't break any test apparently, this will make the task a lot easier.

**Review by brittonsmith — APPROVED** [review]

**Pull request merged**
