### PR TITLE
Fix yt-rockstar interface for Python 3

### PR DESCRIPTION
**Pull request by brittonsmith**
When ported over, this will fix Issue [19](https://github.com/yt-project/yt_astro_analysis/issues/18) of [yt_astro_analysis](https://github.com/yt-project/yt_astro_analysis).

Thanks to @Xarthisius for figuring out the string issue from the first commit.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
I believe the unit tests for rockstar that run on jenkins are disabled for python3. Those should be enabled before this gets merged.

**Comment by ngoldbaum** [comment]
@yt-fido test this please

**Comment by ngoldbaum** [comment]
@yt-fido test this please

**Comment by Xarthisius** [comment]
This PR needs the following to enable rockstar for py3:

```
diff --git a/tests/tests.yaml b/tests/tests.yaml
index f03916772..7f5b4d100 100644
--- a/tests/tests.yaml
+++ b/tests/tests.yaml
@@ -35,10 +35,10 @@ answer_tests:
   local_gizmo_002:
     - yt/frontends/gizmo/tests/test_outputs.py
 
-  local_halos_006:
-    - yt/analysis_modules/halo_analysis/tests/test_halo_finders.py  # [py2]
+  local_halos_007:
+    - yt/analysis_modules/halo_analysis/tests/test_halo_finders.py
     - yt/analysis_modules/halo_analysis/tests/test_halo_catalog.py
-    - yt/analysis_modules/halo_finding/tests/test_rockstar.py  # [py2]
+    - yt/analysis_modules/halo_finding/tests/test_rockstar.py
     - yt/frontends/ahf/tests/test_outputs.py
     - yt/frontends/owls_subfind/tests/test_outputs.py
     - yt/frontends/gadget_fof/tests/test_outputs.py:test_fields_g5
```

**Comment by brittonsmith** [comment]
Thanks, @Xarthisius!

**Comment by Xarthisius** [comment]
@yt-fido test this please

First run only generated answers, now let's check if they work ;)

**Pull request merged**
