### PR TITLE
Adds display_threshold option to StreamlineCallback

### PR DESCRIPTION
**Pull request by KiranEiden**
## PR Summary

Adds a feature to the StreamlineCallback that suppresses streamline segments where the color field fails to meet a given threshold. Also added a test for the callback.

**Note:** It is doubtful that the test ran properly - I may be having issues with my nose installation. If someone could make certain that the test executes and passes that would be appreciated.

The feature was discussed in issue #1921.

## PR Checklist

- [ ] Code passes flake8 checker
- [ ] New features are documented, with docstrings and narrative docs
- [ ] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by AshKelly** [comment]
It looks like the python3.6 AppVeyor build fail is unrelated to your work. The rest of your tests appear to have passed other than a python3.6 timeout which I've restarted.

**Comment by ngoldbaum** [comment]
Also if you want to describe a little bit more what issues you were having with nose and running the new tests you added I might be able to provide suggestions. In particular if you can make a gist with the full error message and traceback (if any) that you saw.

For what it's worth it looks like the test ran on jenkins and passed.

**Comment by KiranEiden** [comment]
Great, thank you! There were no error messages actually - the test just passed for everything, even in cases where I explicitly raised an error. The only thing that would cause it to fail was invalid python syntax. I can take a look at my nose setup; I'm not very familiar with the framework, so it may be a relatively straightforward issue to fix if I read the docs.

**Comment by ngoldbaum** [comment]
Could it have been that you didn't have the dataset specified by `requires_file` in the `test_data_dir`? You'd needed to have set `test_data_dir` in your yt config file and the dataset would need to be extracted there for the test to actually run locally on your machine.

**Comment by ngoldbaum** [comment]
http://yt-project.org/doc/reference/configuration.html#the-configuration-file

**Comment by KiranEiden** [comment]
That may be it, I'll try adding that to my config file.

**Comment by ngoldbaum** [comment]
Maybe @MatthewTurk, @chummels, or @jisuoqing  could take a look at this since you all are familiar with the plot callback code. If anyone else wants to do a review pass please feel free. I think we just need one more reviewer and this should be good to merge.

**Comment by ngoldbaum** [comment]
Thank you for your contribution! :fireworks: :tada: :shipit:

**Comment by KiranEiden** [comment]
You're welcome, thanks for your input!

**Pull request merged**
