### PR TITLE
Fix uninitialized values in bbox selection

### PR DESCRIPTION
**Pull request by Xarthisius**
This provided sane values for the reduced dimension while selecting region of a 2d mesh. Not a full and proper fix, but hopefully will make the annoying error on travis go away. It's similar to #2539 but I hope to merge this before we figure out a proper fix for 2D data.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
Could you elaborate what's the error you are fixing here, and what test(s) are hitting it ?

**Comment by Xarthisius** [comment]
> Could you elaborate what's the error you are fixing here, and what test(s) are hitting it ?

It's the error we've been occasionally seeing on travis w/ OSX for past few weeks.

**Comment by neutrinoceros** [comment]
Ah ! I reported it here https://github.com/yt-project/yt/issues/2861
And Matt already attempted a fix there https://github.com/yt-project/yt/pull/2842

So the randomness arise from the fact we check for uninitialised values ? Fascinating ! Do you see a reliable way to check this indeed fixes the problem ?

**Comment by Xarthisius** [comment]
> Ah ! I reported it here #2861
> And Matt already attempted a fix there #2842
> 
> So the randomness arises from the fact we check for uninitialised values ? Fascinating ! Do you see a reliable way to check this indeed fixes the problem ?

The randomness was caused by the fact that we used a random garbage in `select_bbox` to decide whether a region overlaps 2d points or not. I don't have a reliable way of verifying that this fixes #2861. I was never able to reproduce it on linux, but sounds like you can!

**Comment by neutrinoceros** [comment]
Yeah I can try on my Mac.
I'm now running this horrible loop on master to see _if_ I can reproduce with a somewhat relevant probability.
```bash
for i in {1..100} ; do pytest yt/frontends/stream/tests/test_stream_unstructured.py::test_multi_field; done
```

**Comment by neutrinoceros** [comment]
Oh sorry I just found out that my follow up never reached GitHub... anyway none of my 100 tries failed, so it looks like I was extremely lucky the first time I tried.

**Review by neutrinoceros — APPROVED** [review]

**Pull request merged**
