### PR TITLE
MNT: Add explicit support for Python 3.10 on windows

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

Complements #3543.
I've been testing this on my fork and I believe it is now ready.

I was also able to remove the pinning added in #3298 since [upstream issue](https://github.com/SciTools/cartopy/issues/1140) was resolved.
As a temporary measure I'm conditionally skipping the one test that fails with cartopy 0.20 (reported as https://github.com/yt-project/yt/issues/3705) because I don't think it is bad enough to prevent us from testing on windows + Python 3.10, the issue is linked in the test code. I assume the regression is actually upstream and should be reported there.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
I don't yet understand why this the test isn't skipped on Jenkins, so I'll switch this to draft for now and remove it from the 4.0.2 milestone

**Comment by neutrinoceros** [comment]
Adding the backport label instead of the milestone to signal that it'd be cool to backport this on merge but it's not a blocker for the release

**Comment by neutrinoceros** [comment]
Moving this to draft for now because it seems possible that a solution could be found quickly to avoid skipping the failing test.

**Comment by neutrinoceros** [comment]
rebased on top of #3708

**Comment by matthewturk** [comment]
This is back in draft -- should it be marked ready?

**Comment by neutrinoceros** [comment]
the only reason this is in draft mode is because it's based on #3708
Now if you'd like, feel free to merge this directly, in which case I'll close and delete the other branch

**Comment by neutrinoceros** [comment]
Failures are unrelated. I'll mark it as ready for review when CI is stabilised

**Review by matthewturk — APPROVED** [review]

**Pull request merged**
