### PR TITLE
Remove analysis_modules

### PR DESCRIPTION
**Pull request by brittonsmith**
## PR Summary

This removes the deprecated functionality in `analysis_modules` and updates the associated documentation. I've renamed the analysis modules section in the documentation as Domain-Specific Analysis and added discussions of `yt_astro_analysis`, `yt_attic`, and the yt Extensions packages. I tried to group distinct tasks into single commits, so have a look at the commit list to see what all has been done.

In conjunction with this, I've opened a [pull request to yt_attic](https://github.com/yt-project/yt_attic/pull/2) to add halo mass function testing machinery that was removed here.

I'm open to discussion on doing any of this differently or putting things back. Also, as yt 3.5 was only released a couple weeks ago, this can wait if it's too soon.

## PR Checklist

- [ ] Code passes flake8 checker
- [ ] New features are documented, with docstrings and narrative docs
- [ ] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by chummels** [comment]
The diff is too big, so I couldn't find what happens when someone tries to use any of the deprecated/removed functionality.  Does it direct them to yt_astro_analysis?  

I forget how long we've had that stuff deprecated in here, but it seems like it's only been recently?  It might make sense to hold off on removing this content for a bit since we just released the first stable release of yt_astro_analysis.  Maybe just until yt-4.0 goes into dev?  I dunno.

**Comment by brittonsmith** [comment]
@Xarthisius, is it possible to install yt_astro_analysis and trident on the test machine?

**Comment by brittonsmith** [comment]
Most of the diff is just removing files, imports, and taking out rockstar installation from the install script. The main change to look at is [here](https://github.com/yt-project/yt/pull/2081/files#diff-cf7fac3f0f3c2bcd92b9cccb287f7645), which is the rewrite of the analysis modules docs page.

The main reason I'd like to do this sooner rather than later is that I don't want to have to maintain duplicate codebases, which is a real pain. I think there is an expectation that bugfixes and updates be applied to both yt and yt_astro_analysis for as long as the relevant code exists in both. Either that, or there is confusion about where things should go and what is getting updated. We already have one PR to yt_astro_analysis that will add new functionality and I plan on submitting some others soon as well. Policy-wise, I think it's fine to deprecate in one release and remove in the next. yt 4.0 is probably a little ways off. I don't think we should wait that long.

**Comment by ngoldbaum** [comment]
What sort of error do you get when you try to do a removed import? Can we at least make the error message suggest installing yt_astro_analysis instead of being an opaque ImportError.

@chummels in yt 3.5.0 all of these have been deprecated and will generate an annoying warning if you try to import them. I think removing them for yt 4.0 is the way to go.

It may be less disruptive and easier to manage in terms of the testing infrastructure if you do this on the yt-4.0 branch. That way we'll be able to delay worrying about updating the jenkins test infrastructure until when we're ready to merge the yt-4.0 branch with master.

**Comment by Xarthisius** [comment]
> @Xarthisius, is it possible to install yt_astro_analysis and trident on the test machine?

Done!

**Comment by brittonsmith** [comment]
@Xarthisius, thanks!

@ngoldbaum, I can replace the `api.py` files in each `analysis_modules` subdirectory and have it raise an informative exception. Would that work? I'll have to do each one individually since we don't use a general `analysis_modules.api`, but I suppose that's ok. I will also reissue this to the `yt-4.0` branch.

**Comment by chummels** [comment]
Yeah, your plans are exactly what I was trying to describe in my earlier comment.  Put it in the yt-4.0 branch and have there be an informative error message. :)

**Comment by brittonsmith** [comment]
I've added a `YTModuleRemoved` exception that gets raised in each module's `api.py`. I know the diff looks intimidating, but one can scroll quite quickly over the removed files and just look at the changes, of which there are relatively few. This PR is off the `yt-4.0` branch as well.

I think it would be a good idea to cherry-pick just the changes to the analysis_module docs page and move them to `master` as soon as possible since it can give people a heads-up from the docs and prevent them from using code that isn't being updated anymore. Anyone have thoughts about this in particular?

**Comment by brittonsmith** [comment]
@yt-fido test this please

**Comment by ngoldbaum** [comment]
I'm going to close and re-open the PR to re-trigger testing.

**Comment by ngoldbaum** [comment]
Oh wait that won't matter until I merge with master again, sorry for being slow to get to this. I will do that merge right now.

**Comment by brittonsmith** [comment]
Looks like there is one failure in the Mac OS unit tests having to do with saving/reloading an octree. Is this popping up anywhere else?

**Comment by MatthewTurk** [comment]
The error is very weird:

```
======================================================================
ERROR: This builds an octree, writes to file, reloads and ensure that the reloaded
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/travis/build/yt-project/yt/yt/data_objects/tests/test_octree.py", line 43, in test_saving_loading
    octree = ds.octree(n_ref=1)
  File "/Users/travis/build/yt-project/yt/yt/data_objects/construction_data_containers.py", line 2187, in __init__
    self.tree
  File "/Users/travis/build/yt-project/yt/yt/data_objects/construction_data_containers.py", line 2240, in tree
    self._generate_tree(fname)
  File "/Users/travis/build/yt-project/yt/yt/data_objects/construction_data_containers.py", line 2217, in _generate_tree
    self._octree.save(fname)
  File "yt/utilities/lib/cyoctree.pyx", line 533, in yt.utilities.lib.cyoctree.CyOctree.save
  File "yt/utilities/lib/cyoctree.pyx", line 541, in yt.utilities.lib.cyoctree.CyOctree.save
struct.error: argument out of range
```

I feel like this would or should show up elsewhere, if it were really an issue.

**Comment by brittonsmith** [comment]
@ngoldbaum, I restarted this test yesterday and it's now passing. There is probably a real issue, but it looks like this might be a slightly flaky test.

**Comment by ngoldbaum** [comment]
That's good to hear! In that case I doubt it has anything to do with this.

**Pull request merged**
