### PR TITLE
DEP: drop support for CPython 3.8

### LINKED ISSUE #4302: TST: how to drop CPython 3.8 ?
⚠️ **Disclaimer**
_I am not proposing to drop support for CPython 3.8 **now**. I just want to point out why this will be difficult because it'll need to happen eventually, and the sooner we prepare for it, the easier it'll be._

## Timeline: when can we expect to drop it ?
To ensure the total number of versions we support at any given time stays bounded, and [as long as new versions of CPython keep dropping yearly](https://peps.python.org/pep-0602/), we need to drop 1 version per year to keep up.
Following this motivation, the drop typically happens around the same time of year that a new version is released (see #2917 and #4101 for history), so the typical expectation would be that we do this around October 2023.

Were we to closely follow [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) (which so far we have not, so it shouldn't be expected from us), it could be done as soon as April 2023.

## Problem
CPython 3.8 is our oldest supported version at the moment, and is currently used for testing on Jenkins. This means we need to upgrade the Python runtime on CI _before_ we are allowed to bump `requires-python` in `pyproject.toml`. I expect this may be difficult and/or time consuming because all our answer-tests and image tests that rely on actual simulation data are run there, and many (not sure exactly which) of them use `pickle` for reference storage. Now, Python objects saved to disk with `pickle` are _not_ guaranteed to be interoperable with different versions of the `python` runtime, so it is possible that some references cannot be salvaged and must be regenerated from scratch (then validated manually ?).

To make things worse, the most we  can upgrade these jobs is to Python 3.9, because newer versions (3.10+) are just not compatible with the test framework used for these tests (`nose`).

It follows that dropping 3.9 (around October 2024 ?) will not be possible without leaving some of our test suite behind unless we can finish the migration to pytest before then, but that's an other story (sort of).

So I'd like to open the discussion as soon as possible, mostly with @Xarthisius who's still in the delicate position of being our only Jenkins maintainer, and @matthewturk, who's most aware of the issues we're having with transition to pytest.

I *think* (maybe naively ?) that we can afford doing only minimal manual validation for answers on Python 3.9 (the code base has been extensively tested on Python 3.9 for years now), which would make the process easier.
The better solution of course would be to push for the migration to `pytest` but that seems like an unreasonable amount of work for this timeline, given the history of this project.

Thoughts ?

### PR DESCRIPTION
**Pull request by neutrinoceros**
Following [my recent email](https://mail.python.org/archives/list/yt-dev@python.org/thread/F36HH6UX27KT5Z37R3WKSZ2FRP5BMTVG/), closes #4302

### CODE REVIEW

**Comment by neutrinoceros** [comment]
@fido test this please

**Comment by neutrinoceros** [comment]
@yt-fido test this please

**Comment by neutrinoceros** [comment]
@yt-fido test this please

**Comment by neutrinoceros** [comment]
@yt-fido test this please

**Comment by neutrinoceros** [comment]
@yt-fido test this please

**Comment by neutrinoceros** [comment]
@yt-fido test this please

**Comment by neutrinoceros** [comment]
@yt-fido test this please

**Review by cphyc — APPROVED** [review]
LGTM, thanks for the hard work! For reference, could you comment on the upgrades required to make `nose` work?

**Comment by neutrinoceros** [comment]
@cphyc As far as I know nose is just patched as follow
```
python3.10 -m pip install nose nose-exclude
find .venv/lib/python*/site-packages/nose -name "*.py" -exec sed -i -e 's/collections.Callable/collections.abc.Callable/g' {} \;
```

see https://github.com/yt-project/yt/issues/4302#issuecomment-1696143424
Maybe @Xarthisius has more insight on this.

**Comment by Xarthisius** [comment]
> @cphyc As far as I know nose is just patched as follow
> 
> ```
> python3.10 -m pip install nose nose-exclude
> find .venv/lib/python*/site-packages/nose -name "*.py" -exec sed -i -e 's/collections.Callable/collections.abc.Callable/g' {} \;
> ```
> 
> see [#4302 (comment)](https://github.com/yt-project/yt/issues/4302#issuecomment-1696143424) Maybe @Xarthisius has more insight on this.

That's everything I did.

**Pull request merged**
