### PR TITLE
MNT: drop useless workflow

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

This workflow, while pretty harmless, is also very much useless: it hasn't caught a single problem in ~4.5k runs (over the course ~3 yrs).

### CODE REVIEW

**Comment by matthewturk** [comment]
If I remember correctly, this was part of a couple where we checked for code smells, right?  I mean, I'm OK with dropping it, but is it a big deal time-wise?

**Comment by neutrinoceros** [comment]
It takes about a couple seconds on each PR, so no, it's not costly, but IMO it still takes too much space for what little value (0) it actually provides.

**Comment by matthewturk** [comment]
I'm OK with dropping it, to be clear.

**Review by matthewturk — APPROVED** [review]

**Comment by matthewturk** [comment]
can't wait for my forthcoming PR that imports all our import-on-demand modules sneakily at the top level

**Pull request merged**
