### PR TITLE
[WIP] Use tox for managing environments

### PR DESCRIPTION
**Pull request by matthewturk**
After #2513, #2450 and a couple others, I'd like to propose that we explore simplifying our usage of travis.  Instead of having a large `.travis.yml` file, I think simplifying to use `tox.ini` would be prudent.

This is a rough draft of a very simple tox ini file.  Using it with travis would look something like what's outlined in [this blog post](https://medium.com/@alejandrodnm/testing-against-multiple-python-versions-with-tox-9c68799c7880), and would reduce the travis config file in size -- and probably help us with migrating to something like Circle CI or Github Actions in the future.

This PR will be a staging ground for replicating the travis configuration in tox.

### CODE REVIEW

**Comment by matthewturk** [comment]
(It may also end up being the case that this gets us nothing, in which case, nothing ventured, nothing lost.)

**Comment by neutrinoceros** [comment]
I note that we can avoid the extra file now that we have a pyproject.toml
(https://tox.readthedocs.io/en/latest/example/basic.html)

**Comment by matthewturk** [comment]
I kind of felt ambivalent about this, too. I am not sure it solves anything
for us but maybe I'm wrong.

**Comment by neutrinoceros** [comment]
well if the goal is purely to simplify our usage of Travis I think the solution might just be to migrate to GH workflows for unit tests. And from what I understand tox doesn't add anything there.

**Comment by matthewturk** [comment]
Sounds good to me.  Feel free to close it, unless there's a good reason not
to!

**Comment by neutrinoceros** [comment]
I think it's ok to close for now :)

**Pull request closed without merging**
