### PR TITLE
Flynt+flake+isort doc

### PR DESCRIPTION
**Pull request by cphyc**
## PR Summary

Apply fint to the doc and fix a couple of isort/flake8 issues there.
On a side note, there are many files that depend on `hg` which we haven't been using for years now. Should we clean them up?

### CODE REVIEW

**Comment by neutrinoceros** [comment]
Thanks for doing this ! Could you also add `doc` to the targeted locations in the precommit hooks and gh workflow checks ?

**Comment by neutrinoceros** [comment]
adding the dead code label because of 3171ebc733b98256e95f9f8801a8d100854a1b6a

**Review by neutrinoceros — APPROVED** [review]
Thank you for doing this, I carefully went over it and I approve fully.

**Comment by neutrinoceros** [comment]
> On a side note, there are many files that depend on hg which we haven't been using for years now. Should we clean them up?

I think @matthewturk could answer this question !

**Review by matthewturk — APPROVED** [review]

**Comment by matthewturk** [comment]
I'm OK with removing the hg-related files and support tools, but maybe in a separate PR.

**Pull request merged**
