### PR TITLE
BUG: fix late-binding errors in closures

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

Follow up to #3994
Upgrade flake8-bugbear and fix newly detected gotchas: late-binding errors in closures

If, like me, you didn't know about this problem, here's a helpful blog post to explain what the problem is and its solution(s)
https://docs.python-guide.org/writing/gotchas/#late-binding-closures

Content:

- MNT: manually upgrade flake8-bugbear
- BUG: fix late-binding errors in closures, detected with flake8-bugbear (B023)
- MNT: add noqas to flase positives (B023) in generator based tests

### CODE REVIEW

**Comment by neutrinoceros** [comment]
Turns out most errors are in frontend-specific code

**Comment by matthewturk** [comment]
Do we think these actually resulted in errors?

**Comment by neutrinoceros** [comment]
I am honestly not sure, but it seems likely, and fragile.

**Comment by matthewturk** [comment]
OK, I think the Gadget ones likely did not result in problems (although they should be fixed, as you have) but the RAMSES ones do seem like they may have caused issues *in the specific case* that there were multiple field types being read simultaneously.

**Comment by neutrinoceros** [comment]
Yes, with just one field type the bug should be invisible

**Review by matthewturk — APPROVED** [review]

**Pull request merged**
