### PR TITLE
load_sample: fix sample data registry for 7 datasets

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

This is complementary with https://github.com/yt-project/website/pull/103 and should fix load_sample for 6 more datasets that were not following the dominant naming conventions in tarballs

this will also need to be followed by a systematic cleanup akin to #3317

### CODE REVIEW

**Comment by cphyc** [comment]
Why are the hashes changing?

**Comment by neutrinoceros** [comment]
Because the original tarballs didn't follow the de facto rule implemented but every other data sample: files need to unfold to a directory with the same name as the tarball (minus the .tar.gz extension), which also matches the "key" that's passed to load_sample

**Comment by neutrinoceros** [comment]
this will very likely be superseded by #3366 
Switching to draft for now, but I except this will end up being closed rather than merged.

**Comment by neutrinoceros** [comment]
Probably, but I'd like to keep it around for now if you don't mind.

**Comment by neutrinoceros** [comment]
closing this to clear the backlog as much as possible.
#3366 is the only change we need, and the one performed here can be done without a PR when #3366 is completed

**Pull request closed without merging**
