### PR TITLE
Backport PR #3494 on branch yt-4.0.x (MNT: migrate away from packaging.version.parse)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #3494: MNT: migrate away from packaging.version.parse

### CODE REVIEW

**Comment by neutrinoceros** [comment]
Note to reviewers: while not strictly a bug fix, backporting this will enable automated backports for the following, otherwise conflicting PRs:
- #3556
- #3565

**Comment by munkm** [comment]
I thought individual backports were on pause until a solution to bulk them in a single PR like @Xarthisius suggested was found?

**Comment by neutrinoceros** [comment]
I don't recall us agreeing on a strategy, and no one has proposed to help after 3 weeks.

We cannot bulk such a large number of PRs in a reproducible fashion because there were originally many conflict and order sensitive operations.
Bulking would be more error prone and it wouldn't be nearly as trivial to review as an identical patch.

I get it, people are busy and notifications are annoying, but we are now extremely close to completion with the existing strategy. Can we please finish this before it turns unmanageable again ?

**Comment by munkm** [comment]
If all bugfixes are backported in a single PR with a separate commit for each backport, how would that have an issue with order sensitivity if CI is only tested on the last commit? That's what Kacper was saying.

**Comment by neutrinoceros** [comment]
I'll fully admit that I did not understand this was the proposed alternative. Well, I can to this for this one + the whole list here https://github.com/yt-project/yt/pulls?q=is%3Apr+label%3A%22Still+Needs+Manual+Backport%22+is%3Aclosed+
which would complete the list in the 4.0.2 meta issue.

**Comment by neutrinoceros** [comment]
done in #3651, which now supersedes this PR.

**Pull request closed without merging**
