### PR TITLE
yt-4.0 normalization fix

### PR DESCRIPTION
**Pull request by AshKelly**
## PR Summary

Fixed normalization of some pixelization routines with the addition of two utility functions to normalize

The plots with the fix:
with_fix

The plots without the fix:
without_fix

NOTE: These fixes may break the tests, I'm not 100% sure.

## PR Checklist

- [x] Code passes flake8 checker
- **NA** New features are documented, with docstrings and narrative docs
- **NA** Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
So if I understand correctly, we're now always doing normalization, is that correct? Is `use_normalization` still useful to keep around even though we've hard-coded it to `False`? Maybe it would be less confusing to remove it?

**Comment by AshKelly** [comment]
Yes, all of them are getting normalized after the entire deposition.

Hm, well I guess we don't **need** it now - but I'd have to go through and check everywhere we have used it where we have done the deposition in a single iteration that I use the utility function to normalize, that is probably more maintainable.

If a user wanted to view a plot without a normalization, we don't currently have an API to support that. Do you think that should also be a dataset property?

**Comment by ngoldbaum** [comment]
That would probably be the most natural way to expose it, yeah, something like `ds.use_sph_normalization = True`.

**Comment by JBorrow** [comment]
Just to chime in -- this looks a lot better now! I was concerned yesterday about the circles that spuriously appeared in the old version. Good job @AshKelly!

**Comment by AshKelly** [comment]
not sure why this failed on xcode, but I think this ready to merge

**Comment by ngoldbaum** [comment]
The Mac failure is a timeout, not your fault, happens sometimes.

**Pull request merged**
