### PR TITLE
[BUGFIX] Update con_args parsing for current h5py

### PR DESCRIPTION
**Pull request by matthewturk**
This fixes the ytdata tests for me.  What was happening:

```
f.attrs.get("con_args")
```

was returning

```
array([b'axis', b'coord'], dtype='|S5')
```

So when this was getting `eval`'d, it was trying to eval `axiscoord` (or
`normalcenter`) which didn't exist.  So instead let's pull the
individual values, decode them, and assign them.

### CODE REVIEW

**Comment by munkm** [comment]
One of the yt data tests is still failing on Jenkins on this PR. Is that not happening locally for you?

**Comment by matthewturk** [comment]
Nope, it passes here.

**Comment by Xarthisius** [comment]
Code to reproduce error from Jenkins:

```python
import yt

dnz = "DeeplyNestedZoom/DD0025/data0025"
ds = yt.load(dnz)
center = [0.4915073260199302, 0.5052605316800006, 0.4905805557500548]
plot = yt.SlicePlot(ds, 'z', 'density', width=(0.001, 'pc'), center=center)
full_fn = "ytdata_test/slice.h5"
ds_slice = yt.load(full_fn)
```

**Comment by Xarthisius** [comment]
After some digging I reduced it even further:

```
import yt

dnz = "DeeplyNestedZoom/DD0025/data0025"
ds = yt.load(dnz)
(ds.units.code_mass / ds.units.code_length).latex_representation()
full_fn = "ytdata_test/slice.h5"
ds_slice = yt.load(full_fn)
```

It's `.latex_representation` that cause unit system to propagate.

**Comment by matthewturk** [comment]
With the new `unyt` is this okay to merge?

**Comment by Xarthisius** [comment]
> With the new `unyt` is this okay to merge?

Let's find out.

**Pull request merged**
