### PR TITLE
DEPR: deprecation cycle (4.0 -> 4.1)

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

This removes all code that was targeted for removal for yt 4.1, and associated documentation, with the notable exception of ambiguous fields. This part is left to be solved with #3416 (also included in the 4.1 milestone).

### CODE REVIEW

**Comment by neutrinoceros** [comment]
(adding the "refactor" label just to satisfy the mergeable bot)

**Comment by neutrinoceros** [comment]
@yt-fido test this please

**Comment by neutrinoceros** [comment]
@matthewturk do you want to issue a warning on the mailing list ?

**Comment by chummels** [comment]
I can try to look at this in the next week to add these deprecated/removed features to the yt4differences docs page, but honestly, I'm not super comfortable with this being merged until then.  That page is explicitly written for users on how to update their scripts to yt4 to avoid breakages, so it really deserves to be updated with information about these functions that are being removed from the code which will cause script breakages.

**Comment by neutrinoceros** [comment]
Arguably such updates would need to be backported to the 4.0.x branch. Otherwise it won't reach the stable documentation before it's too late (4.1). The present PR however has to stay on the 4.1 branch (current main). If only for this reason, I'd like to suggest that the docs be updated in a separate PR, regardless of the final merging order.

**Comment by neutrinoceros** [comment]
Following our discussion on Slack, I've repurposed #3451 and targeted it for the 4.0.2 release. Now if I open an issue to remind ourself to document these removals in time for the 4.1 release, can we get this forward @chummels ?

**Comment by chummels** [comment]
I know we keep going back and forth here, but I don't understand why we don't just write the documentation now before these features are removed?  If someone is using the dev version of the code, and this PR gets merged, their scripts will fail and they'll want to figure out why, and likely go to the docs to figure it out.  Why wait to document this change until the release of 4.1?  Can you just include the relevant documentation before merging the code?

**Comment by neutrinoceros** [comment]
I'm working to document them _right now_, but it needs to be done in a separate PR because the docs need to be back ported to the stable branch while the present PR needs to stay on the dev branch only

**Comment by neutrinoceros** [comment]
done in #3665

**Comment by neutrinoceros** [comment]
@chummels can you merge this now ?

**Review by chummels — APPROVED** [review]
Thanks for documenting this.

**Pull request merged**
