### PR TITLE
Documentation for VolumeContainer and related function.

### PR DESCRIPTION
**Pull request by cgyurgyik**
## PR Summary

Adds documentation for  the struct ```VolumeContainer``` and ```vc_index```.

## PR Checklist

- [x] Code passes flake8 checker
- [x] New features are documented, with docstrings and narrative docs
- [x] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by cgyurgyik** [comment]
> Hi @cgyurgyik! Thanks for documenting these functions. I think it'll be much appreciated by anybody else combing through this code!!!
> 
> I noticed your other PR was merged without this comment, but would you mind moving the commenting documentation to be inside the function definition (and indent it accordingly)? I think that'll make it more obvious what the comments are documenting.

So you're saying something along the lines:
```
cdef inline int vc_index(VolumeContainer *vc, int i, int j, int k):
BEGIN DOCUMENTATION
END DOCUMENTATION
    return (i*vc.dims[1]+j)*vc.dims[2]+k
```
?

**Comment by munkm** [comment]
Yep, exactly!

**Comment by cgyurgyik** [comment]
> Yep, exactly!

Done.

**Comment by cgyurgyik** [comment]
Hi @munkm , is there a reason my documentation is failing the codecov/project check?

**Comment by munkm** [comment]
I think it's an error! Don't worry about it.

**Pull request merged**
