### PR TITLE
remove usage of pyplot for annotated volume rendering

### PR DESCRIPTION
**Pull request by ngoldbaum**
Since #1793 the travis tests are intermittently failing in the call to save_annotated because of missing `DISPLAY` environment variable.

We don't really need pyplot at all and in principle real users would hit this error on e.g. a cluster or any other headless SSH session.

I've gone ahead and removed the usages of pyplot in `save_annotated` and functions called by `save_annotated`. This does make the resulting image change appearance slightly. Here's the output of `vol_annotated.py` in the documentation

old:

new:

Note how in the old version the text annotation doesn't actually appear because it's "off the page". I think the new format looks a bit cleaner. If people disagree I can certainly try to make the images match a bit more.

### CODE REVIEW

**Comment by zingale** [comment]
The images are different sizes though, and we really want to be able to control the final output image size if we are rendering for a specific image format (e.g. 1080p).

**Comment by zingale** [comment]
is it possible to leave the old functionality in there in addition to the new?

**Comment by ngoldbaum** [comment]
> is it possible to leave the old functionality in there in addition to the new?

The functionality is the same. I didn't realize that the image resolution was part of the intended output. I think I can retain that. Do you want pyplot for anything else?

**Comment by zingale** [comment]
works great.  Thx.

**Pull request merged**
