### PR TITLE
TYP: setup basic type checking and fix existing type errors

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary
This is a work in progress in support to the ongoing effort to add more type hints to the code base.
Goals:
- [x] enable continuous type checking with mypy
- [x] fix any existing errors (type inconsistencies) with minimal changes
- [ ] add optional yt dependencies to Mypy workflow env and repeat (this may be left to a follow up PR)

### CODE REVIEW

**Comment by neutrinoceros** [comment]
almost there. Now praying I didn't break anything in my rebasing. If all goes well I'll remove the draft status later today.

**Review by cphyc — DISMISSED** [review]
LGTM now, now that the tests pass!

Thanks so much for the thorough work

**Comment by matthewturk** [comment]
@neutrinoceros Do you think we should iterate more on the design, or review/merge as-is?

**Comment by neutrinoceros** [comment]
I consider it mature for reviewing. I see that there are conflicts however so I'm going to rebase + force push

**Comment by neutrinoceros** [comment]
ah, of course I'm now catching up some new typing errors from newly merged PRs, *and* I see another conflict. Switching to draft for now, will reopen after I'm done fixing this

**Comment by neutrinoceros** [comment]
I'm very confused to see new errors pop in, I'm also noting that the ones I get locally don't exactly match the logs I get on GitHub, even though I'm explicitly pinning Mypy's version. Will need to come back to this later

**Comment by neutrinoceros** [comment]
pre-commit.ci autofix

**Comment by neutrinoceros** [comment]
Noe to reviewers: I got this mergeable again, but needed to rebase to resolve some conflicts. Everything that's changed since the last time you reviewed is found in small, isolated commits, so I hope it's still manageable.
Also note that, as most sweeping changes, this has the potential of becoming unmanageable on my end very quickly, so I'd appreciate if we can consider moving this forward as soon as possible. Thanks

**Comment by matthewturk** [comment]
I think moving it forward is a good idea.  And honestly, as long as
there are no functional changes, I think reviewing the top-level
restructurings is good enough, and the type annotations themselves do
not necessarily require detailed review.

**Comment by neutrinoceros** [comment]
There are some *tiny* functional changes though, almost exclusively in input validation routines, where I raised some type degeneracies detected by mypy. Other than that, there should be none

**Comment by neutrinoceros** [comment]
forced-pushed again to resolve conflicts. Again, the bulk of the diff is contained in the unchanged (conflicts aside) first commit. I didn't need any new commit this time, phew

**Comment by matthewturk** [comment]
I personally think that this is good to go.

**Review by matthewturk — APPROVED** [review]

**Comment by neutrinoceros** [comment]
@cphyc, sorry I know you're busy, but could you give this the final review since you've already done most of it ?

**Review by cphyc — APPROVED** [review]

**Pull request merged**
