### PR TITLE
Add mode kwarg to h5py.File calls

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

This is built on top of #2594 as per suggested there.

for reference this change was performed automatically with the following script:
```python
import re
from pathlib import Path

yt_dir = Path(__file__).parent.parent

exp = re.compile("""h5py\.File\([^,]+,\s*['"]""")

def repl_exp(matchobj):
    core = matchobj.group(0)[:-1].rstrip()
    sep = matchobj.group(0)[-1]
    return f"{core} mode={sep}"

for file in yt_dir.glob("**/*.py"):
    with open(file, mode="r") as fileobj:
        text = fileobj.read()

    if (new_text := exp.sub(repl_exp, text)) == text:
        continue

    with open(file, mode="w") as fileobj:
        fileobj.write(new_text)
```

### CODE REVIEW

**Comment by munkm** [comment]
Awesome! I'm going to merge the other PR now and then once the tests pass we can merge this. Thank you @neutrinoceros.

**Comment by neutrinoceros** [comment]
propagated to documentation files and rebased onto master !

**Comment by neutrinoceros** [comment]
Welp, the docs build failed with a time out. Can you please restart the build @munkm ?

**Comment by matthewturk** [comment]
doc builds aren't quite working right now -- this shouldn't be a blocker.

**Pull request merged**
