### PR TITLE
Fix iterator in Python 3.7

### LINKED ISSUE #2264: Dynamic parallel objects StopIteration error in Python 3.7
### Bug report

**Bug summary**

Dynamic parallel objects would result in [`StopIteration` error stemming from a Python 3.7 new behavior](https://stackoverflow.com/a/51701040/10892982).

**Code for reproduction**

Given `test.py`:
```python
import yt
yt.enable_parallelism()

for x in yt.parallel_objects(range(10), dynamic=True):
    print(x)
```

Run:
```console
$ mpirun python test.py
```

**Actual outcome**

```console
...
  File "test.py", line 4, in <module>
    for x in yt.parallel_objects(range(10), dynamic=True):
  File "/Users/qobilidop/work/rse/yt-project/yt-dev/yt/utilities/parallel_tools/parallel_analysis_interface.py", line 481, in parallel_objects
    storage=storage):
  File "/Users/qobilidop/work/rse/yt-project/yt-dev/yt/utilities/parallel_tools/task_queue.py", line 174, in dynamic_parallel_objects
    for task in my_q:
P001 yt : [ERROR    ] 2019-05-27 12:40:34,817 RuntimeError: generator raised StopIteration
...
```

**Expected outcome**

No error.

**Version Information**

  * Python Version: 3.7
  * yt version: master branch (3.6.dev0)

### PR DESCRIPTION
**Pull request by qobilidop**
## PR Summary

Resolves #2264.

## PR Checklist

- [x] Code passes flake8 checker
- [ ] Adds a test for any bugs fixed

### CODE REVIEW

**Comment by qobilidop** [comment]
I don't know where and how to test this when MPI is involved.

**Comment by qobilidop** [comment]
@yt-fido test this please

**Comment by Xarthisius** [comment]
@yt-fido test this please

**Comment by qobilidop** [comment]
@yt-fido test this please

**Comment by brittonsmith** [comment]
@yt-fido test this please

**Pull request merged**
