### PR TITLE
doc: add pypi versions badge

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

This should only be merged a short time ahead of the 4.0 release in order to be relevant.
Currently, this looks like this:
Screen Shot 2020-11-23 at 22 37 17

### CODE REVIEW

**Review by munkm — APPROVED** [review]
+1 to adding this badge. I agree that it should be merged around the 4.0 release (so that the outdated support info isn't advertised on our gh page) but I don't think it specifically matters if it's included in the release. Based on yt-project/yt#2528 and others that change our setup.py the badge should be updating with whatever is there. We should make sure that setup.py doesn't include python 3.5 in the release though. 

I think maybe the badge should come after the mailing list badges, since the badges afterwards are about the code/build?

**Comment by neutrinoceros** [comment]
>  I don't think it specifically matters if it's included in the release

absolutely, I merely put the label so that we don't forget about it when the release is done !

> I think maybe the badge should come after the mailing list badges, since the badges afterwards are about the code/build?

sure thing

**Comment by neutrinoceros** [comment]
Note: with this many badges, they don't fit on a single line anymore so here's how I'm rearranging them thematically (code properties/stability VS useful links). I'm open to suggestions if that's unsatisfactory for any reason.
Screen Shot 2020-11-24 at 23 34 10

**Comment by munkm** [comment]
I think this looks great!

**Comment by matthewturk** [comment]
We could ditch the data hub one and the two user list ones.

**Comment by neutrinoceros** [comment]
> We could ditch the data hub one and the two mailing list ones.

why ? IMO having 2 lines of badges is better than reducing the discoverability of these. Maybe you'd like to replace them with a slack button or something ?

**Comment by neutrinoceros** [comment]
Resolved in #3058

**Pull request closed without merging**
