### PR TITLE
Pytest unittest

### PR DESCRIPTION
**Pull request by jcoughlin11**
## PR Summary

This is the second in a series of pull requests meant to transition yt from the nose testing framework to the pytest testing framework. Specifically, this pr addresses getting the unit tests working with pytest. So far, this has required only one change made to the requires_module meta-wrapper. Additionally, a pytest.ini file has been added solely for the purpose of ignoring all answer tests listed in tests.yaml. These tests can (and will) be removed from this file (eventually leading to the removal of the file itself) as their pytest-compatible versions are added to the code.
## PR Checklist

- [x] Code passes flake8 checker
- [ ] New features are documented, with docstrings and narrative docs
- [x] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by matthewturk** [comment]
@Xarthisius If you think this is ready to go, and @jcoughlin11 agrees, at the PR triage we said we thought it should go in.

**Comment by jcoughlin11** [comment]
Yeah, it should be good to go!

**Comment by jcoughlin11** [comment]
Just wondering why the py 3.8 build was aborted?

**Comment by munkm** [comment]
I think Kacper is still working on getting the updated tests on Jenkins working.

**Comment by jcoughlin11** [comment]
@munkm  Gotcha, thanks!

**Comment by matthewturk** [comment]
@yt-fido test this please

**Pull request merged**
