### PR TITLE
Add "minimal sphere" implementation

### PR DESCRIPTION
**Pull request by cphyc**
## PR Summary

This PR adds a "minimum sphere" function that creates a minimum bounding sphere around a set of points. This is useful to get the smallest spherical volume that contains e.g. some particles.

## PR Checklist

- [x] Code passes flake8 checker
- [x] New features are documented, with docstrings and narrative docs
- [x] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by cphyc** [comment]
The miniball package can be found here https://github.com/weddige/miniball ; it is a bit clumsy to install for now as no pip package exists. Maybe we could include it in `yt/extern` if the license is ok?

**Comment by matthewturk** [comment]
@cphyc If you add `miniball` to the requirements and the testing requirements, that should be enough to get the tests going.

**Comment by cphyc** [comment]
@matthewturk will do once my dissertation is written and shipped!

**Comment by cphyc** [comment]
@matthewturk unfortunately, the `miniball` package cannot be added to the requirements as it is not available on pip. I am issuing a PR on https://github.com/weddige/miniball to get it packaged though.

**Comment by cphyc** [comment]
For reference, I have updated the package to pypi and submitted a PR to the initial project (https://github.com/weddige/miniball/pull/5) to hand it back to the original author.
Meanwhile, the package is available as `MiniballCpp` on pypi (https://pypi.org/project/MiniballCpp/).

**Comment by cphyc** [comment]
For now, the tests are skipped with Python 2 as the miniball package is not compatible with it.
I would also be fine to remove this machinery and rebase on yt-4.0, following @jzuhone suggestion. What's your opinion @matthewturk @brittonsmith @jzuhone?

**Comment by brittonsmith** [comment]
@cphyc, I think either is fine. Getting yt-4.0 merged into master is an ongoing effort right now, so I think it's doubtful there will be another major yt-3.x release. If it's simpler to keep it where it is, you might as well since it will all end up in master sooner or later.

**Comment by cphyc** [comment]
I'm closing the PR to merge it against yt-4.

**Pull request closed without merging**
