### PR TITLE
PERF: Add noexcept qualifiers to improve performance on Cython 3

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

Extracted from #4575 (patch by @matthewturk)
Partially adresses #4355

### CODE REVIEW

**Comment by matthewturk** [comment]
Can we instead just get that one in?  I don't want to have my commits subsumed into this PR.

**Comment by neutrinoceros** [comment]
https://github.com/yt-project/yt/pull/4575 is messy because we're both working on it, so rebasing can only happen once. I'd like to avoid destructive history rewriting, which is why I'm proposing to extract known-good bits instead.

**Comment by matthewturk** [comment]
I would prefer we keep the history in this case, even though we are both working on it.  I will also admit I was rather taken aback that you took my commits and compressed them into a new PR that was authored by you without first suggesting or asking, and I think I would like to suggest that step not be taken in the future.

**Comment by neutrinoceros** [comment]
Sorry about that, I meant no offense.

**Pull request closed without merging**
