### PR TITLE
Grid visitors implementation

### PR DESCRIPTION
**Pull request by MatthewTurk**
This implements a fast indexing system for grids, using the grid visitors.

I have exported this from https://bitbucket.org/yt_analysis/yt/pull-requests/2253 .

### CODE REVIEW

**Comment by yt-fido** [comment]
Can one of the admins verify this patch?

**Comment by yt-fido** [comment]
Can one of the admins verify this patch?

**Comment by jzuhone** [comment]
Hi @MatthewTurk, do we know what is blocking on this? I looked a bit at the test failures and think if I spent a bit of time trying to understand the changes I might be able to fix them.

**Comment by cphyc** [comment]
Hey! 
Would it be possible to summarize the changes introduced by this PR? As it is quite technical and touching deep parts of the code, I'm a bit confused about what's happening there.

**Comment by MatthewTurk** [comment]
I've changed this to target `yt-4.0`.

**Comment by MatthewTurk** [comment]
Closing and will re-open once it's ready for review.

**Pull request closed without merging**
