### PR TITLE
RAMSES: Read rt file descriptor

### PR DESCRIPTION
**Pull request by cphyc**
## PR Summary

This allows reading the `rt_file_descriptor.txt` file (if any) to autodetect the fields within the file.

## PR Checklist

- [x] New features are documented, with docstrings and narrative docs
- [x] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
close/open to refresh CI now that unrelated failures are resolved on main

**Comment by cphyc** [comment]
Test errors are real! Will work on it :)

**Comment by cphyc** [comment]
Hey @mtrebitsch, could you confirm this works for you?

**Review by matthewturk — APPROVED** [review]

**Comment by neutrinoceros** [comment]
trying to reach @mtrebitsch again

**Comment by matthewturk** [comment]
I'm OK with this going in -- how about y'all?

**Comment by neutrinoceros** [comment]
Still waiting for at least manual testing, as of our latest private discussion with @cphyc

**Comment by neutrinoceros** [comment]
at this point, it doesn't seem worth waiting any more (to me). @cphyc , how about we merge this as is ?

**Comment by cphyc** [comment]
Let's go!

**Review by neutrinoceros — APPROVED** [review]

**Pull request merged**
