### PR TITLE
Remove INST_CONDA option from install script

### PR DESCRIPTION
**Pull request by ngoldbaum**
Following up on the discussion from yt-dev, this implements the removal of the INST_CONDA option from the install script. I've also updated the docs to match. In addition, this now makes `yt update --all` a no-op. It was already deprecated.

I've tested this using `test_install_script.py` on my Mac. I'm also going to try testing on a Linux box as well.

### CODE REVIEW

**Comment by jzuhone** [comment]
In theory this means we might be able to support Windows installs from this, but that's for another day.

**Comment by ngoldbaum** [comment]
`test_install_script.py` passed on my linux box.

**Comment by chummels** [comment]
I'm confused by why `yt update --all` is now a no-op.

Also, are there any corner cases for someone who may have not updated their code in the last 1.5 months, and has not moved over from bitbucket and just lost the ability to update their source?  I think it is fairly common to have people not updating their code over that timescale, and now it seems like they have to do a full re-install to get the code?  Or perhaps I'm off-base here.  Just checking what the implications are for this before this somewhat significant PR gets merged only a few hours after being proposed on the dev list.

**Comment by ngoldbaum** [comment]
> I'm confused by why yt update --all is now a no-op.

Because this functionality depended on the `INST_CONDA=0` part of the install script existing. Now that no longer exists.

> Also, are there any corner cases for someone who may have not updated their code in the last 1.5 months, and has not moved over from bitbucket and just lost the ability to update their source? I think it is fairly common to have people not updating their code over that timescale, and now it seems like they have to do a full re-install to get the code? 

I don't think so. `yt update` should continue to work. The mirror to bitbucket is still functioning, so updating the mercurial repository they have checked out will still continue to work and they will get the latest version.

If they did `yt update --all` they wouldn't see their dependencies updated, although they wouldn't have even without this pull request because it's been a long time since we updated the versions of dependencies that are hard-coded for the `INST_CONDA=0` option in the current install script.

`INST_CONDA=1` has been the default for more than a year (since last March). It's been even longer since the `INST_CONDA=0` path was updated. The fully-from-source install is painful to update, quite fragile, and doesn't even work on many operating systems (due to missing or old OpenSSL headers).

> Or perhaps I'm off-base here. Just checking what the implications are for this before this somewhat significant PR gets merged only a few hours after being proposed on the dev list.

I don't think this will be merged today. I only moved to make the PR because I didn't get any negative feedback on the dev list. My sincere apologies if that felt like I was not giving you time to respond.

**Comment by ngoldbaum** [comment]
Thanks for reminding me, though. After commenting just now I realized there were still some spots in the docs where we were advising people to use "yt update --all". I've gone ahead and updated those sections.

**Comment by chummels** [comment]
Thanks for the info about the implications for this PR.  I can get behind it, just wanted those clarifications.  Seems reasonable and simplifies installation notes and procedures.

**Comment by chummels** [comment]
I would approve this, but it doesn't seem like I have privileges to do that.

**Comment by jzuhone** [comment]
@chummels odd--we need to fix that.

**Comment by ngoldbaum** [comment]
@chummes it looks like you're in the yt project org so I think you do have permissions to approve. It's a little buried in the github interface though so you might just be missing it. Click over to the "Files Changed" tab, you should see a green "Review Changes" button. Click it, one of the options will be to approve the pull request.

**Comment by jzuhone** [comment]
@ngoldbaum what's our rule for merging this? how many approvals do you want?

**Comment by ngoldbaum** [comment]
@jzuhone let's give it until next week just in case someone doesn't check there yt email very often.

**Pull request merged**
