### PR TITLE
remove a test that's been disabled for 7 yrs

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

A dead test, probably better to remove it than trying to revive it after so long.

## PR Checklist

- [x] pass `black --check yt/`
- [x] pass `isort . --check --diff`
- [x] pass `flake8 yt/`

### CODE REVIEW

**Comment by neutrinoceros** [comment]
my reasoning exactly :-)

**Comment by matthewturk** [comment]
so have we checked that it fails?

**Comment by neutrinoceros** [comment]
Nope, but it relies on refine_amr, which is going to be removed :) (and that's how I discovered it)

**Comment by matthewturk** [comment]
oh, got it.  Thanks.

**Pull request merged**
