### PR TITLE
Fix some invalid escape sequences.

### PR DESCRIPTION
**Pull request by brittonsmith**
This fixes some invalid escape sequence warnings that have been showing up in later versions of python.

### CODE REVIEW

**Comment by matthewturk** [comment]
so none of the test failures look real to me ... what do you think?

**Comment by Xarthisius** [comment]
> so none of the test failures look real to me ... what do you think?

I'll fix that. It's due to something I discovered during testing of yt4 branch. Please don't merge until then

**Comment by Xarthisius** [comment]
@yt-fido test this please

**Comment by munkm** [comment]
Hey @brittonsmith would you mind merging or rebasing with master? I think these tests should be fixed now and I just want to make sure things pass before merging.

**Comment by brittonsmith** [comment]
Sorry, spaced out. I just rebased.

**Comment by matthewturk** [comment]
@brittonsmith Could you merge with master now that the tests seem to be fixed?

**Pull request merged**
