### PR TITLE
solve bug when deposit velocity/age fields?

### PR DESCRIPTION
**Pull request by HugoPfister**
I use RAMSES and when trying to get deposit fields (ptype_cic_velocity_x or y, z, age) I got the value off by a factor of scale_l / scale_t.

This PR solves my problem in my case...

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Will this change the output of existing scripts that people have written? If so I we might need a somewhat different solution.

Can you share a script that triggers the issue you originally ran into? If possible, please either use one of the example datasets at yt-project.org/data or share the dataset you're using so that we all can run the script locally.

It may be that we just need to do a little bit more massaging of units *inside* of these functions.

**Comment by ngoldbaum** [comment]
ping @HugoPfister - it would be really nice to get a script showing the behavior that this fixes to make the discussion more concrete.

**Comment by HugoPfister** [comment]
Hey,

Sorry for late answer. I will answer in my case, which means using RAMSES.

> Will this change the output of existing scripts that people have written? If so I think we might need a somewhat different solution.

Well, yes... it will change everything by a factor ~scale_l / scale_t, but they will get the right value then.

I downloaded the output_00080 of the test suite and here is the results I got with the last version of YT (first), and with this PR (second).
I first realised I had this problem with my own sims by doing projection of ('deposit','stars_cic_velocity_x') which gave me, as you can see, crazy values.
However, I definitely not masterize YT nor Python, but there might be a bug somewhere...

First:
```
In [1]: import yt

In [2]: def stars(pfilter, data):
   ...:     filter = (data['io','particle_age'] != data['io','particle_age'].min())
   ...:     return filter
   ...: 

In [3]: yt.add_particle_filter("stars", function=stars, filtered_type='io')

In [4]: ds=yt.load('output_00080/info_00080.txt', extra_particle_fields=[("particle_age"
   ...: , "d"),("particle_metallicity", "d")])
yt : [INFO     ] 2017-12-05 15:44:33,199 Parameters: current_time              = 1.11921656406
yt : [INFO     ] 2017-12-05 15:44:33,199 Parameters: domain_dimensions         = [64 64 64]
yt : [INFO     ] 2017-12-05 15:44:33,199 Parameters: domain_left_edge          = [ 0.  0.  0.]
yt : [INFO     ] 2017-12-05 15:44:33,199 Parameters: domain_right_edge         = [ 1.  1.  1.]
yt : [INFO     ] 2017-12-05 15:44:33,200 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2017-12-05 15:44:33,200 Parameters: current_redshift          = 0.14255728632206321
yt : [INFO     ] 2017-12-05 15:44:33,200 Parameters: omega_lambda              = 0.723999977111816
yt : [INFO     ] 2017-12-05 15:44:33,200 Parameters: omega_matter              = 0.276000022888184
yt : [INFO     ] 2017-12-05 15:44:33,200 Parameters: hubble_constant           = 0.703000030517578

In [5]: ds.add_particle_filter('stars')
Out[5]: True

In [6]: d=ds.all_data()

In [7]: d['stars','particle_velocity_x'].max().in_units('km/s')
Out[7]: 498.4750424564706 km/s

In [8]: d['deposit','stars_cic_velocity_x'].max().in_units('km/s')
Out[8]: 7.248780257591348e-07 km/s

In [9]: d['stars','particle_velocity_x'].min().in_units('km/s')
Out[9]: -322.44410901890194 km/s

In [10]: d['deposit','stars_cic_velocity_x'].min().in_units('km/s')
Out[10]: -3.023487926923034e-07 km/s

In [11]: d['stars','particle_velocity_x'].mean().in_units('km/s')
Out[11]: 88.24927356122916 km/s

In [12]: d['deposit','stars_cic_velocity_x'].mean().in_units('km/s')
Out[12]: 2.5645659543777975e-09 km/s
```

Second:
```
In [1]: import yt

In [2]: def stars(pfilter, data):
   ...:     filter = (data['io','particle_age'] != data['io','particle_age'].min())
   ...:     return filter
   ...: 

In [3]: yt.add_particle_filter("stars", function=stars, filtered_type='io')

In [4]: ds=yt.load('output_00080/info_00080.txt', extra_particle_fields=[("particle_age"
   ...: , "d"),("particle_metallicity", "d")])
yt : [INFO     ] 2017-12-05 15:48:26,631 Parameters: current_time              = 1.11921656406
yt : [INFO     ] 2017-12-05 15:48:26,631 Parameters: domain_dimensions         = [64 64 64]
yt : [INFO     ] 2017-12-05 15:48:26,632 Parameters: domain_left_edge          = [ 0.  0.  0.]
yt : [INFO     ] 2017-12-05 15:48:26,632 Parameters: domain_right_edge         = [ 1.  1.  1.]
yt : [INFO     ] 2017-12-05 15:48:26,632 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2017-12-05 15:48:26,632 Parameters: current_redshift          = 0.14255728632206321
yt : [INFO     ] 2017-12-05 15:48:26,632 Parameters: omega_lambda              = 0.723999977111816
yt : [INFO     ] 2017-12-05 15:48:26,633 Parameters: omega_matter              = 0.276000022888184
yt : [INFO     ] 2017-12-05 15:48:26,633 Parameters: hubble_constant           = 0.703000030517578

In [5]: ds.add_particle_filter('stars')
Out[5]: True

In [6]: d=ds.all_data()

In [7]: d['stars','particle_velocity_x'].max().in_units('km/s')
Out[7]: 498.4750424564706 km/s

In [8]: d['deposit','stars_cic_velocity_x'].max().in_units('km/s')
Out[8]: 414.1073148241189 km/s

In [9]: d['stars','particle_velocity_x'].min().in_units('km/s')
Out[9]: -322.44410901890194 km/s

In [10]: d['deposit','stars_cic_velocity_x'].min().in_units('km/s')
Out[10]: -172.72539962982336 km/s

In [11]: d['stars','particle_velocity_x'].mean().in_units('km/s')
Out[11]: 88.24927356122916 km/s

In [12]: d['deposit','stars_cic_velocity_x'].mean().in_units('km/s')
Out[12]: 1.4650816872873869 km/s
```

**Comment by ngoldbaum** [comment]
OK, I can confirm that this is definitely a bug and that the proposed fix does fix it. I was also able to reproduce this with an Enzo dataset so there's nothing RAMSES-specific, it was just an outright bug.

Thanks for providing the example, that made it much easier to see what was going wrong!

**Pull request merged**
