### PR TITLE
[bugfix] Fixing velocity unit in gadget_fof frontend.

### PR DESCRIPTION
**Pull request by brittonsmith**
This fixes the velocity unit similarly to the [bugfix for the Eagle frontend](https://github.com/yt-project/yt/pull/1675).

After reading through the subfind manual, I found a proper definition for `time_unit`, so I fixed that, too.  I also corrected similar errors in the OWLS_Subfind frontend.

### CODE REVIEW

**Comment by brittonsmith** [comment]
@yt-fido test this please

**Comment by ngoldbaum** [comment]
Unfortunately the host jenkins is running on at the moment crashed last night. There's no ETA to get it back up :/

Would you be ok with waiting a few days to get the tests back up? I'd merge this now but I'm a bit worried about answer test answers changing.

**Comment by brittonsmith** [comment]
I believe the py2 tests had passed the first time around, but the py3 tests had hung, likely because of the Nebula issue. Not knowing what the issue was, this was why I triggered the tests again.

Anyway, I'm fine with waiting to be safe.

**Comment by brittonsmith** [comment]
What kind of test?

**Comment by ngoldbaum** [comment]
@yt-fido test this please

**Comment by ngoldbaum** [comment]
@brittonsmith if you feel like it please feel free to add a small test that loads a gadget_fof dataset and verifies that all the units are correct.

I've gone ahead and merged this pull request without a new test because it's a strict improvement over the status quo.

**Pull request merged**
