### PR TITLE
[WIP] Fix compiler warnings

### PR DESCRIPTION
**Pull request by Xarthisius**
A bunch of very care-free type changes all over the place aiming at silencing the compiler. Can't wait for this PR to blow up Windows build on appveyor.

### CODE REVIEW

**Comment by matthewturk** [comment]
This sounds like the kind of PR that should be merged without review before tests have completed.

**Comment by Xarthisius** [comment]
> This sounds like the kind of PR that should be merged without review before tests have completed.

Yeah, I considered force-pushing it as a fixup to a random commit from last 180 days as an easter egg. Think of all the fun of tracking it down!

**Comment by Xarthisius** [comment]
This failure is particularly interesting:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/fido/shiningpanda/jobs/a7d58705/virtualenvs/d41d8cd9/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/fido/workspace/yt_py38_git/yt/testing.py", line 733, in true_wrapper
    return func(*args, **kwargs)
  File "/home/fido/workspace/yt_py38_git/yt/visualization/tests/test_particle_plot.py", line 256, in test_set_units
    pp = ParticlePhasePlot(sp, ("Gas", "density"), ("Gas", "temperature"), ("Gas", "particle_mass"))
  File "/home/fido/workspace/yt_py38_git/yt/visualization/particle_plots.py", line 335, in __init__
    profile = create_profile(
  File "/home/fido/workspace/yt_py38_git/yt/data_objects/profiles.py", line 1313, in create_profile
    obj.add_fields([field for field in fields])
  File "/home/fido/workspace/yt_py38_git/yt/data_objects/profiles.py", line 113, in add_fields
    self._bin_chunk(chunk, fields, temp_storage)
  File "/home/fido/workspace/yt_py38_git/yt/data_objects/profiles.py", line 860, in _bin_chunk
    func(bf_x, bf_y, deposit_vals, fdata[:, fi].size,
  File "yt/utilities/lib/particle_mesh_operations.pyx", line 174, in yt.utilities.lib.particle_mesh_operations.NGPDeposit_2
    assert i1 > 0
AssertionError
```
I put those asserts, because until now we were using uninitialized values of index to assign particle deposits. Now I set -1 as a default...

**Comment by matthewturk** [comment]
Reading over the code that generates that, I see:

```
        for j in range(y_bin_edges.shape[0]):
            if (ypos >= y_bin_edges[j]) and (ypos < y_bin_edges[j+1]):
                j1 = j
                break
```

so if we set the final bin edge by the maximum value for ypos, it will never be inside the if statement.

Also, `j+1` will eventually run off the edge, since it's iterating over `y_bin_edges.shape[0]` and accessing `j+1`.

**Comment by matthewturk** [comment]
Also, wait, why are we asserting it's `> 0`?  Shouldn't it just need to be `>= 0`?

**Pull request closed without merging**
