### PR TITLE
Change IDV to use raycasting

### PR DESCRIPTION
**Pull request by MatthewTurk**
This changes some items inside IDV.  There are two, one major and one minor.  The minor change is to change internal variables to be things that are used elsewhere in the literature; for instance, `lookat` is now `modelview`.

The other change is to change how the rays are cast through the data.  Previously, we had been doing `left_edge` and `right_edge` checks, but now we're going to go ahead and actually compute the intersections and use those for figuring out when we hit and exit the cube.  This matches much of the logic from `grid_traversal.pyx` now.

I believe that there may be an issue with off-by-one-half, which @Xarthisius has previously fixed, but I am not 100% certain that I have correctly fixed that here.  I would appreciate a set of eyes on it.

### CODE REVIEW

**Comment by MatthewTurk** [comment]
This PR now includes a refactoring of the shader objects to allow for concatenation of multiple files.  This makes ray tracing fragment shaders easier to write, as we can have (for instance) the ray tracing be separate from the calculation of the output value.

I believe this is ready to review at this point.  There may be artifacting when the camera is inside a grid; I am hoping to determine the issues related to that, but from my perspective this is still valid to go in as it's an improvement over the existing code.

**Comment by Xarthisius** [comment]
I haven't looked at changes yet, but I tried to play with it:

```python
import yt
ds = yt.load('IsolatedGalaxy/galaxy0030/galaxy0030')
yt.interactive_render(ds)
```

I moved camera around then  hit '2' in order to switch to projection shader. I got:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "yt/visualization/volume_rendering/interactive_vr_helpers.py", line 102, in _render_opengl
    rc.start_loop(scene, c)
  File "yt/visualization/volume_rendering/interactive_loop.py", line 184, in start_loop
    for i in self(scene, camera, callbacks):
  File "yt/visualization/volume_rendering/interactive_loop.py", line 193, in __call__
    scene.render()
  File "yt/visualization/volume_rendering/interactive_vr.py", line 880, in run_program
    collection.run_program()
  File "yt/visualization/volume_rendering/interactive_vr.py", line 293, in run_program
    with self.program.enable():
  File "yt/visualization/volume_rendering/interactive_vr.py", line 283, in program
    self.fragment_shader)
  File "yt/visualization/volume_rendering/shader_objects.py", line 50, in __init__
    self.link(vertex_shader, fragment_shader)
  File "yt/visualization/volume_rendering/shader_objects.py", line 69, in link
    raise RuntimeError(GL.glGetProgramInfoLog(self.program))
RuntimeError: b"error: fragment shader input `inverse_view' has no matching output in the previous stage\n"
```

**Comment by MatthewTurk** [comment]
@Xarthisius Thanks!  I'll update that and keep working.

**Comment by MatthewTurk** [comment]
I've just pushed some changes that get this a lot closer, but not totally there, to being ready to go.  Only a handful of things left, mainly updating the documentation and streamlining one or two things with setting up the IDV context.  Here's an example:

https://gist.github.com/MatthewTurk/3f9edcc6dbd61748ef953208a4e502bf

Note that you can change things like the `scene.annotations[0].text` and then on the next redraw it will be updated.

As it stands, the scripts are still a bit more verbose than I'd like, but I think the basics are there now.

If there's a target for when the 3.4 release goes, I can estimate if this could go in before it; I think it's really, really close, but I don't want to hold up 3.4.

**Comment by MatthewTurk** [comment]
Closing and will re-open once it's ready for review.

**Pull request closed without merging**
