### PR TITLE
Fix to load the swiftsim snapshot by removing the unused "RuntimePars"

### PR DESCRIPTION
**Pull request by weiguangcui**
## PR Checklist

- [ ] New features are documented, with docstrings and narrative docs
- [ ] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
Hi. In #4921 we tried to make sure this bit of code stayed backward compatible and improved forward compatibility. As far as I can tell what you're proposing here is to rip off the backward compatibility layer. Can you explain exactly what is not currently working with the main branch yet ?

**Comment by neutrinoceros** [comment]
(admittedly #4921 is not released yet so I don't expect yt 4.3.1 to work, but the dev branch should)

**Comment by weiguangcui** [comment]
> Hi. In #4921 we tried to make sure this bit of code stayed backward compatible and improved forward compatibility. As far as I can tell what you're proposing here is to rip off the backward compatibility layer. Can you explain exactly what is not currently working with the main branch yet ?

Hi, sorry for forgetting to reply to this question. Yes, the new swift snapshot doesn't include that ["RuntimePars"] in its snapshot anymore. So it is removed, as such the "periodic" parameter is reading from another place: `periodic = int(parameters["InitialConditions:periodic"])`

**Comment by neutrinoceros** [comment]
@weiguangcui I still expect you shouldn't have any issue with the development branch. Have you tried installing it ?
```
python -m pip install git+https://github.com/yt-project/yt.git
```

If I'm right then your proposed patch is unecessary. And if something else still needs fixing we need to take care of backward compatibility too, which is currently missing from your approach.

**Pull request closed without merging**
