### PR TITLE
make requests a part of yt.utilities.on_demand_imports

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary
This is an alternative PR to #3098, and hopefully less controversial

### CODE REVIEW

**Review by cphyc — APPROVED** [review]

**Comment by neutrinoceros** [comment]
@yt-fido test this please

**Comment by Xarthisius** [comment]
@yt-fido test this please

**Review by munkm — COMMENTED** [review]
I agree that this is a better solution than a hard dependency!! 

I think you might want to add requests to the testing requirements files/infrastructure here too.

**Comment by neutrinoceros** [comment]
Oh right that's what I'm missing, thanks !
That also reminds me I would very much like to move forward with #3078 so we can start gathering our deps (both required and optional) into one file !

**Review by matthewturk — APPROVED** [review]

**Review by munkm — APPROVED** [review]

**Pull request merged**
