### PR TITLE
Abstract data structures

### LINKED ISSUE #2426: Discussion: make Dataset an abstract class ?
about frontends development in general: the Dataset class, as it stands, is an abstract class as
some of its code relies on unimplemented methods. When we wrote the AMRVAC frontend with @n-claes, especially as we were getting started, it was quite confusing how there wasn't a really explicit edge between what has to be there for the child class `<YourFrontend>Dataset` to work, and what can be left unimplemented (at least a first). Taking inspiration from existing frontends also adds to the confusion in some ways, because most frontends will add code-specific methods, so as a newcomer you have to jump from one to the other in order to grasp which is which.

I was thinking that it could help future contributors to make Dataset an actual abstract class by inheriting from `abc.ABC` . As the exact syntax for doing this seems different in python 2, maybe that could be a change reserved for yt 4.0.

I'm not aware of any good reason why not to do this, though there might very well be. Any input ?

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

fix #2426 

This is a first effort to make new frontend crafting process easier.
Class methods that require implementation are marked as abstract, and I also made some slight improvements over the existing internal docs both in `Dataset` definition and in the _skeleton frontend template.

Note that one frontend required minor adjustments to this abstraction (GADGET).

### CODE REVIEW

**Comment by neutrinoceros** [comment]
Nothing too bad, but this first draft uncovered two weaknesses in the Gadget frontend. Namely `GadgetFOFHaloDataset` is missing  `_is_valid` and `_set_code_unit_attributes` methods.
The latter is currently circumvented by doing the work in `set_code_units()`, so I'm hoping this can easily be corrected without breaking the frontend. The former simply means that this class is never meant to be instantiated directly by `yt.load()`, so it's very easy to fix too.

**Comment by neutrinoceros** [comment]
Important note: `abc.ABC` was actually introduced in python 3.4, so to allow the py2 tests to pass, I renounced inheriting from it anywhere. In this implementation, it's still allowed to instantiate classes that have abstract methods, so it's more permissive than intented, but we preserve the main result: frontends authors get a very clear error if they forget to implement those methods.

In the future, when py2 tests are dropped, this work can be completed.

**Comment by matthewturk** [comment]
In principle I'm quite supportive of making us more formalized.  I think it might be wise to identify this and other improvements that would all serve to support that, as well, and see if we can pull the band-aid off all at once.

**Comment by munkm** [comment]
@matthewturk where would be a good place to have that conversation? In the linked issue, or here? I'd like to make sure we have the discussions about this in one place so it's easier to track the history and make sure everything gets done. 

This might be a big enough improvement that it merits a [YTEP](https://ytep.readthedocs.io/en/master/).

**Comment by neutrinoceros** [comment]
Weirdly, the py38 job was completed (successfully) hours ago but is still shown as "pending" here.

**Comment by brittonsmith** [comment]
I like this. As the person responsible for the `GadgetFOFHaloDataset`, both of those changes seem fine. You're right, the dataset is not meant to be instantiated with `yt.load`, so the `_is_valid` returning False is good. I think the other change to setting units is also fine, but am slightly less sure.

One other comment, I wonder if it would be better to issue this to the `yt-4.0` branch. Python 2 compatibilities like the `six` module have been removed in that branch, so if this PR goes into `master`, we'll need to do some more of that when `yt-4.0` goes into `master`. On the other hand, `yt-4.0` isn't running answer tests yet, and I'd definitely like to see those be run on this.

**Comment by neutrinoceros** [comment]
Thank you !
Unfortunately I'm stuck on the master's branch because I never managed to install yt-4.0 in my env yet (despite several attempts), so this factor outweighs other criteria... plus, answer tests are definitely needed to validate this. You are right though, this change would look better without six/python2.

**Comment by jzuhone** [comment]
@neutrinoceros maybe we should try helping you get `yt-4.0` set up? I agree with @brittonsmith that it would be better to get this working there.

**Comment by neutrinoceros** [comment]
Nevermind I finally found a workaround to the error that was showing up on my Mac (from https://github.com/huggingface/neuralcoref/issues/97), thanks for offering to help though :)

**Comment by neutrinoceros** [comment]
Alright let's try it with yt4 then (#2556)

**Comment by neutrinoceros** [comment]
I'm closing this PR this the yt-4.0 version of it is moving forward.

**Pull request closed without merging**
