### PR TITLE
MNT: Dedup of mailmap aliases

### PR DESCRIPTION
**Pull request by matthewturk**
In preparation for sending out invites for the paper, @Xarthisius started deduping the mailmap.  I'll continue it.

### CODE REVIEW

**Comment by matthewturk** [comment]
This is ready to go -- I don't think I've missed any, but I will find out and issue a followup if so.

**Comment by neutrinoceros** [comment]
pre-commit.ci autofix

**Comment by neutrinoceros** [comment]
ah, new protection rules from GitHub won't let pre-commit.ci fix this. I'll do it manually then

**Comment by neutrinoceros** [comment]
No can do. The laptop I'm working on today isn't properly configured. @matthewturk , can you fix it ?

**Comment by matthewturk** [comment]
Over here, it says it's right.

**Comment by neutrinoceros** [comment]
here's the patch I get from running `pre-commit run --all-files` on your branch
```patch
diff --git a/.mailmap b/.mailmap
index 9d8bc9676..b5cbc1ed9 100644
--- a/.mailmap
+++ b/.mailmap
@@ -153,4 +153,3 @@ Ryan Farber <rjfarber@umich.edu> Ryan Farber <ryanjsfx@mpa-garching.mpg.de>
 Max Gronke <max.groenke@gmail.com> Max Gronke <maxbg@astro.uio.no>
 Martin Alvarez Sergio <martin.alvarez.sergio@gmail.com> Sergio <martin.alvarez.sergio@gmail.com>
 Martin Alvarez Sergio <martin.alvarez.sergio@gmail.com> MartinAlvarezSergio <51377626+MartinAlvarezSergio@users.noreply.github.com>
-
```

**Comment by matthewturk** [comment]
Won't let me commit that change, because it thinks it's already in.

I have more changes to make so let's put this back on backburner now.

**Comment by neutrinoceros** [comment]
is this ready ?

**Comment by matthewturk** [comment]
Yes, I believe so.

**Pull request merged**
