### PR TITLE
Enhanced test cases for image_array.py in data_objects

### PR DESCRIPTION
**Pull request by git-abhishek**
## PR Summary

Updated the corresponding test cases to increase coverage.
## PR Checklist

- [X] Code passes flake8 checker
- [X] New features are documented, with docstrings and narrative docs
- [X] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Hmm, the coverage report never got generated :/

**Comment by git-abhishek** [comment]
Is there a way to rebuild the PR on Travis without making any changes or should I do few multiple changes to trigger a build again? It could be due to some [internal problems](https://github.com/lemurheavy/coveralls-public/issues/116) at Coveralls.

**Comment by ngoldbaum** [comment]
You can push a no-op commit or do a no-op amend on your last commit and force-push. I can also manually restart the travis build using my admin privileges.

**Comment by git-abhishek** [comment]
Awesome, never heard of no-op commit. I will do it then :)

**Comment by ngoldbaum** [comment]
Here's what I usually do:

```
# make sure the working directory is clean
git reset --hard
git checkout my-branch

git commit -a --amend
<exit editor without changing anything>

git push -f origin my-branch
```

This won't change the content of your last commit, although it will change the commit time to the time when you amended.

**Comment by git-abhishek** [comment]
I did `git commit --allow-empty -m "Trigger notification"`.
[got it from here](https://coderwall.com/p/vkdekq/git-commit-allow-empty)

**Comment by git-abhishek** [comment]
Strange, now the Coveralls link is not showing here. On Travis the build is successful for all the environments but only different message is in OSX where it shows:
 `Done. Your build exited with 0.
/Users/travis/.travis/job_stages: line 166: shell_session_update: command not found`.

**Comment by ngoldbaum** [comment]
TBH I haven't really been super enthusiastic about the experience with coveralls. Matplotlib and unyt use codecov.io, which I think is a bit nicer and less buggy. Would you be open to looking into switching over to codecov.io? Or do you think we could get coveralls working?

**Comment by git-abhishek** [comment]
I did not expect such issues with coveralls. It makes sense to try codecov.io integration. I will do it.

**Pull request merged**
