### PR TITLE
Make uniq_id a little bit more unique

### PR DESCRIPTION
**Pull request by Xarthisius**
## PR Summary

Add some more uniqueness to `unique_identifier`

### CODE REVIEW

**Review by matthewturk — APPROVED** [review]
This seems like a definite improvement.

**Review by neutrinoceros — APPROVED** [review]

**Comment by neutrinoceros** [comment]
This is intended as a fix to https://github.com/yt-project/yt/issues/3319, right ?

**Comment by Xarthisius** [comment]
> This is intended as a fix to #3319, right ?

Yes, but now I see new errors that are all related to cached ewah files

**Comment by matthewturk** [comment]
I can help to address those if need be, but the ewah file caching may need
additional information, as right now it's a sidecar file that only uses
filename, ewah index version, and the order.

**Comment by Xarthisius** [comment]
Questions are: why it's being generated during every run, and why it's messing up the field detection.

**Comment by Xarthisius** [comment]
My latest commit should fix the failures, but it's only a workaround. Actual bug: #3327

**Review by jzuhone — APPROVED** [review]

**Pull request merged**
