### PR TITLE
Add a filter to ytLogger to avoid duplicated successive entries

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

If there's any appetite for  https://github.com/yt-project/yt/issues/2865, here's the fix
fix https://github.com/yt-project/yt/issues/2865
fix https://github.com/yt-project/yt/issues/2859

## A dummy test
Inserting this at the end of `yt/__init__.py`
```python
for _ in range(30):
    mylog.critical("All work and no play makes Jack a dull boy.")
```

and running
```bash
python -c "import yt"
```

## without the filter
```
yt : [CRITICAL ] 2020-08-16 19:24:52,893 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,893 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,894 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,894 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,894 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,894 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,894 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,894 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,894 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,894 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,894 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,894 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,894 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,894 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,895 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,895 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,895 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,895 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,895 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,895 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,895 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,895 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,895 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,895 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,895 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,895 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,895 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,895 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,895 All work and no play makes Jack a dull boy.
yt : [CRITICAL ] 2020-08-16 19:24:52,895 All work and no play makes Jack a dull boy.
```
## with the filter
```
yt : [CRITICAL ] 2020-08-16 19:24:17,119 All work and no play makes Jack a dull boy.
```
## PR Checklist

- [x] pass `black --check yt/`
- [x] pass `isort . --check --diff`
- [x] pass `flake8 yt/`
- [x] pass `flynt yt/ --fail-on-change --dry-run -e yt/extern`
- [ ] New features are documented, with docstrings and narrative docs
- [ ] Adds a test for any bugs fixed. Adds tests for new features.

### CODE REVIEW

**Comment by matthewturk** [comment]
First off, excellent choice of examples.

The second thing I wonder is if it's necessarily the right thing to do this if the time stamp is different.  I could see both ways.

**Comment by neutrinoceros** [comment]
The timestamp is internally represented as `record.created` (in POSIX time). We could take it into account in the filter class to only filter out identical entries emitted within 10s (or any other value, like 1s, or finer ?) of each other.
I'm not aware of any real case where we'd want to have more than one entry every 10s, and even then I think this would probably just feel like a bad proxy for a progress bar.

If you think it's necessary, maybe this value could be exposed through the config file and a public function like `yt.set_logger_max_freq_repeat` ?

My proposition would be this:
in this PR:
- set a default value to 10s
- offer the possibility to change it via config file

Then later, if it turns out users actually need it, add a `yt.set_logger_max_freq_repeat` function.

wdyt ?

**Comment by matthewturk** [comment]
You know, maybe this could just go in as-is.  We log too much.  Let's start pulling back from that with this PR addressing one of the more egregious symptoms.

**Comment by neutrinoceros** [comment]
This seems like the easiest way to go without creating unnecessary maintenance cost and downstream confusion, imo.

**Review by munkm — APPROVED** [review]

**Comment by munkm** [comment]
> My proposition would be this:
> in this PR:
> 
> set a default value to 10s
> offer the possibility to change it via config file

I think we could merge this as-is too and open another issue to make sure we want to update the behavior to include a default and a config file.

**Pull request merged**
