### PR TITLE
Remove parenthesis in getitem calls

### PR DESCRIPTION
**Pull request by cphyc**
## PR Summary

In accordance with the style of the code, replace all occurences of `data[("gas", "density")]` with `data["gas", "density"]` (no extra parentheses).

This is merely a stylistic change.

### CODE REVIEW

**Comment by matthewturk** [comment]
I feel like once upon a time we did it this way, and then when we moved to mandating field tuples we changed it, and I don't think I particularly cared for the change then but I honestly don't know that I am that invested one way or the other now.  It does feel like a lot of churn though.

**Comment by cphyc** [comment]
To be fair I'm also happy for this _not_ to be merged. However, at present, we're using both styles in the codebase (depending on who wrote it), so for the sake of uniformity, it'd be marginally better to settle on either one of the formats (`data[("gas", "density")]` vs `data["gas", "density"]`).

**Comment by cphyc** [comment]
@yt-fido test this please...

**Comment by chrishavlin** [comment]
+1 from me for removing parenthesis. also agree it'd be nice to merge ASAP if folks agree.

**Comment by matthewturk** [comment]
bandaids are meant to be ripped off, I suppose!

**Comment by matthewturk** [comment]
And actually, how hard would it be to make a rule for ruff to apply this?  Probably easy to write, hard to confine to just yt data objects, now that I'm thinking of it.

**Comment by neutrinoceros** [comment]
I had the same idea but I'm too intimidated to try it out myself :D

> hard to confine to just yt data objects, now that I'm thinking of it.

I believe parentheses are never required anywhere that looks like `[(... ,...)]`, because they are syntactically meaningless there, so I think this *would* actually work as a general purpose listing rule !

**Comment by matthewturk** [comment]
> I believe parentheses are never required anywhere that looks like `[(... ,...)]`, because they are syntactically meaningless there, so I think this _would_ actually work as a general purpose listing rule !

Yeah, you must be right.  I think I got confused because of the way h5py recommends `[()]` which is specifically an empty tuple, so I think I got a bit mixed up.

**Comment by neutrinoceros** [comment]
Would you like to give it a go or is it okay if we just open a feature request on ruff ?

**Comment by cphyc** [comment]
Id say let's open an issue; I won't have time to implement this anytime soon.

**Comment by neutrinoceros** [comment]
My question was meant for Matt, sorry for being unclear !

**Comment by neutrinoceros** [comment]
No conflict after two weeks *and* no objection in sight, so I'll push the button. Thanks all !

**Review by neutrinoceros — APPROVED** [review]

**Comment by neutrinoceros** [comment]
Btw I just opened a feature request on ruff https://github.com/astral-sh/ruff/issues/11990

**Pull request merged**
