### PR TITLE
REL: Manual backports for 4.1.4

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

Manual backports for
- #4261
- #4264
- #4281
- #4285 (only b2762924275b937999d42a12d3fe180724201ccc)
- #4290
- #4297
- #4265 (only 8863b83b9a5ebe2650b8d984363dd7c5d5d4c1b5)

### CODE REVIEW

**Comment by neutrinoceros** [comment]
CI is suffering a lot from #4299, so I may end up backporting a patch for it too

**Comment by matthewturk** [comment]
lgtm

**Comment by neutrinoceros** [comment]
⚠️  I also included the version bump

**Comment by neutrinoceros** [comment]
> ⚠️ I also included the version bump

Doesn't seem like a good idea in retrospect, let's wait until we agree to _do_ the release. I'll remove this commit.

**Comment by neutrinoceros** [comment]
@matthewturk this is ready to go

**Comment by neutrinoceros** [comment]
I included the most significant commit from #4265 (8863b83b9a5ebe2650b8d984363dd7c5d5d4c1b5)

**Comment by matthewturk** [comment]
I'm good with this going in.  I'll wait for the tests to pass to merge.

**Pull request merged**
